### ISSUE TITLE
[PRE REVIEW]: Test 1

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#1]
**Submitting author:** @arfon (<a href="http://orcid.org/0000-0002-3957-2474">Arfon Smith</a>)
**Repository:** <a href="http://github.com/arfon/joss" target ="_blank">http://github.com/arfon/joss</a>
**Version:** v1.0.0
**Editor:** @kyleniemeyer
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSE @arfon. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@arfon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by arfon** [comment]
@whedon commands

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
I'm sorry @arfon, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by arfon** [comment]
@kyleniemeyer can you assign me as a reviewer and start the review?

**Comment by kyleniemeyer** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
@kyleniemeyer looks like it's failing in the background. Investigating...

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/2. Feel free to close this issue now!
