### ISSUE TITLE
[PRE REVIEW]: Auto-eD: A visual learning tool for automatic differentiation

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#104]
**Submitting author:** @lindseysbrown (<a href="http://orcid.org/0000-0002-9387-1387">Lindsey Brown</a>)
**Repository:** <a href="https://github.com/lindseysbrown/Auto-eD" target ="_blank">https://github.com/lindseysbrown/Auto-eD</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @rasbt, @Atcold

**Author instructions**

Thanks for submitting your paper to JOSE @lindseysbrown. **Currently, there isn't an JOSE editor assigned** to your paper.

@lindseysbrown if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.29 s (237.9 files/s, 154442.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      15           6243           5772          22772
HTML                            23            425              5           3486
Python                           5            310            444           1423
CSS                              6            375             83           1192
reStructuredText                13            392            573            710
Markdown                         3             24              0            117
Jupyter Notebook                 1              0            891             99
TeX                              1              3              0             36
DOS Batch                        1              8              1             27
make                             1              4              6             10
Bourne Shell                     1              0              0              3
-------------------------------------------------------------------------------
SUM:                            70           7784           7775          29875
-------------------------------------------------------------------------------


Statistical information for the repository 'bd9dfa073aa10e5675c6fe35' was
gathered on 2021/02/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Sondak                    17         11196            965           19.61
Rachel Moon                     38         11962           2524           23.36
Xinyue(Cynthia) Wang             5           948              2            1.53
lindseysbrown                  115         25380           9031           55.49

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Sondak              10904           97.4          7.1               16.81
Rachel Moon               11544           96.5          0.3               16.48
lindseysbrown             14516           57.2         11.2               16.33
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00104/jose.00104/10.21105.jose.00104.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1109/5.58337 may be a valid DOI for title: Backpropagation through time: what it does and how to do it

INVALID DOIs

- None
```

**Comment by lindseysbrown** [comment]
Some suggestions for potential reviewers:
- Sidafa Conde
- Kyle Niemeyer

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @Atcold as reviewer

**Comment by whedon** [comment]
OK, @Atcold is now a reviewer

**Comment by labarba** [comment]
hi @Atcold 👋  —  thanks for agreeing to be a review for JOSE! I'll be looking for a second reviewer, and when added here, will start another GitHub where the review happens. In the meantime, have a look at our [documentation](https://openjournals.readthedocs.io/) and ask me anything!

**Comment by labarba** [comment]
@amueller — We're in need of a second reviewer for this submission to the Journal of Open Source Education, JOSE. Would you be amenable to contributing a review? 
"Auto-eD: A visual learning tool for automatic differentiation"
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by labarba** [comment]
I'm still looking for a second reviewer for this submission. @JontySinai — could I interest you in contributing a review for the Journal of Open Source Education, [JOSE](https://jose.theoj.org)? The submission is:
**"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by amueller** [comment]
Sorry for the slow reply, I don't think I have time unfortunately.

**Comment by labarba** [comment]
Thanks for popping in here, @amueller! Maybe another time. (Do unsubscribe to the thread to avoid notifs)

**Comment by labarba** [comment]
@rasbt – Would you be willing to contribute a review on this submission to JOSE? I know you recently reviewed for us, and I don't want to lean to heavily on you, but if you can find the cycles, I'm needing the help. If you cannot do it, but can offer some suggested names for alternative reviewers, I'd be grateful.
Submission title: **"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by rasbt** [comment]
@labarba Thanks for considering me, but I am very time-constrained in the upcoming 1 1/2 months since I will be traveling and have limited access to my computer. 

@Atcold might possibly willing (and possibly excited) to review this article :)

**Comment by labarba** [comment]
Hi @rasbt – thank you! In fact @Atcold already agreed to be a reviewer and I'm looking for a second one. 😃

**Comment by rasbt** [comment]
Oops, I should have double-checked :). Below is a list of machine learning researchers and educators who would be great candidates:

@brohrer
@khakhalin
@muellerzr
@radekosmulski

**Comment by labarba** [comment]
@brohrer Hi Brandon 👋  — I see on your site that you have a lot of educational material. Could I interest you in contributing a review for this submission to JOSE, the Journal of Open Source Education?

> Auto-eD: A visual learning tool for automatic differentiation
> [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

[JOSE](https://jose.theoj.org) is a community led open-source journal to publish articles about educational software and learning modules (human learning, not machine, ha ha).

I already have one reviewer for this one, but need a second one to initiate the review. Have a look and let me know!

**Comment by brohrer** [comment]
Thanks for thinking for me on this, it’s a big vote of confidence. I’m afraid I will have to decline. I have fully booked myself for the rest of the year and I’m having to be extra disciplined in my prioritization.

Sorry!
Brandon

**Comment by labarba** [comment]
Thanks, @brohrer — another time! (Feel free to unsubscribes to this thread to avoid more notifications.)

@khakhalin Hi Arseny 👋  — would you consider contributing a peer review for JOSE? (The Journal of Open Source Education) 
Submission title: **"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by khakhalin** [comment]
Sorry, but I have my plate really full right now :( I'd love to, and I'm happy that you thought about me, I just physically cannot find time for that in nearest 2-3 months. Sorry!!

**Comment by labarba** [comment]
hi @GaelVaroquaux 👋  — Would you consider volunteering a review for JOSE? (The Journal of Open Source Education, sibling journal to JOSS). I already have one reviewer, but need a second to start the review.
Submission title: **"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)
Have a look and let me know! 🙏

**Comment by GaelVaroquaux** [comment]
I'm trying to take a month's holiday and be off the computer, so I fear that I am not the right person. I think that @jilljenn might be an interesting person for this paper.

**Comment by labarba** [comment]
@GaelVaroquaux — Ha ha, a month has past and we still don't have a second reviewer for this submission! Are you back from holiday? Could you help us out?

**Comment by khakhalin** [comment]
Hi Lorena! I'm super-sorry, but I'm still totally under with paperwork and
all the new responsibilities. And also the paper is still not at all close
to anything I ever did before. I'd had to learn a new field to review it,
or at least build some basic idea about it, and I simply don't have time
for this now, even though it is of course very interesting. I'm really
sorry, but I don't think I can help here!

**Comment by labarba** [comment]
hi @muellerzr 👋 — Would you consider volunteering a review for JOSE? (The Journal of Open Source Education, sibling journal to JOSS). I already have one reviewer, but need a second to start the review.
Submission title: **"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)
Have a look and let me know! 🙏

**Comment by labarba** [comment]
hi @merveenoyan — Would you consider volunteering a review for JOSE? (The Journal of Open Source Education, sibling journal to JOSS). I already have one reviewer, but need a second to start the review.
Submission title: **"Auto-eD: A visual learning tool for automatic differentiation"**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)
Have a look and let me know! 🙏

**Comment by labarba** [comment]
hi @rasbt — We're continuing our search for a second reviewer for this JOSE submission, so far with no luck 😞
Do you think you might be able to help us out, now that the semester is closing? Thanks for considering it!

**Comment by rasbt** [comment]
@labarba  I am currently still swamped with tasks -- the semester is going a bit longer than usual this year. But I will put it down on my task list for this month and hope to get to it after the semester and holidays!

**Comment by labarba** [comment]
@rasbt — thank you so much, we've had a real hard time finding reviewers, and will accommodate your schedule. If that's OK, I will assign you now, start the review, and we can re-group in the newly created Review issue 🙏

**Comment by rasbt** [comment]
That sounds like a good plan!

**Comment by labarba** [comment]
@whedon assign @rasbt as reviewer

**Comment by whedon** [comment]
OK, @rasbt is now a reviewer

**Comment by labarba** [comment]
@Atcold 👋 — You had [agreed to review](https://github.com/openjournals/jose-reviews/issues/104#issuecomment-870009251) this submission for us a few months ago. I had a very hard time identifying a second reviewer, and so a lot of time has passed. I want to double-check after all this time that you are still willing and able to review.
Title: **Auto-eD: A visual learning tool for automatic differentiation**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by lindseysbrown** [comment]
@labarba I just wanted to check on this submission since I hadn't seen any updates in a while.

**Comment by rasbt** [comment]
@labarba I would still be happy to help out. (I think I was waiting for the reviewer "Issue" template.)

**Comment by labarba** [comment]
In all my editing experience, it has _never_ been so hard to secure reviewers! Even though we are a grass-roots journal with no parasitic publisher raking in the big bucks, and folks are generally more willing to review, it is a struggle. I will give it another push!

Thank you @rasbt for your willingness to help. Yes, you are right that we need to start the review (in a new issue) with the checklist.

**Comment by labarba** [comment]
@Atcold 👋 — You had [agreed to review](https://github.com/openjournals/jose-reviews/issues/104#issuecomment-870009251) this submission for us a few months ago. We've struggled to secure reviewers! Are you still willing and able to review?
Title: **Auto-eD: A visual learning tool for automatic differentiation**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00104/jose.00104/10.21105.jose.00104.pdf)

**Comment by labarba** [comment]
@whedon add @Atcold as reviewer

**Comment by whedon** [comment]
OK, @Atcold is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/161.

**Comment by labarba** [comment]
@rasbt, @Atcold — the review issue is now opened! Head over to:
https://github.com/openjournals/jose-reviews/issues/161
