### ISSUE TITLE
[PRE REVIEW]: Instructing Pump Test Evaluation using Jupyter

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#106]
**Submitting author:** @eholzbe (<a href="http://orcid.org/0000-0002-1350-9223">Ekkehard Holzbecher</a>)
**Repository:** <a href="https://github.com/eholzbe/Hydraulic-testing" target ="_blank">https://github.com/eholzbe/Hydraulic-testing</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @eholzbe. **Currently, there isn't an JOSE editor assigned** to your paper.

@eholzbe if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (62.0 files/s, 66341.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 1              0           5510            594
TeX                              1             18              0            164
Markdown                         2             32              0             48
Python                           2             13             29             12
-------------------------------------------------------------------------------
SUM:                             6             63           5539            818
-------------------------------------------------------------------------------


Statistical information for the repository 'ef5d59655c0989b71a69d2a9' was
gathered on 2021/02/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ekkehard Holzbecher              2            54              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ekkehard Holzbecher          54          100.0          0.0               14.81
```

**Comment by whedon** [comment]
PDF failed to compile for issue #106 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.00441 is OK
- 10.1016/j.jhydrol.2010.08.033 is OK
- 10.1029/TR036i001p00095 is OK
- 10.1029/TR037i006p00702 is OK
- 10.1111/j.1745-6584.1996.tb02038.x is OK
- 10.1007/s10040-004-0406-5 is OK
- 10.13140/2.1.1848.6721 is OK

MISSING DOIs

- 10.1029/tr016i002p00519 may be a valid DOI for title: The relation between the lowering of the piezometric surface and the rate and duration of discharge of a well using ground-water storage
- 10.1029/tr027i004p00526 may be a valid DOI for title: A generalized graphical method for evaluating formation constants and summarizing well‐field history

INVALID DOIs

- None
```

**Comment by eholzbe** [comment]
Dear JOSE

Thanks for the mail. I updated the bibliography file on github according to
the recommendations.
Concerning possible reviewers, I find only one dealing with Jupyter
projects: bryan.weber from Connecticut.
He seems not to be involved with groundwater, so he may find himself not
the right person for a review.
Can I propose people who are not on your list?

Best regards
Ekkehard Holzbecher

**Comment by eholzbe** [comment]
Is there any activity for manuscripts under pre-review?
I suggest bryanwweber as potential reviewer. 
@bryanwweber
Ekkehard Holzbecher

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #106 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by labarba** [comment]
Hi @eholzbe — Your paper is not compiling because the metadata is nonconforming to the specs. I looked at the paper.md source and I am not quite satisfied as it relates to the Statement of Need, and to how the materials might be used by others. Note this from the [submission requirements](https://openjournals.readthedocs.io/en/jose/submitting.html#submission-requirements):

> Computational learning modules should be complete and immediately usable for self-learning or adoption by other instructors.

And also (further below):

> The goal is that someone reading the JOSE paper has enough information to decide if they’d be interested in adoping the learning module or software. 

More importantly, you say that the material submitted is used to support one lecture on the topic. This is fairly small and seems below the bar of what merits a full journal paper to reflect the scholarly effort. My assessment is that its scope is too minor for proceeding to review. If you have any argument to the contrary, feel free to make it. Otherwise, I will desk-reject it. Bear in mind that JOSE is evaluating the educational resources submitted with the goal of giving scholarly credit via journal publication. We want readers, authors (and their employers) to recognize JOSE papers similarly to research publications, and thus it should represent substantial scholarly effort.

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by eholzbe** [comment]
Dear labarba - there is obviously a misunderstanding concerning the word 'lecture' that I use in the summary. The lecture is not a single lesson, but the course 'Hydraulic Testing' that was held now for a second time at German University of Technology in Oman. The course consists of a practical part in a lab, and a second part that deals with the evaluation of the data. The Jupyter notebook has been the core instruction tool for the second part. Especially in these times, when the students do not have access to the computer labs, this Jupyter notebook became indispensable not only for the instruction during the classes, but also for exercises that the students perform at their homes. The notebook enables the students to approach the topic easily and user friendly, which is the scholarly concept. The efforts made  to set up the notebook are not visible for the student. But there are complex function evaluations and optimization algorithms programmed that work as accurate as those in commercial products. 
Having said all this I summarize that I do not agree with your first impression that you have got and I hope that you come to a different decision. If I a have not made my point clear enough in the current submission, I am ready to hand in a revised version.

**Comment by labarba** [comment]
@eholzbe – Please clarify in your paper how the material could be adopted by another instructor. From our [documentation](https://openjournals.readthedocs.io/en/jose/submitting.html#submission-requirements):

> Computational learning modules should be complete and immediately usable for self-learning or adoption by other instructors. 

This should be made clear in the paper. Explain how much instructional time is involved, how much is direct instruction and how much is student self-directed learning. In part, a difficulty in evaluating your submission has to do with the very specialized language: try to give an explanation for the non-specialist of how this is used in its educational setting.

**Comment by eholzbe** [comment]
Dear Reviewer

Thanks a lot for the valuable feedback on the first submission of the
manuscript. Your comments gave me a lot of momentum for modifications. It's
not only that parts of the text are modified. I shifted text blocks from
one chapter to another. Technical issues that were too specific were
deleted. Parts of the manuscript were extended, mainly concerning the
option for other instructors to use the notebook in their lecturing and
giving their students a playground to explore the methods themselves.

I am sure the new version is strongly improved in the direction that you
wanted, and I hope that this is sufficient for a publication. Of course I
am ready to work on further improvements if that is wished.

Best regards

**Comment by jgorzalski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #106 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by moorepants** [comment]
@labarba asked me to comment as a topic editor. I agree with Lorena in that this is likely too small of a submission for the journal. There is a single notebook that seems like it would accompany one lab session for students to read and explore and a single assignment for that week or even a half week. The notebook is reusable but the assignment and task sheets are not, as they are presented as PDF files with no source (which is also required for this journal). If this were a series of notebooks for all the lab sessions in a course (> 5 or so) then it may fit our requirements. Another thing to keep in mind is that the unit of submission to JOSE should be equivalent to the effort, quantity, and quality of a traditional scientific journal article. This repository does not fit that guideline either.

**Comment by labarba** [comment]
@eholzbe — Thank you again for your patience, as the editorial team is regrouping after pandemic-related disruptions. Two more editors have assessed the submission and concur that it does not meet the bar for substantial scholarly contribution, and thus we decided to reject it.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
