### ISSUE TITLE
[PRE REVIEW]: IndeterminateBeam: A Python package for solving 1D indeterminate beams

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#107]
**Submitting author:** @jessebonanno (<a href="http://orcid.org/0000-0002-4996-6813">Jesse Bonanno</a>)
**Repository:** <a href="https://github.com/JesseBonanno/IndeterminateBeam/" target ="_blank">https://github.com/JesseBonanno/IndeterminateBeam/</a>
**Version:** v2.0.1
**Editor:** @moorepants
**Reviewers:** @amcc1996 , @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSE @jessebonanno. **Currently, there isn't an JOSE editor assigned** to your paper.

@jessebonanno if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.12 s (226.6 files/s, 53885.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          11            740           1556           2839
Markdown                         3             84              0            208
reStructuredText                 6            129             83            147
Jupyter Notebook                 3              0            505            143
TeX                              2             14              2            138
DOS Batch                        1              8              1             26
JSON                             1              0              0             14
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            28            979           2154           3524
-------------------------------------------------------------------------------


Statistical information for the repository '3395e65fd136b6b737024580' was
gathered on 2021/02/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
JesseBonanno                    87         43717          38582          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
JesseBonanno               5135           11.7          0.9                9.35
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/jose.00065 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
Hi @moorepants — you handled the [Beambending](https://jose.theoj.org/papers/10.21105/jose.00065) submission, which this package extends. Can you take this through review?

One question I have is why create a new package and not add functionality to the existing one? It seems like having so many packages to study statics would not be great for the users...

**Comment by moorepants** [comment]
Yes, I'll take this one.

**Comment by moorepants** [comment]
@JesseBonanno, as a pre-review check can you explain here which of the two submission types this submission fits in? You can find the submission requirements here: https://jose.theoj.org/about. I see that you have created a software library for making calculations regarding beams, but that does not fit our specification for "educational software tools". I also do not see any teaching and learning content for use in course lessons which is needed for the "open-source education materials" submission type.

**Comment by JesseBonanno** [comment]
@moorepants I have intended this to be an educational software tool that can be used to check the solutions for beams. It can be thought of as an autograder for students solving for beams. I have also included documentation about the theory behind the solutions. As to why i didnt simply update the original package, i am new to coding and was originally playing around. By now i would say there are no lines from the original package in the the IndeterminateBeam code. It is a completely new code, and is a few thousand lines in length vs the original few hundred.

**Comment by moorepants** [comment]
@whedon assign @moorepants as editor

**Comment by whedon** [comment]
OK, the editor is @moorepants

**Comment by moorepants** [comment]
@alfredocarella Would you be interested in reviewing this submission? It is very similar to your prior JOSE article.

**Comment by moorepants** [comment]
@JesseBonanno Can you recommend some reviewers in the field?

**Comment by moorepants** [comment]
@amcc1996 I see that you've developed the symbeam package. I believe you'd be an appropriate reviewer for this Journal of Open Source Education submission on a similar topic. Would you like to be a reviewer?

**Comment by amcc1996** [comment]
Hello, @moorepants. I would be very happy to contribute to this publication as a reviewer, you can count on me.

**Comment by moorepants** [comment]
Great, thanks! Let me see if I can get a second reviewer and then we'll start.

**Comment by JesseBonanno** [comment]
If @alfredocarella is able to review i think he would be very well suited for the task. I have privately been in contact with him and he has already had a look at the code and given feedback so he is halfway into the role already.

Other potential candiates i can find are Satish Annigeri, Kyle Niemeyer, Cameron Devine (in order of suitability). Chosen for a background in mechanical/civil/structural engineering with knowledge of python.

I would also like to note that since i submitted this paper i made some changes to calculation method based on recommendations from Alfredo Carella. This has led me to a more pythonic code at version v2.0.1 which i am more satsified with. Would i be able to update this review from version v1.2.2 to version v2.0.1 or is that too difficult?

**Comment by moorepants** [comment]
> This has led me to a more pythonic code at version v2.0.1 which i am more satsified with. Would i be able to update this review from version v1.2.2 to version v2.0.1 or is that too difficult?

Yes please update.

**Comment by moorepants** [comment]
@whedon assign @amcc1996  as reviewer

**Comment by whedon** [comment]
OK, @amcc1996  is now a reviewer

**Comment by moorepants** [comment]
@whedon set v2.0.1 as version

**Comment by whedon** [comment]
OK. v2.0.1 is the version.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: :point_left:

**Comment by JesseBonanno** [comment]
I think i am going to have to update the paper to reflect some minor changes to referenced images etc, that i didnt account for during last few commits. I will update the paper now, shouldn't take too long.

**Comment by alfredocarella** [comment]
@moorepants I appreciate being considered as a reviewer. However, as @JesseBonanno  correctly points out, we have exchanged a few emails and I have privately suggested improvements. I am afraid this might appear as a potential conflict of interest, and believe it would be healthy to avoid it if possible.
In case you don't find a second reviewer within reasonable time, I am willing to take the role as a last resource. I just believe I should not be the first choice.

**Comment by moorepants** [comment]
Ok, good to know.

**Comment by moorepants** [comment]
@satish-annigeri would you be interested in reviewing this Journal of Open Source Education submission regarding beam bending structural mechanics?

**Comment by JesseBonanno** [comment]
Sounds fair @alfredocarella, i hadn't considered that.

Also, I have updated the paper to be completely in-sync with any changes from v2.0.1.
I will generate the paper below now.

**Comment by JesseBonanno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: :point_left:

**Comment by moorepants** [comment]
@JesseBonanno From a quick pass in your paper, I see that you use SymPy in your tool but don't include the builtin beam bending functionality in your comparison table. I think it could be worth adding that. Here are the docs: https://docs.sympy.org/latest/modules/physics/continuum_mechanics/index.html

**Comment by amcc1996** [comment]
While we wait to start the more in-depth review process, I skimmed through the contents of the repository to check if something popped out to me.

I completely agree with @moorepants. Without wanting to raise any conflicts of interest here, in my opinion, the article will benefit from a more up-to-date version of the beam bending software out there. As this work relies on a Python implementation, maybe one should consider including the recent alternative [SymBeam](https://github.com/amcc1996/symbeam) in the comparison table, for the sake of completeness. To my knowledge, I do not know of any other Python alternatives, which ultimately motivates me to make this suggestion. Do you think this is reasonable @moorepants , or it grasps the limits of conflict of interests?

Regarding the [`README.md`](README.md) file, I think there is a minor typo in the *Plot results* section. In the sentence *The `plot` method is actually a wrapper that combines these four methods*, it seems that you should be referring to the `plot_beam_internal` method instead. Can you look at it @JesseBonanno?

Last, maybe I am being too peaky, but for those not so acquainted with `plotly`, it could advantageous to include the plotting lines `fig.show()` in the example described in the repository. Otherwise, one may end running `python3 intermediatebeam.py` a number of times an getting absolutely no output. What to do you think @JesseBonanno?

**Comment by moorepants** [comment]
I think it is reasonable to mention closely related packages, regardless of the conflict of interest, but it's fine if they are left out too.

**Comment by JesseBonanno** [comment]
@moorepants I agree that i should add SymPy in.

@amcc1996 I don't have any issues adding in SymBeam. I think it would be dishonest to not include anything with similar capabilities.

And you are correct that is a typo, and i agree i should add in fig.show().

I will make these changes within the next few days.

**Comment by JesseBonanno** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00107/jose.00107/10.21105.jose.00107.pdf) :page_facing_up: :point_left:

**Comment by moorepants** [comment]
@Psycho-Pirate would you be interested in reviewing this Journal of Open Source Education submission regarding beam bending structural mechanics?

**Comment by moorepants** [comment]
I found a second reviewer via twitter. @nicoguaro has kindly agreed to join in.

@Psycho-Pirate, @satish-annigeri, we will move on with the other two reviewers, but you are welcome to join if interested as a third. Otherwise, we can keep the requests as backups. Thanks for the consideration.

**Comment by moorepants** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/111.

**Comment by Psycho-Pirate** [comment]
> @Psycho-Pirate would you be interested in reviewing this Journal of Open Source Education submission regarding beam bending structural mechanics?

Hey Jason, I would definitely be interested in reviewing it. However, I am currently occupied with preparing my GSoC proposal for Sympy. I will be available after few days. Is there any deadline for this?
@moorepants

**Comment by moorepants** [comment]
@Psycho-Pirate Yes, we will agree on some deadlines in #111. Maybe 3 weeks for the first pass. I have two reviewers now, so it is ok and we can save you for a future one.

**Comment by Psycho-Pirate** [comment]
Sounds good to me. I greatly appreciate being considered as a reviewer. Thanks! @moorepants
