### ISSUE TITLE
[PRE REVIEW]: r-cubed: Guiding the overwhelmed scientist from random wrangling to Reproducible Research in R

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#109]
**Submitting author:** @lwjohnst86 (<a href="http://orcid.org/0000-0003-4169-2616">Luke W. Johnston</a>)
**Repository:** <a href="https://gitlab.com/rostools/r-cubed/" target ="_blank">https://gitlab.com/rostools/r-cubed/</a>
**Version:** v3.0
**Editor:** @JasonJWilliamsNY
**Reviewers:** @pschloss

**Author instructions**

Thanks for submitting your paper to JOSE @lwjohnst86. **Currently, there isn't an JOSE editor assigned** to your paper.

@lwjohnst86 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.43 s (122.2 files/s, 32183.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              1              1              1           3048
HTML                             6            463             10           1306
Markdown                         8            208              0            727
Rmd                             18           1563           4718            542
R                               10             66             63            315
CSS                              3             13             28            260
TeX                              3             23              2            259
YAML                             3              4              0             71
-------------------------------------------------------------------------------
SUM:                            52           2341           4822           6528
-------------------------------------------------------------------------------


Statistical information for the repository 'db34f936b54cbeeaf7e654f6' was
gathered on 2021/02/21.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.annepidem.2015.03.002 is OK
- 10.21105/jose.00053 is OK
- 10.1186/s13059-015-0850-7 is OK
- 10.1186/s13059-015-0669-2 is OK
- 10.1007/s11306-017-1299-3 is OK
- 10.1146/annurev-statistics-060116-054104 is OK
- 10.1093/bib/bbx100 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00109/jose.00109/10.21105.jose.00109.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00109/jose.00109/10.21105.jose.00109.pdf) :page_facing_up: :point_left:

**Comment by lwjohnst86** [comment]
Hi! Maybe to push this forward more. I've looked through the list of reviewers and these are some that I feel might be good for this paper. They either have some background in biomedicine, reproducibility, or education in general, based on their listed topics.

- Jeffrey Hollister
- Pat Schloss
- Brandon LeBeau
- Albert Y. Kim
- Kelly Bodwin
- Andrew Duncan
- Jason Williams
- Aayushi Uberoi
- Kate Hertweck (disclaimer: we work together on a project)
- Teon Brooks

**Comment by pschloss** [comment]
I'd be happy to review this submission if needed

**Comment by lwjohnst86** [comment]
Just pinging this to get an update. There's not yet an editor, maybe @labarba could add @pschloss as reviewer?

**Comment by lwjohnst86** [comment]
Doing another ping here as a reminder. Any updates?

**Comment by labarba** [comment]
Thanks for volunteering to review @pschloss !!

**Comment by labarba** [comment]
@whedon assign @pschloss as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by labarba** [comment]
@whedon invite @JasonJWilliamsNY as editor

**Comment by whedon** [comment]
@JasonJWilliamsNY has been invited to edit this submission.

**Comment by JasonJWilliamsNY** [comment]
@whedon assign @JasonJWilliamsNY  as editor

**Comment by whedon** [comment]
OK, the editor is @JasonJWilliamsNY

**Comment by JasonJWilliamsNY** [comment]
Hi @lwjohnst86 glad to see @pschloss as reviewer. I will attempt to find one additional reviewer and get the ball rolling. I don't think we need to wait more than a week.

**Comment by lwjohnst86** [comment]
@JasonJWilliamsNY Just sending another ping as a reminder. You able to find another reviewer?

**Comment by JasonJWilliamsNY** [comment]
Hi @lwjohnst86 doing this by email and will hopefully strike gold soon!

**Comment by JasonJWilliamsNY** [comment]
Thanks for your patience @lwjohnst86 - still sending emails to potential reviewers.

**Comment by JasonJWilliamsNY** [comment]
@whedon assign @fmichonneau as reviewer

**Comment by whedon** [comment]
OK, @fmichonneau is now a reviewer

**Comment by JasonJWilliamsNY** [comment]
@whedon assign @pschloss as reviewer

**Comment by whedon** [comment]
OK, @pschloss is now a reviewer

**Comment by JasonJWilliamsNY** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/122.
