### ISSUE TITLE
[PRE REVIEW]: Neuromatch Academy: a 3-week, online summer school in computational neuroscience

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#110]
**Submitting author:** @thartbm (<a href="http://orcid.org/0000-0002-0045-3769">Bernard Marius &#39;t Hart</a>)
**Repository:** <a href="https://github.com/NeuromatchAcademy/course-content" target ="_blank">https://github.com/NeuromatchAcademy/course-content</a>
**Version:** 1
**Editor:** @emckiernan
**Reviewers:** @TomDonoghue, @PaulScotti

**Author instructions**

Thanks for submitting your paper to JOSE @thartbm. **Currently, there isn't an JOSE editor assigned** to your paper.

@thartbm if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #110 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #110 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf from branch jose_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch jose_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #110 with the following error: 

 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (2712209b765c450f9b53ba41/paper.md): mapping values are not allowed in this context at line 494 column 64 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by thartbm** [comment]
The line mentioned there has a URL in the affiliation (it's an event that has changing physical locations, but a constant web address). I'm guessing that parts of the URL are read to have meaning in yaml (like a colon), can I prevent that somehow?

**Comment by labarba** [comment]
I don't think so. You can try things around and then [Check that your paper compiles](https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles)

**Comment by thartbm** [comment]
Oh, interesting. I only submitted once that compiled. Since I did change the file a bit since first submitting (including replacing one of the colons from the affiliation on line 494 with a comma), I just checked and it had no problems. I'm not sure what to change now.

There are some additional things to work on regarding author names. If you look at the one citation in the paper, I had to indicate what the last name of the first author is, as it contains a space, like my own name. I don't know how to indicate this in the yaml header though so if we leave it as as, this is probably going to enter some people into databases with part of their last name as a first name. There are also two people with their name in uppercase, and this is correct, but might get "fixed" down the line.

**Comment by labarba** [comment]
@whedon generate pdf from branch jose_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch jose_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #110 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:204:in `block in parse_authors': Author (Patrick J Mineault) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
Different error now. Can you check the paper header again?

**Comment by thartbm** [comment]
This is correct: Patrick J. Mineault does not have an affiliation, and that is as it should be. Is there some way I should indicate this?

**Comment by labarba** [comment]
Yes, you can [indicate it as "Independent Researcher,"](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) or something similar.

**Comment by thartbm** [comment]
Alright, I asked Patrick and he's ok with "Independent Researcher". So I've added it, and the PDF compiles but seems to just print the yaml header across ~13 pages.

**Comment by labarba** [comment]
@whedon generate pdf from branch jose_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch jose_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00110/jose.00110/10.21105.jose.00110.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00110/jose.00110/10.21105.jose.00110.pdf) :page_facing_up: :point_left:

**Comment by moorepants** [comment]
FYI, see the conversation here for reference to the size and scope: https://github.com/openjournals/jose/issues/52

**Comment by labarba** [comment]
@thartbm — thank you for linking to the pre-submission enquiry. I have read that now, and got caught up with the discussion about authorship and size of the work submitted.

I have concerns about the author list. 

Authorship guidelines vary from field to field but:

> The minimum requirements for authorship, common to all definitions, are 1) substantial contribution to the work and 2) accountability for the work that was done and its presentation in a publication. […]
> Acknowledgements may be used to denote contributions to the work that do not meet the criteria of authorship such as, supporting the study, general mentoring, collecting data, acting as study coordinator, and other related activities

[COPE Guidelines PDF, p.4](https://publicationethics.org/files/COPE_DD_A4_Authorship_SEPT19_SCREEN_AW.pdf)

**Comment by labarba** [comment]
See also:
http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html#two

**Comment by koerding** [comment]
As a co-founder of NMA and participant in the run-up to this paper I can confirm that we made sure that all authors substantially contributed (and that we spent weeks as a group making that sure for every person). I can also confirm that they all are and feel accountable (and that we explicitly asked each participant).

**Comment by thartbm** [comment]
As reviewers, these 6 people from your list seem to have a related background and knowledge of Python:

Ariel Rokem (arokem)
Teon Brooks (teonbrooks)
Enrico Glerean (eglerean)
Damien Mannion (djmannion)
Manjaru Narayan (mnarayan)
Thomas Donoghue (TomDonoghue)

**Comment by thartbm** [comment]
Hello! Bumping this, and wondering what the status is. :)

**Comment by labarba** [comment]
@whedon assign @emckiernan as editor

**Comment by whedon** [comment]
OK, the editor is @emckiernan

**Comment by labarba** [comment]
Thank you for agreeing to handle this as editor, @emckiernan — note that the submitting author suggested a few reviewers above.

@thartbm — thank you for your patience! We'll be looking to commit two reviewers, and then start the review in a new issue.

**Comment by thartbm** [comment]
@labarba Thanks!
@emckiernan Please note that we are getting ready for the 2021 edition of the summer school so that the main repository's content is being changed right now. The branch for this paper should be untouched though, and I have a copy of last year's materials that I can make available too, if need be. Also, if you need more suggestions for reviewers, we're happy to get them to you.

**Comment by emckiernan** [comment]
@thartbm Thanks for the info, and for the reviewer suggestions! I'll start sending out invitations today!

**Comment by emckiernan** [comment]
Hi, @arokem, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
Hi, @teonbrooks, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by arokem** [comment]
Hi @emckiernan : thanks for calling on me, and apologies for the slowness in replying. This looks really interesting, but I am over-committed at the moment, so I can't take this on.

**Comment by teonbrooks** [comment]
Hi @emckiernan, sorry as well, just now wading through my backlog of things to do 😅. 

I would be happy to review but I am not available until July at the earliest. If that is a problem, I understand, but at the moment, I'm unavailable to do so.

**Comment by emckiernan** [comment]
> Hi @emckiernan : thanks for calling on me, and apologies for the slowness in replying. This looks really interesting, but I am over-committed at the moment, so I can't take this on.

Hi @arokem: no worries, completely understand. Thanks for letting us know!

**Comment by emckiernan** [comment]
> Hi @emckiernan, sorry as well, just now wading through my backlog of things to do 😅.
> 
> I would be happy to review but I am not available until July at the earliest. If that is a problem, I understand, but at the moment, I'm unavailable to do so.

Hi @teonbrooks: No worries. I'm going to contact a few other potential reviewers who might be able to look at this sooner, but I'll definitely circle back to you in July if we need additional reviews. Thanks so much for the offer!

**Comment by emckiernan** [comment]
Hi, @eglerean, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
Hi, @djmannion, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by djmannion** [comment]
> Hi, @djmannion, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

Hi @emckiernan. Thank you for the invitation, but I am unfortunately unavailable for reviewing manuscripts at the moment - apologies.

**Comment by emckiernan** [comment]
> Hi @emckiernan. Thank you for the invitation, but I am unfortunately unavailable for reviewing manuscripts at the moment - apologies.

Hi @djmannion: totally understand. Thanks for letting us know!

**Comment by emckiernan** [comment]
Hi, @mnarayan, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
Hi, @TomDonoghue, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by mnarayan** [comment]
I am unfortunately not available for reviewing this month.

**Comment by emckiernan** [comment]
> I am unfortunately not available for reviewing this month.

Ok @mnarayan, thanks for letting us know!

**Comment by TomDonoghue** [comment]
Hey @emckiernan - yeh, I would be able to review this paper!

**Comment by emckiernan** [comment]
> Hey @emckiernan - yeh, I would be able to review this paper!

@TomDonoghue: Fantastic, thanks so much! Adding you as a reviewer now...

**Comment by emckiernan** [comment]
@whedon assign @TomDonoghue as reviewer

**Comment by whedon** [comment]
OK, @TomDonoghue is now a reviewer

**Comment by emckiernan** [comment]
Hi, @PaulScotti, you previously signed up to review for JOSE. Would you please consider contributing a review for this submission? The title is "Neuromatch Academy: a 3-week, online summer school in computational neuroscience". Please let me know if you're available and willing. Thanks!

**Comment by PaulScotti** [comment]
@emckiernan Yes, I am happy to review this!

**Comment by emckiernan** [comment]
> @emckiernan Yes, I am happy to review this!

@PaulScotti: Great, thanks so much! Adding you as a reviewer now...

**Comment by emckiernan** [comment]
@whedon add @PaulScotti as reviewer

**Comment by whedon** [comment]
OK, @PaulScotti is now a reviewer

**Comment by emckiernan** [comment]
Hi @thartbm, we've now got 2 reviewers (yay!). So, I'm going to go ahead and close this issue and start the review process. There's still one pending invitation, but we can always add an additional reviewer later if necessary.

**Comment by emckiernan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/118.
