### ISSUE TITLE
[PRE REVIEW]: EPIDEMIC: Epidemiology Educational Code

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#112]
**Submitting author:** @BrunaPavlack (<a href="http://orcid.org/0000-0002-6807-0916">Bruna Silveira Pavlack</a>)
**Repository:** <a href="https://github.com/americocunhajr/EPIDEMIC" target ="_blank">https://github.com/americocunhajr/EPIDEMIC</a>
**Version:** 1.0.0
**Editor:** @magsol
**Reviewers:** @dalonsoa, @3mmaRand

**Author instructions**

Thanks for submitting your paper to JOSE @BrunaPavlack. **Currently, there isn't an JOSE editor assigned** to your paper.

@BrunaPavlack if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.21 s (127.5 files/s, 26068.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                          22            677           1809           2591
Markdown                         2             71              0            262
TeX                              1              8              0             78
YAML                             2              1              4             20
-------------------------------------------------------------------------------
SUM:                            27            757           1813           2951
-------------------------------------------------------------------------------


Statistical information for the repository 'e37329ad16afc42dde04d0f3' was
gathered on 2021/05/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1101/2020.04.13.20063354 may be a valid DOI for title: SimCOVID: Open-Source Simulation Programs for the COVID-19 Outbreak
- 10.1016/j.amc.2018.06.024 may be a valid DOI for title: Calibration of a SEIR–SEI epidemic model to describe the Zika virus outbreak in Brazil
- 10.1186/1471-2105-13-76 may be a valid DOI for title: EpiFire: An open source C++ library and application for contact network epidemiology
- 10.1063/5.0005204 may be a valid DOI for title: Embedded model discrepancy: a case study of Zika modeling
- 10.4172/2155-6113.1000e107 may be a valid DOI for title: The Role of Computational Epidemiology and Risk Analysis in the Fight Against HIV/AIDS

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #112 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:204:in `block in parse_authors': Author (Amanda Cunha Guyt) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by BrunaPavlack** [comment]
Suggestion from reviewers: Shannon Quinn, Juan Klopper and Erin McKiernan

**Comment by labarba** [comment]
@BrunaPavlack 👋  — Your paper is not compiling because the metadata is nonconforming to the specs. Please check the [example paper](https://openjournals.readthedocs.io/en/jose/submitting.html#example-paper-and-bibliography) and fix.

**Comment by labarba** [comment]
@whedon invite @magsol as editor

**Comment by whedon** [comment]
@magsol has been invited to edit this submission.

**Comment by BrunaPavlack** [comment]
> @BrunaPavlack 👋 — Your paper is not compiling because the metadata is nonconforming to the specs. Please check the [example paper](https://openjournals.readthedocs.io/en/jose/submitting.html#example-paper-and-bibliography) and fix.

Hello! I would like help identifying what the problem is with compiling the paper. I used the site https://whedon.theoj.org/  to view and compiled it just right. Thank you very much in advance!

**Comment by labarba** [comment]
@openjournals/dev — We're seeing compilation errors on this submitted JOSE paper, but when I enter the repo URL and branch in the sandbox at https://whedon.theoj.org it compiles properly. Can you help us?

**Comment by arfon** [comment]
> Author (Amanda Cunha Guyt) is missing affiliation

Please add an affiliation for Amanda Cunha Guyt as per the error above.

**Comment by BrunaPavlack** [comment]
Thanks for the feedback! I've already added the affiliation.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00112/jose.00112/10.21105.jose.00112.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00112/jose.00112/10.21105.jose.00112.pdf) :page_facing_up: :point_left:

**Comment by magsol** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by BrunaPavlack** [comment]
Hello! Suggestion from reviewers: Shannon Quinn, Juan Klopper and Erin McKiernan

**Comment by magsol** [comment]
@BrunaPavlack The reviewers you suggested are excellent open science researchers, but none of them seem to have experience in computational epidemiology. Are you sure you'd like these folks to act as reviewers?

**Comment by BrunaPavlack** [comment]
> @BrunaPavlack The reviewers you suggested are excellent open science researchers, but none of them seem to have experience in computational epidemiology. Are you sure you'd like these folks to act as reviewers?


Helo! I could not identify any with experience in the epidemiological area, feel free to suggest new reviewers.

**Comment by labarba** [comment]
hi @BrunaPavlack 👋 
I just read your paper and I have the following comment: I miss a passage that explains to readers how they might potentially use the software in their teaching and learning context. If you have used it within a course, it helps to describe briefly how it was used. Mostly, though, what we want is to make it easier for another instructor or a self-learner to visualize how they might reuse your artifacts. Have a look at the ["What should my paper contain?"](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain) of our documentation.

**Comment by BrunaPavlack** [comment]
> hi @BrunaPavlack 👋
> I just read your paper and I have the following comment: I miss a passage that explains to readers how they might potentially use the software in their teaching and learning context. If you have used it within a course, it helps to describe briefly how it was used. Mostly, though, what we want is to make it easier for another instructor or a self-learner to visualize how they might reuse your artifacts. Have a look at the ["What should my paper contain?"](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain) of our documentation.

Hi! Thank you so much for the comment! We have already added in the paper the potential use of EPIDEMIC for teaching and learning. We've also added an example of using EPIDEMIC in a course on numerical and computational
methods. We are available for any questions!

**Comment by BrunaPavlack** [comment]
Hi @labarba  ! Thank you so much for the comment! We have already added in the paper the potential use of EPIDEMIC for teaching and learning. We've also added an example of using EPIDEMIC in a course on numerical and computational
methods. We are available for any questions!

**Comment by BrunaPavlack** [comment]
Hi @labarba  ! Thank you so much for the comment! We have already added in the paper the potential use of EPIDEMIC for teaching and learning. We've also added an example of using EPIDEMIC in a course on numerical and computational methods. We are available for any questions!

**Comment by BrunaPavlack** [comment]
Hi! I hope you are all well! Would you like to know how the review of the paper is progressing? Thank you in advance for any information!

**Comment by magsol** [comment]
Hi @BrunaPavlack! I'm so sorry this has been taking awhile, but I've been having a lot of trouble finding reviewers. I've been emailing potential reviewers offline, and so far have contacted 4 and had 4 subsequent declines :( I'm still following up on some additional reviewer leads, and if you have any suggestions for people who could potentially review your submission I'd be happy to hear them!

Otherwise I will certainly update you again next week with whatever progress I have made in finding reviewers.

**Comment by labarba** [comment]
Maybe `@lwjohnst86` could volunteer a review here, as the author of the recently published `r-cubed` paper: https://jose.theoj.org/papers/10.21105/jose.00122

**Comment by magsol** [comment]
Hi @BrunaPavlack! Thanks so much for the additional reviewer suggestions! I've reached out to five more (some you recommended, some others who declined to review recommended) and am hoping to hear back soon! Will update.

**Comment by magsol** [comment]
@whedon assign @dalonsoa as reviewer

**Comment by whedon** [comment]
OK, @dalonsoa is now a reviewer

**Comment by magsol** [comment]
@BrunaPavlack I've found one reviewer, and a possible lead on a second. Will update!

**Comment by magsol** [comment]
@whedon add @3mmaRand as reviewer

**Comment by whedon** [comment]
OK, @3mmaRand is now a reviewer

**Comment by magsol** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/149.
