### ISSUE TITLE
[PRE REVIEW]: OpenQuestion: A survey building and reporting platform written in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#113]
**Submitting author:** @Alcampopiano (<a href="http://orcid.org/0000-0002-3280-4447">Allan Campopiano</a>)
**Repository:** <a href="https://github.com/Alcampopiano/OpenQuestion" target ="_blank">https://github.com/Alcampopiano/OpenQuestion</a>
**Version:** v0.1.0
**Editor:** @labarba
**Reviewers:** @stefania11, @csev

**Author instructions**

Thanks for submitting your paper to JOSE @Alcampopiano. **Currently, there isn't an JOSE editor assigned** to your paper.

@Alcampopiano if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.35 s (398.7 files/s, 26985.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                            57              9              2           3009
Python                          69           1036            737           2476
Markdown                        11            242              0           1000
CSS                              2            161            108            622
HTML                             1              7              0             78
TeX                              1              5              0             51
-------------------------------------------------------------------------------
SUM:                           141           1460            847           7236
-------------------------------------------------------------------------------


Statistical information for the repository '6f937db809ce1bbb18b3494a' was
gathered on 2021/05/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
alcampopiano                    25           321             95            4.56
campopianoa@hcdsb.or           169          6402           2304           95.44

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
alcampopiano                224           69.8          2.3               11.61
campopianoa@hcdsb.or       4100           64.0          6.0                6.44
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/TVCG.2016.2599030 is OK

MISSING DOIs

- 10.1016/j.jbi.2008.08.010 may be a valid DOI for title: Research electronic data capture (REDCap)—a metadata-driven methodology and workflow process for providing translational research informatics support

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00113/jose.00113/10.21105.jose.00113.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00113/jose.00113/10.21105.jose.00113.pdf) :page_facing_up: :point_left:

**Comment by Alcampopiano** [comment]
Hello folks! Here are some potential reviewers:

johnlray
ShahneRodgers
nniiicc

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
hi @stefania11 👋 — You signed up to review for JOSE (The Journal of Open Source Education) a while back. Do you think you could help us with this submission?
**OpenQuestion: A survey building and reporting platform written in Python**
Target repository: https://github.com/Alcampopiano/OpenQuestion
Paper: https://github.com/openjournals/jose-papers/blob/jose.00113/jose.00113/10.21105.jose.00113.pdf

It’s a Python tool to build surveys and issue reports. It uses Anvil, Python, and JSON.

Let me know if you're interested in contributing a review for this. Thank you!

**Comment by stefania11** [comment]
Sure happy to help!

**Comment by labarba** [comment]
@whedon assign @stefania11 as reviewer

**Comment by whedon** [comment]
OK, @stefania11 is now a reviewer

**Comment by labarba** [comment]
Thank you, Stefania! After I add a second reviewer we can start the review issue, which will include a checklist to guide the review. In the meantime, you can of course look at the contents of the submission, and ask me any questions you may have.

**Comment by stefania11** [comment]
Sounds good!

**Comment by labarba** [comment]
@whedon add @csev as reviewer

**Comment by whedon** [comment]
OK, @csev is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/123.
