### ISSUE TITLE
[PRE REVIEW]: Teaching Python for Data Science: Collaborative development of a modular & interactive curriculum

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#119]
**Submitting author:** @bnwolford (<a href="http://orcid.org/0000-0003-3153-1552">Brooke N. Wolford</a>)
**Repository:** <a href="https://github.com/GWC-DCMB/curriculum-notebooks/" target ="_blank">https://github.com/GWC-DCMB/curriculum-notebooks/</a>
**Version:** v0.1.0
**Editor:** @JasonJWilliamsNY
**Reviewers:** @lechten, @ThomasA
**Managing EiC:** Lorena Barba

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". 

## Status

[![status](https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0/status.svg)](https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0"><img src="https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0/status.svg)](https://jose.theoj.org/papers/bfcfe417b85c7f0b5bf5b9885110c6d0)
```

**Author instructions**

Thanks for submitting your paper to JOSE @bnwolford. **Currently, there isn't an JOSE editor assigned** to your paper.

@bnwolford if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (1108.2 files/s, 466616.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook               109              0          46159           2947
XML                              1              0            129           1790
Markdown                         6            142              0            719
TeX                              1             19              0            224
SVG                              1              0              1            212
YAML                             4             10              4            194
Python                           2             12             10             53
Bourne Shell                     1              0              0              8
-------------------------------------------------------------------------------
SUM:                           125            183          46303           6147
-------------------------------------------------------------------------------


Statistical information for the repository '825ba90356fcc8114529f5f1' was
gathered on 2021/06/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kelly Sovacool                   1            75              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kelly Sovacool               75          100.0          0.0                5.33
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00119/jose.00119/10.21105.jose.00119.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00119/jose.00119/10.21105.jose.00119.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1371/journal.pcbi.1005134 is OK
- 10.1145/268084.268127 is OK
- 10.1016/j.infsof.2009.02.001 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1371/journal.pcbi.1008090 is OK
- 10.21105/joss.03021 is OK
- 10.12688/f1000research.3-62.v2 is OK
- 10.1101/2021.06.15.448091 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
@JasonJWilliamsNY has been invited to edit this submission.

**Comment by labarba** [comment]
@whedon assign @JasonJWilliamsNY as editor

**Comment by whedon** [comment]
OK, the editor is @JasonJWilliamsNY

**Comment by JasonJWilliamsNY** [comment]
@whedon add @lechten as reviewer

**Comment by JasonJWilliamsNY** [comment]
Thanks @lechten for agreeing to review - once we find more reviewer @bnwolford we will begin the review.

**Comment by labarba** [comment]
@whedon assign @lechten as reviewer

**Comment by whedon** [comment]
OK, @lechten is now a reviewer

**Comment by lechten** [comment]
Just to be sure: I also wait for the second reviewer, correct?

**Comment by ThomasA** [comment]
I can offer to review. I have taught Python for Scientific Computing at Aalborg University for several years.

**Comment by labarba** [comment]
Thank you, @ThomasA, for volunteering to review! 

@JasonJWilliamsNY — that gets you to two reviewers, and moves this to review. Allow me to take those steps for you tonight.

**Comment by labarba** [comment]
@whedon add @ThomasA as reviewer

**Comment by whedon** [comment]
OK, @ThomasA is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/138.
