### ISSUE TITLE
[PRE REVIEW]: The Riffomonas Reproducible Research Tutorial Series

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#12]
**Submitting author:** @pschloss (<a href="http://orcid.org/0000-0002-6935-4275">Patrick D Schloss</a>)
**Repository:** <a href="https://github.com/riffomonas/reproducible_research" target ="_blank">https://github.com/riffomonas/reproducible_research</a>
**Version:** v1.0.0
**Editor:** @tracykteal
**Reviewers:** @jhollist 

**Author instructions**

Thanks for submitting your paper to JOSE @pschloss. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pschloss if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #12 with the following error: 

 Can't find any papers to compile :-(

**Comment by pschloss** [comment]
Among the people listed as possible reviewers, I might suggest @jhollist or @K8hertweck

**Comment by pschloss** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pschloss** [comment]
Sorry, I'm not sure why the PDF couldn't be built - let me know if I can help debug what went wrong.

**Comment by kyleniemeyer** [comment]
Hi @pschloss, we're still getting JOSE up and running, so getting that fixed may take a little time.

**Comment by jhollist** [comment]
When JOSE is ready for reviewers, would be happy to review this one!

**Comment by labarba** [comment]
@whedon assign @tracykteal as editor

**Comment by whedon** [comment]
OK, the editor is @tracykteal

**Comment by labarba** [comment]
Thank you for agreeing to review, @jhollist ! This gets JOSE started for real.

**Comment by labarba** [comment]
@whedon assign @jhollist  as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jhollist

**Comment by jhollist** [comment]
All, sorry for the delay on this.  On my list for digging into the review this week.

**Comment by labarba** [comment]
Good to hear back from you. Have a look at our discussion over at #11, where I'm giving the author more direction about what we want to see in JOSE papers. This, after we had a telecon with the editorial board. 

I will start this review now, which will create another issue with the review checklist for you.

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/13. Feel free to close this issue now!
