### ISSUE TITLE
[PRE REVIEW]: Virtual training on virtual environments: an online open-source introduction to conda

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#126]
**Submitting author:** @marisalim (<a href="http://orcid.org/0000-0003-2097-8818">Marisa Lim</a>)
**Repository:** <a href="https://github.com/nih-cfde/training-and-engagement" target ="_blank">https://github.com/nih-cfde/training-and-engagement</a>
**Version:** n/a
**Editor:** @allisonhorst
**Reviewers:** @colbrydi, @shanamatthews
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e/status.svg)](https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e"><img src="https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e/status.svg)](https://jose.theoj.org/papers/17eef7276bb7ca1229556b8c0f44014e)
```

**Author instructions**

Thanks for submitting your paper to JOSE @marisalim. **Currently, there isn't an JOSE editor assigned** to your paper.

@marisalim if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by allisonhorst** [comment]
Hi @shanamatthews, thank you for signing up to review for the Journal of Open Source Education! Would you like to contribute a review for this submission, "Virtual training on virtual environments: an online open-source introduction to conda"? Please let me know if you're available and willing to review this submission. Thank you!

**Comment by colbrydi** [comment]
Hi @allisonhorst, I should be able to do this review.  Please note that I am new to this git centered review process so it may take me some time to figure out.

**Comment by allisonhorst** [comment]
Thank you @colbrydi, we really appreciate your willingness to review for JOSE! No worries at all about learning the review process. I am new to it, too, and here to help (with the support of the JOSE editorial board). I'll go ahead and add you as a reviewer for this paper and kick off the review process. Please reach out any time with questions, and I'll follow up with some information within the next two days.

**Comment by allisonhorst** [comment]
@whedon assign @colbrydi as reviewer

**Comment by whedon** [comment]
OK, @colbrydi is now a reviewer

**Comment by shanamatthews** [comment]
> Hi @shanamatthews, thank you for signing up to review for the Journal of Open Source Education! Would you like to contribute a review for this submission, "Virtual training on virtual environments: an online open-source introduction to conda"? Please let me know if you're available and willing to review this submission. Thank you!

Hi @allisonhorst! I’m happy to review as well.

**Comment by allisonhorst** [comment]
@whedon add @shanamatthews as reviewer

**Comment by whedon** [comment]
OK, @shanamatthews is now a reviewer

**Comment by allisonhorst** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/130.
