### ISSUE TITLE
[PRE REVIEW]: Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#128]
**Submitting author:** @ethanwhite (<a href="http://orcid.org/0000-0001-6728-7745">Ethan P. White</a>)
**Repository:** <a href="https://github.com/datacarpentry/semester-biology/" target ="_blank">https://github.com/datacarpentry/semester-biology/</a>
**Version:** v4.1.0
**Editor:** @ShanEllis
**Reviewers:** @smwindecker, @catherinehulshof
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f/status.svg)](https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f"><img src="https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f/status.svg)](https://jose.theoj.org/papers/30d2d92728226af1e99f559f2f22b38f)
```

**Author instructions**

Thanks for submitting your paper to JOSE @ethanwhite. **Currently, there isn't an JOSE editor assigned** to your paper.

@ethanwhite if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by ShanEllis** [comment]
Thanks @ethanwhite! Looks ready to start the review process.

Hi @jsta and @jhollist, I have you both as interested reviewers for JOSE, and it appears you are each a good fit for this submission. Would you like to contribute a review for this submission? The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". Please let me know if you're available and willing. Thanks!

**Comment by ShanEllis** [comment]
Hi @pschloss, given your interest in reviewing for JOSE (and previous review - thank you!), I wanted to reach out to see if you'd be interested in contributing a review for this submission? The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". Please let me know if you're available and willing in the next couple of days. Thanks!

**Comment by ShanEllis** [comment]
Hi @K8hertweck, it looks like you've signed up previously to review for JOSE, and I think we have a recent submission that's a great fit for you. I wanted to reach out to see if you'd be interested in contributing a review for this submission? The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". Please let me know if you're available and willing in the next couple of days. Thanks!

**Comment by jhollist** [comment]
@ShanEllis I am so sorry for not getting back to you on this sooner.  No excuse...  Just forgot.

Unfortunately, I am going to have to pass at this time.  I'd really love to review this, but I am swamped.  Keep me in mind for future submissions.

**Comment by pschloss** [comment]
Hi - thanks for reaching out. Unfortunately, I've been pretty swamped with
other reviews and projects that I need to tend to.

Pat

**Comment by ShanEllis** [comment]
> Unfortunately, I am going to have to pass at this time. I'd really love to review this, but I am swamped. Keep me in mind for future submissions.

I have been there, @jhollist. Thanks for the reply, and good luck with all that's on your plate.

**Comment by ShanEllis** [comment]
> Hi - thanks for reaching out. Unfortunately, I've been pretty swamped with
other reviews and projects that I need to tend to.

Totally understand, @pschloss! Thanks for the quick reply.

**Comment by ShanEllis** [comment]
Hi @fmichonneau! I have you down as an interested reviewer for JOSE, and I think we have a recent submission that's a really good fit for you. I wanted to reach out to see if you'd be interested in contributing a review for this submission? The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". Please let me know if you're available and willing in the next couple of days. Thanks!

**Comment by fmichonneau** [comment]
Hi @ShanEllis Thanks for the invitation but I think my affiliation with The Carpentries creates a conflict of interest for this submission.

**Comment by ShanEllis** [comment]
Hi @gvdr! I have you down as an interested reviewer for JOSE, and I think we have a recent submission that's a good fit for you. I wanted to reach out to see if you'd be interested in contributing a review for this submission? The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". Please let me know if you're available and willing in the next couple of days. Thanks!

**Comment by ShanEllis** [comment]
Hi @karthik! I'm sure you're super busy (which is why I've held off thus far on bugging you for this), but I've been struggling to pin down reviewers. **Any chance you have time for a JOSE review?** The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". I believe you've reviewed for JOSE before, so you know that the papers are not very long and the review process is open and happens entirely on GitHub. Let me know if you'll have time to complete this review!

**Comment by labarba** [comment]
I noticed on the paper it says these materials have been used in a number of university and college courses. Why not find someone among the instructors of those courses to act as reviewers? They would already have read the material and had direct experience teaching with them, perhaps finding areas that need improvement. I don't see that there would be any reason to think adopting the materials raises conflict-of-issue concerns, if the adopter did not collaborate with the original authors... What do you think, @ethanwhite ?

**Comment by ShanEllis** [comment]
That's a good idea, @labarba. I wasn't sure if there was a COI issue there, but if you and @ethanwhite think that's a  possibility, I'll go ahead with that!

Also, we do have one reviewer on board now! I'll add @smwindecker to the official review issue once we find our second (unless you say otherwise, @labarba!)

**Comment by karthik** [comment]
> Hi @karthik! I'm sure you're super busy (which is why I've held off thus far on bugging you for this), but I've been struggling to pin down reviewers. **Any chance you have time for a JOSE review?** The title is "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples". I believe you've reviewed for JOSE before, so you know that the papers are not very long and the review process is open and happens entirely on GitHub. Let me know if you'll have time to complete this review!  

Thanks for thinking of me. I'm out on family leave at the moment and am not taking on new reviews till the end of the year. Good luck with your reviewer search.

**Comment by labarba** [comment]
> I'll add @smwindecker to the official review issue once we find our second (unless you say otherwise/to start it before then, @labarba!)

Yes, you add the reviewers here, in the Pre-review issue. Go ahead and run `@whedon assign <user> as reviewer` here for the first reviewer, then `@whedon add <user> as reviewer` for the second, then `@whedon start review` 😄

**Comment by ethanwhite** [comment]
I agree that folks who have used this material in their courses could be good reviewers. Of the courses on that list the only folks I'm aware of who have conflicts of interest are the University of Florida folks (institutional conflicts + one of them is an author on the paper).

One person on that list that comes to mind as a possibility is catherinehulshof.

**Comment by ShanEllis** [comment]
@whedon assign @smwindecker as reviewer

**Comment by whedon** [comment]
OK, @smwindecker is now a reviewer

**Comment by ShanEllis** [comment]
> I agree that folks who have used this material in their courses could be good reviewers. Of the courses on that list the only folks I'm aware of who have conflicts of interest are the University of Florida folks (institutional conflicts + one of them is an author on the paper).
> 
> One person on that list that comes to mind as a possibility is catherinehulshof.

Excellent. Thank you, @ethanwhite. I will reach out to to this end, keeping the exceptions you noted in mind. I appreciate it!

**Comment by ShanEllis** [comment]
Hi @catherinehulshof! Reaching out to see if you're interested and able to review a submission to JOSE (Journal of Open Source Education) titled "Data Carpentry for Biologists: A semester long Data Carpentry course using ecological and other biological examples".  I believe you are familiar with these materials, making you a good fit for the review and hopefully making the review process shorter for you. The review process for JOSE is open and happens on GitHub. If you're interested and able, please let me know!

**Comment by catherinehulshof** [comment]
Dear Shannon,

I would be interested and am familiar with the materials after learning
more about the review process. What are the review criteria/format, etc?

Cheers,

Catherine

______________________________________________
Catherine M. Hulshof, PhD (she/her: why I use pronouns
<https://www.mypronouns.org/what-and-why>)
Environmental Data Science
Department of Biology
Virginia Commonwealth University
Richmond, VA, 23284
https://www.biodiversityresearchlab.com

**Comment by catherinehulshof** [comment]
Hi Shannon,

I'd be happy to provide a review within the next several weeks.

Catherine

______________________________________________
Catherine M. Hulshof, PhD (she/her: why I use pronouns
<https://www.mypronouns.org/what-and-why>)
Environmental Data Science
Department of Biology
Virginia Commonwealth University
Richmond, VA, 23284
https://www.biodiversityresearchlab.com

**Comment by ShanEllis** [comment]
@whedon add @catherinehulshof as reviewer

**Comment by whedon** [comment]
OK, @catherinehulshof is now a reviewer

**Comment by ShanEllis** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/139.
