### ISSUE TITLE
[PRE REVIEW]: A virtual training module for introducing the use of Amazon Web Services

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#132]
**Submitting author:** @abhijna (<a href="http://orcid.org/0000-0002-5861-3737">Abhijna Parigi</a>)
**Repository:** <a href="https://github.com/nih-cfde/training-and-engagement" target ="_blank">https://github.com/nih-cfde/training-and-engagement</a>
**Version:** v1.0.0
**Editor:** @willingc
**Reviewers:** @giuliaguidi, @manics
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d/status.svg)](https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d"><img src="https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d/status.svg)](https://jose.theoj.org/papers/39c22a9db13af767ca070e1268a71e7d)
```

**Author instructions**

Thanks for submitting your paper to JOSE @abhijna. **Currently, there isn't an JOSE editor assigned** to your paper.

@abhijna if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #132 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (741.3 files/s, 104956.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                       143           4853              0           9750
CSS                              4            854             71           6424
JavaScript                       4             31             52           1141
HTML                             5              1             14            375
YAML                            11             35             69            199
R                                2             72             51            157
Python                           1             13              5             30
reStructuredText                 1              5              7              3
-------------------------------------------------------------------------------
SUM:                           171           5864            269          18079
-------------------------------------------------------------------------------


Statistical information for the repository 'bee59e9001e98f82eb19c485' was
gathered on 2021/09/10.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Amanda Charbonneau              10         20107          20108           96.85
Jeremy Walter                   12             8              8            0.04
Marisa Lim                       2            49              1            0.12
Saranya Canchi                   4          1234              0            2.97
abhijna                          1             5              4            0.02

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marisa Lim                   48           98.0          9.8               10.42
Saranya Canchi             1224           99.2          8.4                4.25
```

**Comment by jgorzalski** [comment]
@whedon generate pdf from branch AWS_Jose_Paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch AWS_Jose_Paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00132/jose.00132/10.21105.jose.00132.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00132/jose.00132/10.21105.jose.00132.pdf) :page_facing_up: :point_left:

**Comment by abhijna** [comment]
@whedon get pdf from branch AWS_JOSE_Paper

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by abhijna** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by abhijna** [comment]
Suggested reviewers:  Rahul Kulkarni, Jason Williams, Jens Lechtenbörger, Luke Johnston

**Comment by erahulkulkarni** [comment]
Good Day,



Sorry, but I have very little experience in the use of Amazon Web Services.


So in one way, the readability of the documentation should help me get
started with Amazon Web Services.


But since I have little experience I would not be able to suggest other /
better ways of usage.


Please let me know if it would still be okay if I agree to review?


Thanks and Regards,
*Rahul Kulkarni*

**Comment by jgorzalski** [comment]
Hello @abhijna! Sorry for the slow reply, we've been a little backlogged at JOSE due to the pandemic and are trying to keep up with everything. I've read through your paper and I need a little clarification before we move this forward. At JOSE we are looking to publish modules and course lessons with their own objectives and activities that could be taught over three to five weeks of a semester. I'm getting the sense from this paper that the information and tools presented here amount to more of a two hour training session or a one time in class activity. Am I understanding that correctly? Thank you for the clarification.

**Comment by abhijna** [comment]
Hello @jgorzalski, that is correct. We offer a 2-hour, one-time virtual lesson that provides a hands-on introduction to configuring, launching, and connecting to an AWS instance. The lesson is intended for novice users who wish to learn about AWS (and cloud computing) without the commitment of a semester-long course. Our workshops are widely successful and attract diverse audiences (e.g. professors, students, and non-academic professionals). Please let me know if you need further clarification.

**Comment by abhijna** [comment]
@erahulkulkarni, thank you for your response. Anyone who has knowledge of bioinformatics, computational biology, data analysis, remote computing, and/or curriculum development might find our manuscript interesting and be a valuable reviewer.

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by labarba** [comment]
@whedon generate pdf from branch AWS_JOSE_Paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch AWS_JOSE_Paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch AWS_Jose_Paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
@willingc has been invited to edit this submission.

**Comment by labarba** [comment]
@giuliaguidi 👋  — We received this submission to The Journal of Open Source Software, JOSE: **A virtual training module for introducing the use of Amazon Web Services**. Could you help us out with a review?
JOSE is a fully volunteer-led, open journal for publishing open source software for educational uses and open learning modules or tutorials. Have a look at our [docs](https://openjournals.readthedocs.io/en/jose/).

**Comment by giuliaguidi** [comment]
Hi,

I would be happy to help, please let me know how to proceed.

Best,
Giulia Guidi

**Comment by willingc** [comment]
Awesome @giuliaguidi. I'll be in touch with more details after my work day. Thanks!

**Comment by willingc** [comment]
@whedon assign @giuliaguidi as reviewer

**Comment by whedon** [comment]
OK, @giuliaguidi is now a reviewer

**Comment by willingc** [comment]
Hi @giuliaguidi, The best place to begin learning about the review process is to start in our [reviewer guide](https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html). Please feel free to reach out with questions. Thanks. :sunny:

**Comment by giuliaguidi** [comment]
Great, I'll have a look later this week. Is there a deadline for the review?

Best,
Giulia

**Comment by abhijna** [comment]
Hello @willingc and @giuliaguidi, are there any updates on the review status of this paper? Please let me know if you need anything.

**Comment by giuliaguidi** [comment]
I'll complete it by the end of the next week.

Best,
Giulia

**Comment by labarba** [comment]
Hi everybody — the handling editor, @willingc, will need to add one more reviewer here before running `@whedon start review`, which will open a new issue thread that will show a review checklist for each reviewer (and close this thread). 

@giuliaguidi : You can start reviewing the materials, but the conversation about revisions, etc., will happen in the Review thread.

**Comment by giuliaguidi** [comment]
@labarba sounds good, I mostly completed my review—I'll wait for @willingc to start the review thread to copy/paste it over there.

**Comment by willingc** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by willingc** [comment]
@betatim @choldgraf @sgibson91 Do any of you have time to do a review of this paper? Requires some knowledge of AWS. I would really appreciate it. Thanks.

@abhijna I'm back now so this should get back on track. Sorry for the delay.

**Comment by sgibson91** [comment]
I wonder if @damianavila has the time and expertise for this? (I haven't used AWS... yet)

**Comment by abhijna** [comment]
Hello @willingc, just checking in on the review status of this paper. Are there any updates?

**Comment by choldgraf** [comment]
Hey all - just realized I didn't reply to this. I don't believe I am the right person to review a paper like this, and sadly am swamped for time right now anyway. Have you considered posting in the JupyterHub Team Compass? I believe that @manics might have some experience with AWS.

**Comment by manics** [comment]
I might be able to help... Can someone give me a TLDR of what to do/where to start before I commit? 😀

**Comment by labarba** [comment]
hi @manics — thank you! Have a look at the documentation here: https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html

If you agree to review, we'll start a new issue, which will have a review checklist at the top for each of the reviewers. You can tick off items there, and open issues on the target repository for things you would like to see improved, and we have a conversation in the review issue until all are happy. Sound good?

**Comment by manics** [comment]
@labarba Thanks, I've read the link and I'm happy to review the submission.

**Comment by labarba** [comment]
@whedon add @manics as reviewer

**Comment by whedon** [comment]
OK, @manics is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/167.
