### ISSUE TITLE
[PRE REVIEW]: Computational models of human social behavior and neuroscience: An open educational course and Jupyter Book to advance computational training

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#136]
**Submitting author:** @shawnrhoads (<a href="http://orcid.org/0000-0003-1350-9458">Shawn A. Rhoads</a>)
**Repository:** <a href="https://github.com/shawnrhoads/gu-psyc-347" target ="_blank">https://github.com/shawnrhoads/gu-psyc-347</a>
**Version:** v1.0.0
**Editor:** @emckiernan
**Reviewers:** @arokem, @djmannion
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be/status.svg)](https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be"><img src="https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be/status.svg)](https://jose.theoj.org/papers/62fca31989cb19be1eb93970ac7554be)
```

**Author instructions**

Thanks for submitting your paper to JOSE @shawnrhoads. **Currently, there isn't an JOSE editor assigned** to your paper.

@shawnrhoads if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1668

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1111/tops.12404 is OK
- 10.7554/eLife.49547 is OK
- 10.1093/scan/nsaa040 is OK
- 10.1093/scan/nsaa089 is OK
- 10.1016/j.tics.2017.03.011 is OK
- 10.1016/j.neuron.2021.04.001 is OK
- 10.1016/j.tics.2021.03.018 is OK
- 10.1371/journal.pone.0244974 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.5281/zenodo.3509134 is OK
- 10.1073/pnas.1603198113 is OK
- 10.3758/s13428-018-01193-y is OK
- 10.5281/zenodo.2561065 is OK
- 10.1016/j.neuron.2013.10.038 is OK
- 10.1002/9781119159193.ch17 is OK
- 10.1186/s13742-016-0121-x is OK
- 10.5281/zenodo.3909717 is OK

MISSING DOIs

- 10.31234/osf.io/rybh9 may be a valid DOI for title: How Computational Modeling Can Force Theory Building in Psychological Science

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.24 s (248.8 files/s, 195172.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3            727           1282           5141
Jupyter Notebook                33              0          26552           4478
JavaScript                       2            655            503           3247
XML                              2              0              0           1651
Markdown                        11            234              0            820
TeX                              2             37              0            718
YAML                             5             14             26            158
HTML                             1              7              4             29
-------------------------------------------------------------------------------
SUM:                            59           1674          28367          16242
-------------------------------------------------------------------------------


Statistical information for the repository 'd95ab77e28ef3135531bffd4' was
gathered on 2021/09/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Shawn Rhoads                     7         26446          14891          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Shawn Rhoads              11555           43.7          0.0               15.27
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00136/jose.00136/10.21105.jose.00136.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00136/jose.00136/10.21105.jose.00136.pdf) :page_facing_up: :point_left:

**Comment by shawnrhoads** [comment]
Thank you! I have added the DOI [referenced above](https://github.com/openjournals/jose-reviews/issues/136#issuecomment-931490754) with [this PR](https://github.com/shawnrhoads/gu-psyc-347/pull/179)

@whedon generate pdf

**Comment by shawnrhoads** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00136/jose.00136/10.21105.jose.00136.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00136/jose.00136/10.21105.jose.00136.pdf) :page_facing_up: :point_left:

**Comment by shawnrhoads** [comment]
Suggested reviewers listed in [Google sheet](https://docs.google.com/spreadsheets/d/1gQ_KZnJx-lyJwiuHBp9rE6b2ugMkJZzigvt4QLQHCH8/edit#gid=0):
- [Tom Donoghue](https://github.com/TomDonoghue)
- [Ariel Rokem](https://github.com/arokem)

Other potential reviewers not listed in Google sheet:
- [Lei Zhang](https://github.com/lei-zhang)
- [Jo Cutler](https://github.com/jocutler)
- [Junaid Merchant](https://github.com/JunaidMerchant)
- [Jin Hyun Cheong](https://github.com/jcheong0428)

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by emckiernan** [comment]
@whedon assign @emckiernan as editor

**Comment by arokem** [comment]
@emckiernan : apologies for the slowness. I can take this.

**Comment by whedon** [comment]
OK, @arokem is now a reviewer
