### ISSUE TITLE
[REVIEW]: Interactive Bin Packing: A Java Application for Learning Constructive Heuristics for Combinatorial Optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#140]
**Submitting author:** @cicirello (<a href="http://orcid.org/0000-0003-1072-8559">Vincent A Cicirello</a>)
**Repository:** <a href="https://github.com/cicirello/InteractiveBinPacking" target ="_blank">https://github.com/cicirello/InteractiveBinPacking</a>
**Version:** v3.1.1
**Editor:** @labarba
**Reviewers:** @turketwh
**Archive:** <a href="https://doi.org/10.5281/zenodo.6402123" target="_blank">10.5281/zenodo.6402123</a>

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". 

## Status

[![status](https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130/status.svg)](https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130"><img src="https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130/status.svg)](https://jose.theoj.org/papers/c994f4aab2b351e9c2fee12113bd2130)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cicirello/InteractiveBinPacking" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@adeepak7 & @turketwh, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @labarba know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/joss/blob/jose/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cicirello/InteractiveBinPacking">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v3.1.1
- [ ] **Authorship:** Has the submitting author (@cicirello) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [ ] **Example usage:** Do the authors include examples of how to use the software?
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/joss/blob/jose/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cicirello/InteractiveBinPacking">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v3.1.1
- [x] **Authorship:** Has the submitting author (@cicirello) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @adeepak7, @turketwh it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 976

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICPP.1999.797428 is OK
- 10.1007/s11276-005-5266-y is OK
- 10.1145/1508865.1508951 is OK
- 10.1145/1047344.1047409 is OK

MISSING DOIs

- 10.1007/springerreference_5277 may be a valid DOI for title: Bin packing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (308.7 files/s, 66797.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            20            526           1034           4410
TeX                              3            160            143            557
HTML                             4            106              0            556
Markdown                         5             96              0            425
Maven                            1             17              0            313
YAML                             5             45             46            185
JSON                             1              0              0             24
TOML                             1              2              6              3
-------------------------------------------------------------------------------
SUM:                            40            952           1229           6473
-------------------------------------------------------------------------------


Statistical information for the repository '8d8fc100a6067187e3fa8e32' was
gathered on 2021/10/05.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vincent A. Cicirello            53          3582            713           58.06
Vincent Cicirello                3          3102              1           41.94

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent A. Cicirello       5970          166.7          0.4               17.32
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00140/jose.00140/10.21105.jose.00140.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00140/jose.00140/10.21105.jose.00140.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@adeepak7, @turketwh — Thank you for agreeing to review for JOSE! This is where the action happens: work your way through the review checklist, feel free to ask questions or post comments here, and also open issues in the submission repository as needed. If you do, be sure to include a link to this Review issue, so a cross-link will be created.
Godspeed! 🚀

**Comment by labarba** [comment]
Hi  @adeepak7, @turketwh — do you have any questions about how the JOSE review process works? Feel free to ask me here. 

@adeepak7 — I see you've not gotten a start yet. If you could pop in here and check off the first few items in your checklist, that'll tell me you're still with us on this! 🙏

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by labarba** [comment]
@adeepak7 — Feel free to ask me any questions right here!

And by the way `@whedon` is our editorial bot, and only knows to reply to certain commands 😄

**Comment by labarba** [comment]
@adeepak7 Do you have any question about how to do this review? I'll be happy to help, just let me know!

**Comment by labarba** [comment]
@turketwh How is it going with your review? You should feel free to open issues in the target repository with any questions for the author (linking this issue thread for reference).

**Comment by turketwh** [comment]
> @turketwh How is it going with your review? You should feel free to open issues in the target repository with any questions for the author (linking this issue thread for reference).

Making progress (has been slow, but picking up now) - thanks for the note @labarba

**Comment by labarba** [comment]
I just pinged @adeepak7 [via Twitter](https://twitter.com/LorenaABarba/status/1468961382993301507), in case his GitHub notifications are not going through!

**Comment by cicirello** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by cicirello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICPP.1999.797428 is OK
- 10.1007/s11276-005-5266-y is OK
- 10.1145/1508865.1508951 is OK
- 10.1145/1047344.1047409 is OK
- 10.1145/3017680.3017762 is OK
- 10.1145/3017680.3017728 is OK
- 10.1145/3159450.3159602 is OK
- 10.1145/3287324.3287480 is OK
- 10.1145/3017680.3017793 is OK

MISSING DOIs

- 10.1007/springerreference_5277 may be a valid DOI for title: Bin packing

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00140/jose.00140/10.21105.jose.00140.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00140/jose.00140/10.21105.jose.00140.pdf) :page_facing_up: :point_left:

**Comment by turketwh** [comment]
@labarba @cicirello I have (effectively) finished my review of this JOSE submission.  I have left the *Version* box under the *General checks* criteria unchecked, as I believe the version in the repository is 3.1.0, while it was originally submitted as version 3.0 (as indicated at the top of this review issue).  

I asked the author to address three concerns during the review process, impacting the documentation around installation and support,  the Java API documentation, and the *Statement of need* in the publication itself.  I am satisfied with the author's addressing of each concern.  

I am in favor of *accepting* the submission. 

In my opinion, I believe the software, embedded tutorial, example assignments , and accompanying manuscript make a valuable contribution as an open-source educational tool. Bin packing, as an example of a NP-hard optimization problem, and the idea of heuristics appear in multiple computer science and mathematics courses, suggesting broad applicability.  From using the software, I would argue that the number of heuristics covered and the range of bin packing problems that can be initialized allow for repeated, non-trivial student learning experiences and the example assignments provide a template for how to curate such experiences.  From reviewing the code, the software itself appears cleanly written and well tested, and, in my opinion, is in a state that facilitates extension by others if desired.  The software provides capabilities that go beyond other bin packing tutorials that I can find available and it incorporates various pedagogical best practices.

**Comment by cicirello** [comment]
@turketwh thank you for your feedback during the review process. It was valuable in improving the paper and documentation, etc.

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by labarba** [comment]
Thank you for the detailed feedback, @turketwh — most appreciated! 🙏

**Comment by labarba** [comment]
@adeepak7 — You agreed to review a submission for The Journal of Open Source Education some time ago. We now have a returned full review, and would like to move this forward. Are you able to provide your review in a short span of time?

**Comment by labarba** [comment]
I have now sent the first reviewer an email asking for an update.

**Comment by labarba** [comment]
@whedon remove @adeepak7 as reviewer

**Comment by whedon** [comment]
OK, @adeepak7 is no longer a reviewer

**Comment by labarba** [comment]
hi folks, I received email from `@adeepak7` saying personal difficulties made it impossible to complete the review. We are now minus a reviewer. Thanks for your patience.

**Comment by cicirello** [comment]
@labarba thanks for the update

**Comment by labarba** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by labarba** [comment]
Oops. I forgot the final steps. @cicirello – could you:

- make a tagged release on the repo, and post the version number here?
- make an archive of the submission on Zenodo (or an equivalent service) and post the archive DOI here?

**Comment by cicirello** [comment]
@labarba Great. I'll create the release and archive with Zenodo tomorrow morning. I'll comment again after I do.

**Comment by cicirello** [comment]
@labarba the version number is v3.1.1 and the Zenodo DOI is https://doi.org/10.5281/zenodo.6402123

**Comment by labarba** [comment]
@whedon set v3.1.1 as version

**Comment by whedon** [comment]
OK. v3.1.1 is the version.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.6402123 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.6402123" target="_blank">10.5281/zenodo.6402123</a> is the archive.

**Comment by labarba** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICPP.1999.797428 is OK
- 10.1007/s11276-005-5266-y is OK
- 10.1145/1508865.1508951 is OK
- 10.1145/1047344.1047409 is OK
- 10.1145/3017680.3017762 is OK
- 10.1145/3017680.3017728 is OK
- 10.1145/3159450.3159602 is OK
- 10.1145/3287324.3287480 is OK
- 10.1145/3017680.3017793 is OK

MISSING DOIs

- 10.1007/springerreference_5277 may be a valid DOI for title: Bin packing

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@cicirello – Please give us your approval of the proof, and we will proceed to publication

**Comment by cicirello** [comment]
@labarba the proof looks good.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by labarba** [comment]
Congratulations, @cicirello, your JOSE article is published! 🚀 

Huge thanks to the reviewer: @turketwh — we really appreciate your contribution to this adventure in publishing 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00140/status.svg)](https://doi.org/10.21105/jose.00140)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00140">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00140/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00140/status.svg
   :target: https://doi.org/10.21105/jose.00140
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00140/status.svg)](https://doi.org/10.21105/jose.00140)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-jose

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
