### ISSUE TITLE
[PRE REVIEW]: PCP Notebooks: A Preparation Course for Python with a Focus on Signal Processing

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#147]
**Submitting author:** @sebastianrosenzweig (<a href="http://orcid.org/0000-0003-4964-9217">Sebastian Rosenzweig</a>)
**Repository:** <a href="https://github.com/meinardmueller/PCP" target ="_blank">https://github.com/meinardmueller/PCP</a>
**Version:** v1.0.3
**Editor:** @moorepants
**Reviewers:** @boisgera , @alfredocarella
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359/status.svg)](https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359"><img src="https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359/status.svg)](https://jose.theoj.org/papers/281cddae8d4b2eef936a1d99484f8359)
```

**Author instructions**

Thanks for submitting your paper to JOSE @sebastianrosenzweig. **Currently, there isn't an JOSE editor assigned** to your paper.

@sebastianrosenzweig if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (325.2 files/s, 140201.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                11              0           7891           1251
Python                          12            456            586            952
Markdown                         2             19              0             33
YAML                             1              2              1             17
-------------------------------------------------------------------------------
SUM:                            26            477           8478           2253
-------------------------------------------------------------------------------


Statistical information for the repository '711739ccad4d94304e526ad0' was
gathered on 2021/10/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Meinard Müller                   6          1637              9           73.48
Peter Meier                      1             2              2            0.18
sebastianrosenzweig              3           478            112           26.34

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Meinard Müller             1520           92.9          0.0                7.76
Peter Meier                   2          100.0         10.8                0.00
sebastianrosenzweig         472           98.7          0.6               13.56
```

**Comment by moorepants** [comment]
I can handle this one. Thanks.

@sebastianrosenzweig Can you suggest some reviewers?

**Comment by labarba** [comment]
@whedon assign @moorepants as editor

**Comment by alfredocarella** [comment]
I will be happy to review this module. Same situation here, my next couple of weeks are busy, but I will have some time later.

**Comment by alfredocarella** [comment]
@moorepants I forgot to tag you on my reply, sorry about that. I will gladly review this work.

**Comment by moorepants** [comment]
@boisgera and @alfredocarella, thank you both for volunteering to review this submission. The timeline works for us, so we can plan to have the initial reviews by November 26th. Let me know if that doesn't work. Please have a look at the JOSE reviewing guide: https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html to get an introduction for reviewing here or to refresh your memory if you have already reviewed with us.

I will add you all as reviewers and new issue will be opened where the review will occur.

Let me know if you have any questions.

**Comment by moorepants** [comment]
@whedon add @boisgera  as reviewer

**Comment by whedon** [comment]
OK, @boisgera  is now a reviewer

**Comment by moorepants** [comment]
@whedon add @alfredocarella as reviewer

**Comment by whedon** [comment]
OK, @alfredocarella is now a reviewer

**Comment by moorepants** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/148.
