### ISSUE TITLE
[PRE REVIEW]: An Active Learning Laboratory Manual for Teaching a Contemporary Undergraduate Operating System Course

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#151]
**Submitting author:** @saverioperugini (<a href="http://orcid.org/0000-0002-1736-4009">Saverio Perugini</a>)
**Repository:** <a href="https://bitbucket.org/saverioperugini/operating-systems-lab-manual/" target ="_blank">https://bitbucket.org/saverioperugini/operating-systems-lab-manual/</a>
**Version:** v1.0.0
**Editor:** @csev
**Reviewers:** @MattForshaw, @georgiastuart
**Managing EiC:** Jordan Gorzalski

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1/status.svg)](https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1"><img src="https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1/status.svg)](https://jose.theoj.org/papers/c75d974e8d532948840318176362cbb1)
```

**Author instructions**

Thanks for submitting your paper to JOSE @saverioperugini. **Currently, there isn't an JOSE editor assigned** to your paper.

@saverioperugini if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #151 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by jgorzalski** [comment]
@whedon generate pdf from branch PAPER

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch PAPER. Reticulating splines etc...
```

**Comment by jgorzalski** [comment]
@whedon generate pdf from branch PAPER

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch PAPER. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #151 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by jgorzalski** [comment]
@openjournals/dev seem to have trouble compiling the PDF for this paper - any ideas about the cause?

**Comment by saverioperugini** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by jgorzalski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #151 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:155:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by xuanxu** [comment]
> @openjournals/dev seem to have trouble compiling the PDF for this paper - any ideas about the cause?

There are some empty `orcid` entries in the paper's metadata section. They should be removed for the PDF to compile.

**Comment by jgorzalski** [comment]
@saverioperugini see above comment ☝️ for fix to compile paper. Thank you @xuanxu!

_"There are some empty orcid entries in the paper's metadata section. They should be removed for the PDF to compile."_

**Comment by saverioperugini** [comment]
Thanks. Just fixed that and committed/pushed.

--

Saverio Perugini, Ph.D.
Professor
Department of Computer Science
University of Dayton
300 College Park
Dayton, OH 45469-0280
Tel: +1 (937) 229-4079
Fax: +1 (937) 229-2193
E-mail: ***@***.***
WWW: http://academic.udayton.edu/SaverioPerugini/

CONFIDENTIALITY NOTICE
The information contained in this electronic message is confidential and intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this e-mail or any of its components is strictly prohibited. If you have received this email in error, please "reply" to the sender.

**Comment by jgorzalski** [comment]
@whedon generate pdf

**Comment by saverioperugini** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
@labarba – Whedon is failing here because of the size of the Git repository. It's > 1.6GB in size and is very slow to clone:

```
remote: Enumerating objects: 432, done.
remote: Counting objects: 100% (432/432), done.
remote: Compressing objects: 100% (358/358), done.
remote: Total 432 (delta 100), reused 373 (delta 65), pack-reused 0
Receiving objects: 100% (432/432), 1.61 GiB | 5.21 MiB/s, done.
Resolving deltas: 100% (100/100), done.
Updating files: 100% (429/429), done.
```

Upon some digging, this is because there is a Ubuntu VM image checked in here: `setup/VirtualMachine/bin/ubuntu-16.04-os-labs.iso`.

@saverioperugini – I would strongly encourage you to remove this image from your git repository as this will make cloning the repository very challenging for users, especially those with poorer internet connectivity. If you decide to do this, you'll need to rewrite the git history to actually reduce the size of the repository.

In the meantime, I've compiled the paper locally, and this will need to be a manual process throughout the JOSE review process as Whedon can't handle a repository of this size or structure.

[10.21105.jose.00151.pdf](https://github.com/openjournals/jose-reviews/files/7569380/10.21105.jose.00151.pdf)

**Comment by saverioperugini** [comment]
Hi,

I have removed the large image file and rewritten the history.  Sorry about that.

Saverio

--

Saverio Perugini, Ph.D.
Professor
Department of Computer Science
University of Dayton
300 College Park
Dayton, OH 45469-0280
Tel: +1 (937) 229-4079
Fax: +1 (937) 229-2193
E-mail: ***@***.***
WWW: http://academic.udayton.edu/SaverioPerugini/

CONFIDENTIALITY NOTICE
The information contained in this electronic message is confidential and intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this e-mail or any of its components is strictly prohibited. If you have received this email in error, please "reply" to the sender.

**Comment by jgorzalski** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00151/jose.00151/10.21105.jose.00151.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00151/jose.00151/10.21105.jose.00151.pdf) :page_facing_up: :point_left:

**Comment by saverioperugini** [comment]
The link https://bit.ly/jose-reviewers doesn’t seem to work. I was trying to recommend reviewers.

--

Saverio Perugini, Ph.D.
Professor
Department of Computer Science
University of Dayton
300 College Park
Dayton, OH 45469-0280
Tel: +1 (937) 229-4079
Fax: +1 (937) 229-2193
E-mail: ***@***.***
WWW: http://academic.udayton.edu/SaverioPerugini/

CONFIDENTIALITY NOTICE
The information contained in this electronic message is confidential and intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this e-mail or any of its components is strictly prohibited. If you have received this email in error, please "reply" to the sender.

**Comment by jgorzalski** [comment]
Hello @saverioperugini 👋 I'm not running into any issues clicking through that link, are receiving an error message?

**Comment by saverioperugini** [comment]
I can access it now.

The reviewers I can recommend for this paper/work are:

Matthew Foresaw ***@***.***

Georgia Stuart ***@***.***

Stian Håklev ***@***.***

Abram Connelly ***@***.***

Neal Davis ***@***.***

Rizwan Bulbul ***@***.***

Sarah Masud ***@***.***

Luiz Irber ***@***.***

Jens Lechtenbörger ***@***.***

Stefania Druga ***@***.***

Matthew Forshaw ***@***.***

Gajendra Deshpande ***@***.***

I hope this helps.


—


Saverio Perugini, Ph.D.
Professor
Department of Computer Science
University of Dayton
300 College Park
Dayton, OH 45469-0280
Tel: +1 (937) 229-4079
Fax: +1 (937) 229-2193
E-mail: ***@***.***
WWW: http://academic.udayton.edu/SaverioPerugini/

CONFIDENTIALITY NOTICE
The information contained in this electronic message is confidential and intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, or copying of this e-mail or any of its components is strictly prohibited. If you have received this email in error, please "reply" to the sender.

**Comment by jgorzalski** [comment]
Very helpful, thank you! Still working on assigning an editor, apologies for the slow response time.

**Comment by jgorzalski** [comment]
Hi @mattforshaw 👋 Would you consider volunteering to review for JOSE (The Journal of Open Source Education, sibling journal to JOSS). We are looking for reviewers with your skillset to check out this submission: **"An Active Learning Laboratory Manual for Teaching a Contemporary Undergraduate Operating System Course"** [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00151/jose.00151/10.21105.jose.00151.pdf)
Have a look and let me know! Thank you 🙏

**Comment by MattForshaw** [comment]
Hi @jgorzalski; I would be happy to help but I'm fully committed until early January so there would likely be a delay of around a month before I could perform my review. Please feel very welcome to assign this to me if it would be acceptable. Best wishes, Matt

**Comment by saverioperugini** [comment]
Hi,

Are there any updates on this submission?

thanks,

**Comment by jgorzalski** [comment]
@MattForshaw 👋  are you still interested in reviewing this submission?

**Comment by jgorzalski** [comment]
Hi @georgiastuart 👋 Would you consider volunteering to review for JOSE (The Journal of Open Source Education, sibling journal to JOSS). We are looking for reviewers with your skillset to check out this submission: "An Active Learning Laboratory Manual for Teaching a Contemporary Undergraduate Operating System Course" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00151/jose.00151/10.21105.jose.00151.pdf)
Have a look and let me know! Thank you

**Comment by MattForshaw** [comment]
Hi @jgorzalski, yes I'll be very happy to help.

**Comment by csev** [comment]
Hey @jgorzalski and @labarba I will take a look at this as well.

**Comment by jgorzalski** [comment]
@whedon add @MattForshaw as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by georgiastuart** [comment]
Happy to review!

**Comment by csev** [comment]
Hey @jgorzalski - I have looked through the PDF and like it a lot.  But I want to do some basic testing - it seems as though I cannot highlight and/or launch the links from the generated PDF.

**Comment by labarba** [comment]
@csev Thanks for the help! Since we have two willing reviewers, I'll assign you as editor here (Jordan and I will help!) and we can start the review, and you can post your assessment of the submission there. 

Note that you have to download the PDF to click on any embedded links. The GitHub preview doesn't allow it.

**Comment by labarba** [comment]
@whedon assign @csev as editor

**Comment by whedon** [comment]
OK, the editor is @csev

**Comment by labarba** [comment]
@whedon assing @MattForshaw as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by labarba** [comment]
@whedon assign @MattForshaw as reviewer

**Comment by whedon** [comment]
OK, @MattForshaw is now a reviewer

**Comment by labarba** [comment]
@whedon add @georgiastuart as reviewer

**Comment by whedon** [comment]
OK, @georgiastuart is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/162.

**Comment by labarba** [comment]
@csev and @MattForshaw, @georgiastuart — we started the review in a new issue: head over to https://github.com/openjournals/jose-reviews/issues/162
