### ISSUE TITLE
[PRE REVIEW]: Hyper2D: a finite-volume solver for hyperbolic PDEs and hypersonic flows

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#157]
**Submitting author:** @sbocce (<a href="http://orcid.org/0000-0003-2276-9606">Stefano Boccelli</a>)
**Repository:** <a href="https://github.com/sbocce/hyper2D" target ="_blank">https://github.com/sbocce/hyper2D</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @ketch, @mandli
**Managing EiC:** Jordan Gorzalski

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d/status.svg)](https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d"><img src="https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d/status.svg)](https://jose.theoj.org/papers/bfae4c46b559c6edea1e47b89f37e08d)
```

**Author instructions**

Thanks for submitting your paper to JOSE @sbocce. **Currently, there isn't an JOSE editor assigned** to your paper.

@sbocce if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 879

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.08 s (149.6 files/s, 15947.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
MATLAB                           5            203            254            391
make                             5             76             43            112
Markdown                         1             29              0            108
TeX                              1              7              0             56
-------------------------------------------------------------------------------
SUM:                            12            315            297            667
-------------------------------------------------------------------------------


Statistical information for the repository 'd40c365cfb0e4da576ea0454' was
gathered on 2022/02/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1063/5.0006258 is OK
- 10.1111/j.1365-2966.2005.09546.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00157/jose.00157/10.21105.jose.00157.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00157/jose.00157/10.21105.jose.00157.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@sbocce Hi! 👋 
Thanks for your submission to JOSE. We'll be looking for a handling editor who will search for appropriate reviewers. But in the meantime, I want to say that you need to work a bit on the paper to flesh out the educational use of the software. Can you say more about how it is used in the classroom? We're looking for sufficient presentation so that another instructor may be able to reuse the software and/or educational content in their teaching.

**Comment by sbocce** [comment]
@labarba Hello, thank you for your message. 
Sure, I will modify the paper following your suggestions and push the changes on the repository. 
Just one thing: I see that the whedon code counting functionality has missed most of the code (all Fortran files). We previously had this problem and solved it switching from cloc to tokei.

**Comment by sbocce** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00157/jose.00157/10.21105.jose.00157.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00157/jose.00157/10.21105.jose.00157.pdf) :page_facing_up: :point_left:

**Comment by sbocce** [comment]
@labarba Hello, I have modified the paper introducing some examples to show how the software served as an educational tool, in the past. I'm glad to introduce further examples and/or clarifications if needed.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@mandli Hi! 👋 
Would you consider volunteering to review for JOSE (The Journal of Open Source Education, sibling journal to JOSS). We are looking for reviewers with your skillset to check out this submission: "An Active Learning Laboratory Manual for Teaching a Contemporary Undergraduate Operating System Course" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00157/jose.00157/10.21105.jose.00157.pdf)
Have a look and let me know! Thank you

**Comment by labarba** [comment]
@ketch Hi! 👋 
Would you consider volunteering to review for JOSE (The Journal of Open Source Education, sibling journal to JOSS). We are looking for reviewers with your skillset to check out this submission: "An Active Learning Laboratory Manual for Teaching a Contemporary Undergraduate Operating System Course" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00157/jose.00157/10.21105.jose.00157.pdf)
Have a look and let me know! Thank you

**Comment by sbocce** [comment]
Hello @labarba I think you may have copied the wrong title by mistake. The title of the submission should be: "Hyper2D: a finite-volume solver for hyperbolic PDEs and hypersonic flows". The link is correct though. Thank you!

**Comment by labarba** [comment]
Yikes! That's what happens when you copy-paste from saved text. Sorry! Will edit.

**Comment by ketch** [comment]
Hi @labarba !  Yes, I'd be happy to review this.

**Comment by labarba** [comment]
@whedon assign @ketch as reviewer

**Comment by whedon** [comment]
OK, @ketch is now a reviewer

**Comment by labarba** [comment]
Thanks, @ketch — that's great! Once I secure the second reviewer, we will start the review in a new issue thread. In the meantime, feel free to start exploring the submission and open any issues in the target repository.

**Comment by mandli** [comment]
Sorry for the slow reply, SIAM PP is going on and have been distracted.  I would be happy to serve as a reviewer.

**Comment by labarba** [comment]
@mandli, thanks, that's great!

**Comment by labarba** [comment]
@whedon add @mandli as reviewer

**Comment by whedon** [comment]
OK, @mandli is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/163.
