### ISSUE TITLE
[PRE REVIEW]: pendsim: Developing, Simulating, and Visualizing Feedback Controlled Inverted Pendulum Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#158]
**Submitting author:** @rland93 (<a href="http://orcid.org/0000-0001-5394-2737">Mike Sutherland</a>)
**Repository:** <a href="https://github.com/rland93/pendsim" target ="_blank">https://github.com/rland93/pendsim</a>
**Version:** v1.0.0
**Editor:** @moorepants
**Reviewers:** @cooperrc, @repagh
**Managing EiC:** Jordan Gorzalski

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a/status.svg)](https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a"><img src="https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a/status.svg)](https://jose.theoj.org/papers/f2bb0a8f4e8b9b59c955c1cc482a2b5a)
```

**Author instructions**

Thanks for submitting your paper to JOSE @rland93. **Currently, there isn't an JOSE editor assigned** to your paper.

@rland93 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1049

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (286.4 files/s, 102772.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            264            586            919
Jupyter Notebook                 6              0           6920            386
Markdown                         2             66              0            132
reStructuredText                 4             82             98            101
TeX                              1              2              0             29
DOS Batch                        1              8              1             26
make                             1              5              7             16
YAML                             1              6             10             14
CSS                              1              1              0              8
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            27            434           7622           1634
-------------------------------------------------------------------------------


Statistical information for the repository 'a72532b7dd7c221f2b0042bc' was
gathered on 2022/02/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mike Sutherland                 19          2585           2036           29.12
ms                              23          5399           4472           62.21
rland93                          6           954            422            8.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mike Sutherland            1690           65.4          2.5                8.46
rland93                      79            8.3          3.6               41.77
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00158/jose.00158/10.21105.jose.00158.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00158/jose.00158/10.21105.jose.00158.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@moorepants — hi Jason! 👋  It looks like this submission is in your wheelhouse, doesn't it? Could you handle it?

**Comment by moorepants** [comment]
Yes, I'll take this one.

**Comment by moorepants** [comment]
@whedon assign @moorepants as editor

**Comment by whedon** [comment]
OK, the editor is @moorepants

**Comment by moorepants** [comment]
@rland93 can you address "Failed to discover a Statement of need section in paper"?

**Comment by moorepants** [comment]
Also, can you suggest some reviewers that do not have conflicts of interest:

"@rland93 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list)."

**Comment by rland93** [comment]
@moorepants 

Ah! Sorry about the long no-response -- this went to a different email that I don't check regularly.

Thanks for the review!

I have included a Statement of Need section. Maybe there is a particular flag or way of formatting that I need to include. I will look at it.

I don't have too many contacts or ideas for reviewers, but I will ask around.

Best, 
Mike

**Comment by rland93** [comment]
Alright, https://github.com/rland93/pendsim/commit/ba34d4d70c7411803938da8c4c002519dbfa9e44 should have fixed that issue.

**Comment by moorepants** [comment]
@rland93 Did you look at the list of reviewers? None of those are possibly suitable?

**Comment by rland93** [comment]
I think it would be suitable for these JOSE reviewers, also:

- Cameron Devine
- Sébastien Boisgérault
- Erich Wehrle
- Kyle Niemeyer

I thought you meant external reviewers. Sorry, I am not familiar with this process!

**Comment by rland93** [comment]
re: https://github.com/rland93/pendsim/commit/ba34d4d70c7411803938da8c4c002519dbfa9e44

@whedon generate pdf

**Comment by moorepants** [comment]
@boisgera can review the article but not until May 1. We can select him as a tentative reviewer, but I will continue to look for others and if we get two that can start earlier I will go with them. Thank you @boisgera!

**Comment by moorepants** [comment]
@cooperrc Thanks for your willingness to review. The number of hours should be similar to other journal reviews, it's up to you how much time you spend. A couple of hours is probably the minimum overall. Once we secure at least two reviewers we will set a due date. 2 weeks is really good, a month is probably more realistic.

Have a look at our reviewer guidelines while I continue looking for another reviewer that can start soon: https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html

**Comment by moorepants** [comment]
@whedon add @cooperrc as reviewer

**Comment by whedon** [comment]
OK, @cooperrc is now a reviewer

**Comment by moorepants** [comment]
Rene van Paasen @repagh has agreed to be a second reviewer. Thanks Rene!

@boisgera I'm going to proceed with Ryan Cooper and Rene as the two reviewers. Thanks for volunteering, but we can reach out to you for a future review.

For Rene and Ryan, please have a look over the https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html to familiarize yourself with the process. I will now open a new github issue where the review will occur and further instructions will be available there. Thanks for volunteering your time and expertise.

**Comment by moorepants** [comment]
@whedon add @repagh as reviewer

**Comment by whedon** [comment]
OK, @repagh is now a reviewer

**Comment by moorepants** [comment]
@rland93 there does not seem to be a tag or release in your github repository corresponding to Version 1.0. Can you please tag the version we will be reviewing?

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by moorepants** [comment]
@whedon check references

**Comment by moorepants** [comment]
@whedon check repository

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00158/jose.00158/10.21105.jose.00158.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00158/jose.00158/10.21105.jose.00158.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1515/9781400828739 is OK
- 10.1109/MCSE.2007.55 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.23 s (117.5 files/s, 42113.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           9            264            586            919
Jupyter Notebook                 6              0           6920            386
Markdown                         2             65              0            124
reStructuredText                 4             82             98            101
TeX                              1              2              0             29
DOS Batch                        1              8              1             26
make                             1              5              7             16
YAML                             1              6             10             14
CSS                              1              1              0              8
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                            27            433           7622           1626
-------------------------------------------------------------------------------


Statistical information for the repository '860f860347e07b79c021839e' was
gathered on 2022/03/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mike Sutherland                 19          2585           2036           29.12
ms                              23          5399           4472           62.21
rland93                          6           954            422            8.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mike Sutherland            1690           65.4          2.5                8.46
rland93                      79            8.3          3.6               41.77
```

**Comment by rland93** [comment]
Thank you Dr. Van Paasen and Dr. Cooper for the review, it is very much appreciated.

> @rland93 there does not seem to be a tag or release in your github repository corresponding to Version 1.0. Can you please tag the version we will be reviewing?

Yes! I created [v1.0.0](https://github.com/rland93/pendsim/releases/tag/v1.0.0) this version as a release. 

Thanks,
Mike

**Comment by moorepants** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by moorepants** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/168.
