### ISSUE TITLE
[PRE REVIEW]: Spatial data analysis with R: wrangling, visualization and econometric models

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#166]
**Submitting author:** @jaime-pru (<a href="http://orcid.org/0000-0001-5866-1280">Jaime Alberto Prudencio Vázquez</a>)
**Repository:** <a href="https://github.com/jaime-pru/Analisis-de-datos-espaciales" target ="_blank">https://github.com/jaime-pru/Analisis-de-datos-espaciales</a>
**Version:** 1.0
**Editor:** @allisonhorst
**Reviewers:** @hernandezcortes, @nmorandeira 
**Managing EiC:** Lorena Barba

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". 

## Status

[![status](https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d/status.svg)](https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d"><img src="https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d/status.svg)](https://jose.theoj.org/papers/aed2caaa5c0f30d574b83e80bd29f17d)
```

**Author instructions**

Thanks for submitting your paper to JOSE @jaime-pru. **Currently, there isn't an JOSE editor assigned** to your paper.

The author's suggestion for the handling editor is @allisonhorst.

@jaime-pru if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 974

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-23430-9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=2.12 s (28.8 files/s, 9269.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            18            421              5           9104
JavaScript                      14            806            565           3887
CSS                              6            140             60           1074
Rmd                              9            979           1481            419
SVG                              1              0              0            288
TeX                              4             34              0            257
Markdown                         4             34              0             51
YAML                             3              2              0             31
JSON                             2              0              0              2
-------------------------------------------------------------------------------
SUM:                            61           2416           2111          15113
-------------------------------------------------------------------------------


Statistical information for the repository 'df439ccc44e1c0e12475536a' was
gathered on 2022/03/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jaime                            1         10516              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jaime                     10516          100.0          0.0               10.75
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00166/jose.00166/10.21105.jose.00166.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00166/jose.00166/10.21105.jose.00166.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@whedon assign @allisonhorst as editor

**Comment by whedon** [comment]
OK, the editor is @allisonhorst

**Comment by allisonhorst** [comment]
@whedon assign @hernandezcortes as reviewer

**Comment by whedon** [comment]
OK, @hernandezcortes is now a reviewer

**Comment by allisonhorst** [comment]
@whedon add @nmorandeira  as reviewer

**Comment by whedon** [comment]
OK, @nmorandeira  is now a reviewer

**Comment by allisonhorst** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/173.
