### ISSUE TITLE
[PRE REVIEW]: SNIK Graph—Visualizing Knowledge about Management of Hospital Information Systems

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#169]
**Submitting author:** @KonradHoeffner (<a href="http://orcid.org/0000-0001-7358-3217">Konrad Höffner</a>)
**Repository:** <a href="https://github.com/snikproject/snik-graph" target ="_blank">https://github.com/snikproject/snik-graph</a>
**Version:** 3.0.0
**Editor:** @juanklopper
**Reviewers:** @bwatson, @behollister
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09/status.svg)](https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09"><img src="https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09/status.svg)](https://jose.theoj.org/papers/789a3e340dadf910c4ac2e1b6e225f09)
```

**Author instructions**

Thanks for submitting your paper to JOSE @KonradHoeffner. **Currently, there isn't an JOSE editor assigned** to your paper.

@KonradHoeffner if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (997.3 files/s, 99541.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                      45            266            859           4246
HTML                             5             14             20            355
JSON                             5              0              0            250
CSS                              4             28              0            200
Markdown                         3             58              0            195
TeX                              1             13              0            125
JavaScript                       2              7              6             76
YAML                             1              9              0             40
Dockerfile                       1              1              0             15
Bourne Shell                     1              1              0              3
-------------------------------------------------------------------------------
SUM:                            68            397            885           5505
-------------------------------------------------------------------------------


Statistical information for the repository '11aabf515f3549a35ad15e30' was
gathered on 2022/04/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Konrad Hoeffner                 42          1189          27200           35.66
Konrad Höffner                 650         22149          20760           53.89
T-P-1                            3             7              6            0.02
Thomas Pause                    28           469            422            1.12
ThomasPause                    108          4148           3267            9.31

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Konrad Höffner               23            0.1          2.6                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv557 is OK
- 10.1145/75335.75352 is OK
- 10.3233/978-1-61499-678-1-349 is OK
- 10.1145/2362499.2362532 is OK
- 10.1109/jcsse.2018.8457325 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon invite @juanklopper as editor

**Comment by whedon** [comment]
@juanklopper has been invited to edit this submission.

**Comment by juanklopper** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @juanklopper

**Comment by KonradHoeffner** [comment]
# Reviewer Suggestions
* eglerean: JavaScript as preferred language, graph theory and network science
* behollister: preference for JavaScript and the listed domain of Scientific Visualization.

**Comment by behollister** [comment]
I'm open to doing the review. Please note that I am still finishing https://github.com/openjournals/joss-reviews/issues/4283.

Should be done with that one tomorrow, or the next day.

**Comment by whedon** [comment]
OK, @bwatson is now a reviewer

**Comment by behollister** [comment]
Hi @juanklopper. If you want to add me as a reviewer, I am happy to help out.

**Comment by juanklopper** [comment]
@whedon add @behollister as reviewer

**Comment by whedon** [comment]
OK, @behollister is now a reviewer

**Comment by juanklopper** [comment]
Thank you @bwatson and @behollister for reviewing.

**Comment by juanklopper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/180.
