### ISSUE TITLE
[PRE REVIEW]: The Argo Online School: An e-learning tool to get started with Argo

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#170]
**Submitting author:** @Alberto-GS (<a href="http://orcid.org/0000-0001-5781-9330">Alberto González</a>)
**Repository:** <a href="https://github.com/euroargodev/argoonlineschool" target ="_blank">https://github.com/euroargodev/argoonlineschool</a>
**Version:** 1.0
**Editor:** @kls2177
**Reviewers:** @bzemskova
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode".

## Status

[![status](https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818/status.svg)](https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818"><img src="https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818/status.svg)](https://jose.theoj.org/papers/b66eaed8751b3adb6f2f4ad146380818)
```

**Author instructions**

Thanks for submitting your paper to JOSE @Alberto-GS. **Currently, there isn't an JOSE editor assigned** to your paper.

@Alberto-GS if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.17882/42182 is OK
- 10.5281/zenodo.4539666 is OK
- 10.3389/fmars.2019.00439 is OK
- 10.1038/nclimate2872 is OK
- 10.1038/nclimate2872 is OK
- 10.1175/JTECH-D-19-0041.1 is OK
- 10.21105/joss.02425 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (367.8 files/s, 206072.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                29              0          21124            697
JSON                             3              0              0            635
Markdown                         4             75              0            147
YAML                             4             22             12            121
TeX                              1             16              4            116
-------------------------------------------------------------------------------
SUM:                            41            113          21140           1716
-------------------------------------------------------------------------------


Statistical information for the repository '20eadd361d06e329b165b954' was
gathered on 2022/04/04.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Pedro Velez                     27         27542          28260           64.49
PedroVelez                      15         15719          15001           35.51

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00170/jose.00170/10.21105.jose.00170.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00170/jose.00170/10.21105.jose.00170.pdf) :page_facing_up: :point_left:

**Comment by Alberto-GS** [comment]
@whedon given the background, I'd like to propose Ali Ramadhan, Daniel Buscombe, David Pérez-Suárez or Julia Wagemann for reviewing. 

Sorry in advance if a make any mistake (JOSE first-timer).

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by Alberto-GS** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Alberto-GS** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by Alberto-GS** [comment]
jwagemann
dpshelio
marda-science
ali-ramadhan

**Comment by labarba** [comment]
@whedon invite @lorenanicole as editor

**Comment by labarba** [comment]
@whedon invite @lorenanicole as editor

**Comment by jgorzalski** [comment]
@whedon invite @lorenanicole as editor

**Comment by Alberto-GS** [comment]
> @openjournals/dev — why is the editorial bot not obeying me here?

Hi, is there anything I can do?

**Comment by arfon** [comment]
@labarba – this assignment is failing as it doesn't look like @lorenanicole's profile was correctly set up on the JOSE site. @lorenanicole – can you make sure you've logged in with your ORCID here: https://jose.theoj.org and I can fix this.

**Comment by labarba** [comment]
Oops. Since we don't have new editors very often, I guess I forget some steps! Apologies.

**Comment by labarba** [comment]
@whedon invite @lorenanicole as editor

**Comment by arfon** [comment]
> @labarba – this assignment is failing as it doesn't look like @lorenanicole's profile was correctly set up on the JOSE site. @lorenanicole – can you make sure you've logged in with your ORCID here: https://jose.theoj.org/ and I can fix this.

@labarba – we're still in the same situation here. @lorenanicole - have you logged in to the JOSE site? If so, could you tell me what your ORCID is so I can fix your account?

**Comment by Alberto-GS** [comment]
@lorenanicole

**Comment by PedroVelez** [comment]
Hi @labarba and  @lorenanicole is there any way to continue with the process. Thanks a lot!

**Comment by labarba** [comment]
hi @Alberto-GS  and @PedroVelez 👋 
Thank you for your patience. I did not receive a reply from the editor we initially assigned to this submission, despite several emails and DMs. (People have generally been much harder to reach in the past 2.5 years, and one can never know what is affecting them.) The good news is that JOSE had a campaign to recruit new editors, and we have 7 editors joining the board as we speak! (They need to be onboarded, though.)

In the meantime, I had a fresh look at the submission, in more depth, and let me anticipate a few things. 

1. About the videos: note that JOSE considers videos as supplementary material that we do not review (*). I did notice that you have the videos on Google Drive, and for me they did not play on JupyterBook, as you have embedded them. It needed a "pop-out" to Drive. Have you considered putting them in a YouTube channel? (Perhaps unlisted? Vimeo is also an option). Then using [`from IPython.display import YouTubeVideo`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.YouTubeVideo) they will be playable in the Jupyter notebook (and JupyterBook?).
2. On your paper, a reader has to wonder what Argos is all the way to the "Statement of Need," so I think that first paragraph there should be moved to the top of the Introduction.
3. Regarding the audience, you mention high-school students, which called my attention. Is there any experience involving high-school students in this topic? Do you have any experiences with different student populations that you could tell us about?

(*) We do not review videos, or slide presentations, or other forms of OCW, because they cannot be modified or easily reused. JOSE reviews open-source material that is reusable and allows derived works. Also, when you make an archive of the repository (source files for the JupyterBook), the videos will not be included.

**Comment by labarba** [comment]
Another possibility is to add the videos in an iframe within the markdown, rather than a code cell. Like this example: 
https://so-cool.github.io/you-only-write-thrice/

**Comment by labarba** [comment]
Thank you, Karen! I will assign you as editor. Since this will be your first assignment as editor, count on my as your buddy and ask me anything!

**Comment by labarba** [comment]
@whedon assign @kls2177 as editor

**Comment by whedon** [comment]
OK, the editor is @kls2177

**Comment by PedroVelez** [comment]
Dear @labarba and  @kls2177 , thanks a lot for the comments. 
We will fix the videos and reply to the comments regarding  the text as soon as possible.
best
pedro

**Comment by labarba** [comment]
hi everyone! 👋 
@kls2177 – I know this is your first submission as editor, so please do not hesitate to ask for help. We need to find two reviewers. You can start with the [list of volunteers](https://bit.ly/jose-reviewers), also look through published papers and see if we can recruit a JOSE author (to give back to the community!), or have a Googling about the 'net 🚀

**Comment by kls2177** [comment]
Hi @labarba, Thanks for checking-in. I have sent out quite a few reviewer invites but no luck so far. I will keep at it.

**Comment by kls2177** [comment]
@editorialbot add @bzemskova as reviewer

**Comment by labarba** [comment]
Hi @kls2177 👋 — JOSE is behind in the Open Journals technology, and we're still not upgraded to `@editorialbot`. Summon our old bot `@whedon` instead!

**Comment by kls2177** [comment]
@whedon add @bzemskova as reviewer

**Comment by whedon** [comment]
OK, @bzemskova is now a reviewer

**Comment by kls2177** [comment]
@whedon add @gaelforget as reviewer

**Comment by kls2177** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/193.
