### ISSUE TITLE
[PRE REVIEW]: What and How of Machine Learning Transparency: Building Bespoke Explainability Tools with Interoperable Algorithmic Components

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#171]
**Submitting author:** @So-Cool (<a href="http://orcid.org/0000-0002-9869-5896">Kacper Sokol</a>)
**Repository:** <a href="https://github.com/fat-forensics/Surrogates-Tutorial" target ="_blank">https://github.com/fat-forensics/Surrogates-Tutorial</a>
**Version:** 2020-ecml-pkdd
**Editor:** @ttimbers
**Reviewers:** @kvarada, @arokem
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f/status.svg)](https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f"><img src="https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f/status.svg)](https://jose.theoj.org/papers/d58625bd4c600da866522c879986b18f)
```

**Author instructions**

Thanks for submitting your paper to JOSE @So-Cool. **Currently, there isn't an JOSE editor assigned** to your paper.

@So-Cool if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1147

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
@ttimbers has been invited to edit this submission.

**Comment by ttimbers** [comment]
Happy to act as editor here @labarba !

**Comment by labarba** [comment]
Great! Here's a neat trick: you can run `@whedon assign me as editor`

**Comment by ttimbers** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @ttimbers

**Comment by So-Cool** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2939672.2939778 is OK
- 10.48550/arXiv.1710.09412 is OK
- 10.48550/arXiv.1910.13016 is OK
- 10.48550/arXiv.1909.05167 is OK
- 10.21105/joss.01904 is OK
- 10.48550/arXiv.2005.01427 is OK
- 10.48550/arXiv.2008.07007 is OK
- 10.48550/arXiv.2112.14466 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by So-Cool** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: :point_left:

**Comment by ttimbers** [comment]
@So-Cool - thank-you for your submission. I have read your manuscript and considered it with the scope of JOSE. Typically, short learning modules are not within scope of the journal. However, short learning modules can be considered if the authors show substantial scholarly effort in other ways. One example of this would be if the tutorial has been given many times and iteratively improved. Another example would be that the module has been subject to methodical evaluation. These scholarly efforts should be reported in the manuscript.

Reading your manuscript, I did note you mentioned this module has been taught more than once, and perhaps by others? If this were further elaborated on, as well as what has been learned from teaching this several times, that could be considered on of the scholarly efforts we described above.

**Comment by So-Cool** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2939672.2939778 is OK
- 10.48550/arXiv.1710.09412 is OK
- 10.48550/arXiv.1910.13016 is OK
- 10.48550/arXiv.1909.05167 is OK
- 10.21105/joss.01904 is OK
- 10.48550/arXiv.2005.01427 is OK
- 10.48550/arXiv.2008.07007 is OK
- 10.48550/arXiv.2112.14466 is OK
- 10.1023/A:1010933404324 is OK
- 10.1080/10618600.2014.907095 is OK
- 10.1214/aos/1013203451 is OK
- 10.48550/arXiv.2107.06639 is OK
- 10.1038/s42256-019-0048-x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by So-Cool** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf) :page_facing_up: :point_left:

**Comment by So-Cool** [comment]
Thank you for your review, @ttimbers. We have revised the manuscript based on your comments. In particular, the last paragraph of the "Modular Surrogate Explainers" section has been updated and extended by a new paragraph explaining the evolution of the training materials and our teaching experience.

**Comment by ttimbers** [comment]
@joelostblom – hi! 👋 you teach related topics and I wonder if you would consider contributing a review on this manuscript submitted to JOSE. We are in need of some help with this submission:

Title: What and How of Machine Learning Transparency:
Building Bespoke Explainability Tools with Interoperable
Algorithmic Components
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf)

Thanks for considering it!

**Comment by ttimbers** [comment]
@kbodwin - hi! 👋 you are listed on the JOSE reviewer volunteer list, and that you have domain expertise in machine learning. Thus, I wonder if you would consider contributing a review on this manuscript submitted to JOSE. We are in need of some help with this submission:

Title: What and How of Machine Learning Transparency:
Building Bespoke Explainability Tools with Interoperable
Algorithmic Components
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf)

Thanks for considering it!

**Comment by ttimbers** [comment]
A gentle ping to @joelostblom and @kbodwin to answer whether or not they could serve as reviewers for this?

**Comment by joelostblom** [comment]
Thanks for the ping and sorry for my delayed reply! After reading through the manuscript, I must unfortunately decline to review as I don't think I have enough expertise on this specific topic to provide valuable feedback and advice on the submission.

**Comment by ttimbers** [comment]
Thanks @joelostblom for the reply and completely understandable.

**Comment by ttimbers** [comment]
Thanks @kvarada for agreeing (over Slack) to serve as a reviewer for this manuscript 🎉

**Comment by ttimbers** [comment]
@whedon add @kvarada as reviewer

**Comment by whedon** [comment]
OK, @kvarada is now a reviewer

**Comment by ttimbers** [comment]
@kbodwin - I am going to assume you don't have the time to review this and search for another reviewer, please correct me in case I am wrongly assuming this.

**Comment by ttimbers** [comment]
@arokem - hi! 👋 you are listed on the JOSE reviewer volunteer list, and that you have domain expertise in machine learning. Thus, I wonder if you would consider contributing a review on this manuscript submitted to JOSE. We are in need of some help with this submission:

Title: What and How of Machine Learning Transparency:
Building Bespoke Explainability Tools with Interoperable
Algorithmic Components
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf)

Thanks for considering it!

**Comment by kbodwin** [comment]
> @kbodwin - I am going to assume you don't have the time to review this and search for another reviewer, please correct me in case I am wrongly assuming this.

Sorry to miss this!  

I don't think the material is quite in my wheelhouse, but if you don't find someone by the end of June, I'll be done with a mountain of deadlines and willing to give it a go.

**Comment by arokem** [comment]
Hi @ttimbers : I am currently bogged down with other reviews and leaving for a conference at the end of the week. If you don't have the needed reviewers at the end of the month, I'd be happy to jump on it then. Or, if that's an acceptable delay, you can assign me, with the understanding that I will not get to it before the end of June.

**Comment by ttimbers** [comment]
Thank-you @kbodwin and @arokem. @kbodwin - no worries, if you feel this is outside of your wheelhouse, then we will find someone else. @arokem - thanks for offering if we cannot find anyone else before the end of the month. I will let you know in the event that happens.

**Comment by ttimbers** [comment]
@mnarayan - hi! 👋 you are listed on the JOSE reviewer volunteer list, and that you have domain expertise in machine learning. Thus, I wonder if you would consider contributing a review on this manuscript submitted to JOSE. We are in need of some help with this submission:

Title: What and How of Machine Learning Transparency:
Building Bespoke Explainability Tools with Interoperable
Algorithmic Components
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00171/jose.00171/10.21105.jose.00171.pdf)

Thanks for considering it!

**Comment by mnarayan** [comment]
I'm not available for the next 2 weeks. If the issue is still open after
that, I can review.

**Comment by ttimbers** [comment]
@arokem - I am going to have to take you up on your kind offer to act as a reviewer for this paper. It seems to be a tricky time of year to find folks to review, so we are very happy to work with you on a review timeline that fits with your availability. I will open the review now with the understanding that you cannot start this until after June. Many thanks!

**Comment by ttimbers** [comment]
@whedon add @arokem as reviewer

**Comment by ttimbers** [comment]
@mnarayan - thank-you for the offer, however we had another reviewer provide the same offer a bit earlier than you. We will of course keep you in mind for the next machine learning paper we need reviewed at JOSE!

**Comment by ttimbers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/175.
