### ISSUE TITLE
Journal ISSN

### ISSUE THREAD

**Issue by nmorandeira** [openjournals/jose-reviews#174]
This is a suggestion for the JOSE webpage. @allisonhorst 
It's difficult to find the journal's ISSN, which is only included in the footnote below the CC logo, and with low color contrast.
I suggest including the ISSN in the first section of the [About webpage](https://jose.theoj.org/about)

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
