### ISSUE TITLE
[PRE REVIEW]: The Data Behind Dark Matter: Exploring Galactic Rotation

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#177]
**Submitting author:** @villaa (<a href="http://orcid.org/0000-0002-3893-7259">Anthony Villano</a>)
**Repository:** <a href="https://github.com/villano-lab/galactic-spin-W1" target ="_blank">https://github.com/villano-lab/galactic-spin-W1</a>
**Version:** v3.0.0
**Editor:** @moorepants
**Reviewers:** @Carreau, @noelstoj
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df/status.svg)](https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df"><img src="https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df/status.svg)](https://jose.theoj.org/papers/9fc3443a7c138ea1a3e1a15f4a3f14df)
```

**Author instructions**

Thanks for submitting your paper to JOSE @villaa. **Currently, there isn't an JOSE editor assigned** to your paper.

@villaa if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1184

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00177/jose.00177/10.21105.jose.00177.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00177/jose.00177/10.21105.jose.00177.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1086/182804 is OK
- 10.1046/j.1365-8711.2003.06165.x is OK
- 10.3847/0004-6256/152/6/157 is OK
- 10.5281/zenodo.5570790 is OK
- 10.1093/mnras/203.3.735 is OK
- 10.1051/0004-6361/201116634 is OK
- 10.1111/j.1365-2966.2008.12837.x is OK
- 10.1111/j.1365-2966.2007.11532.x is OK
- 10.1093/mnras/stv568 is OK
- 10.1086/318767 is OK
- 10.1051/0004-6361/201425339 is OK
- 10.1111/j.1365-2966.2008.13422.x is OK
- 10.1086/505345 is OK
- 10.1086/527543 is OK
- DOI:10.5281/zenodo.6588350 is OK

MISSING DOIs

- 10.5860/choice.35-2173 may be a valid DOI for title: An Introduction to Error Analysis: The Study of Uncertainties in Physical Measurements

INVALID DOIs

- None
```

**Comment by juditbergfalk** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by juditbergfalk** [comment]
Hello @jgorzalski ! 
I would like to add **Ian Hawke** to @villaa 's list of reviewers. Reviewer has astrophysics knowledge.
Thank you

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by villaa** [comment]
@jgorzalski My team has made some upgrades so we would like to change the review version here to [v3.0.0](https://github.com/villano-lab/galactic-spin-W1/releases/tag/v3.0.0), thanks.

**Comment by labarba** [comment]
@whedon invite @moorepants

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by labarba** [comment]
@whedon invite @moorepants as editor

**Comment by whedon** [comment]
@moorepants has been invited to edit this submission.

**Comment by villaa** [comment]
@labarba I don't know if you're able, but please update the review version here to [v3.0.0](https://github.com/villano-lab/galactic-spin-W1/releases/tag/v3.0.0), thanks.

**Comment by moorepants** [comment]
@labarba I'm on vacation for the next three weeks. I could pick this up in late August or early September.

**Comment by labarba** [comment]
@whedon set v3.0.0 as version

**Comment by whedon** [comment]
OK. v3.0.0 is the version.

**Comment by labarba** [comment]
👋  @moorepants – Thank you! We are currently short of editors (two out on parental leave), so we'll wait for you here.

**Comment by moorepants** [comment]
@whedon assign @moorepants as editor

**Comment by whedon** [comment]
OK, the editor is @moorepants

**Comment by moorepants** [comment]
@IanHawke, @ali-ramadhan, @ntmoore, and @Carreau would any of you like to review this JOSE submission about an education module for simulating galaxies?

**Comment by Carreau** [comment]
Sure, I can do that.

**Comment by moorepants** [comment]
@Carreau Great! Thanks for volunteering. I hope to get 1 more reviewer before we officially start, but feel free to have a look at the paper before then.

**Comment by moorepants** [comment]
@whedon add @Carreau as reviewer

**Comment by moorepants** [comment]
Ok, I've found a second reviewer. Joel Noel-Storr (@noelstoj) has agreed to review.

**Comment by moorepants** [comment]
@whedon add @noelstoj as reviewer

**Comment by whedon** [comment]
OK, @noelstoj is now a reviewer

**Comment by moorepants** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/184.
