### ISSUE TITLE
[PRE REVIEW]: From Maps to Models - Tutorials for structural geological modeling using GemPy and GemGIS

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#178]
**Submitting author:** @AlexanderJuestel (<a href="http://orcid.org/0000-0003-0980-7479">Alexander Jüstel</a>)
**Repository:** <a href="https://github.com/cgre-aachen/gemgis_data" target ="_blank">https://github.com/cgre-aachen/gemgis_data</a>
**Version:** v.1.0.0
**Editor:** @acocac
**Reviewers:** @BenjMy, @jwagemann
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941/status.svg)](https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941"><img src="https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941/status.svg)](https://jose.theoj.org/papers/5e6ad1eedf43a1175c41e188b2881941)
```

**Author instructions**

Thanks for submitting your paper to JOSE @AlexanderJuestel. **Currently, there isn't an JOSE editor assigned** to your paper.

@AlexanderJuestel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 2280

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.4569086 is OK
- 10.5194/gmd-12-1-2019 is OK
- 10.21105/joss.01450 is OK
- 10.5281/zenodo.4572994 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1016/j.pepi.2008.06.013 is OK
- 10.1007/978-94-011-2556-7_11 is OK
- 10.1130/GES02455.1 is OK
- 10.1007/BF02775087 is OK
- 10.1007/978-1-4615-9630-1 is OK
- 10.21105/joss.03709 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.81 s (83.8 files/s, 137751.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                49              0         105485           5289
Markdown                         7            107              0            268
QML                              1              3              0            240
XML                              8              0              0            221
TeX                              1             14              0            168
YAML                             2              5              6             34
-------------------------------------------------------------------------------
SUM:                            68            129         105491           6220
-------------------------------------------------------------------------------


Statistical information for the repository '8036508bc786e23e79e15049' was
gathered on 2022/07/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00178/jose.00178/10.21105.jose.00178.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00178/jose.00178/10.21105.jose.00178.pdf) :page_facing_up: :point_left:

**Comment by jgorzalski** [comment]
Hi @AlexanderJuestel 👋 If you could please take a look at the list of reviewers and see if you have any suggestions that would be great! Thank you!

**Comment by AlexanderJuestel** [comment]
Dear @jgorzalski, 

I would start with **sharondenisse** as her preferred programming language is Python and her Topic Areas include Geology
Secondly, I would go with **jwagemann** as her preferred programming language is also Python and her Topic Areas include Geospatial Data Analysis. 

Cheers
Alex

**Comment by AlexanderJuestel** [comment]
@jgorzalski, I suggested some reviewers, maybe we can continue the procedure once you have time :)

Cheers Alex

**Comment by AlexanderJuestel** [comment]
@jgorzalski just wanted to check in when we can proceed with the Pre-Review?

Cheers Alex

**Comment by labarba** [comment]
@whedon invite @ShanEllis as editor

**Comment by whedon** [comment]
@ShanEllis has been invited to edit this submission.

**Comment by ShanEllis** [comment]
Hi! Thanks for thinking of me, but I'm currently on parental leave and won't be able to get this done.

**Comment by labarba** [comment]
Oops. Looks like I missed this fact, or confused it somehow with Tiffany, who is also on parental leave!

**Comment by AlexanderJuestel** [comment]
All good, just wanted to check in :)

**Comment by AlexanderJuestel** [comment]
Hey @labarba, 

just wanting to inquire if you have a rough schedule on how we proceed with the submission.

No hurry from my side though. 

Cheers 
Alex

**Comment by labarba** [comment]
Hi @AlexanderJuestel — I cannot give you a schedule right now. The good news is that JOSE had a campaign to recruit new editors, and we have 7 editors joining the board as we speak! (They are being onboarded this week, and their profiles has already been posted to our website.) Thank you for your patience.

**Comment by acocac** [comment]
@labarba, happy to take this one on.

**Comment by labarba** [comment]
Thank you, @acocac ! I will assign you now.

**Comment by labarba** [comment]
@whedon assign @acocac as editor

**Comment by whedon** [comment]
OK, the editor is @acocac

**Comment by acocac** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00178/jose.00178/10.21105.jose.00178.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00178/jose.00178/10.21105.jose.00178.pdf) :page_facing_up: :point_left:

**Comment by acocac** [comment]
Hi @jwagemann — you volunteered to review for JOSE (The Journal of Open Source Education). Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks! 🙏
Title: "From Maps to Models - Tutorials for structural geological modeling using GemPy and GemGIS"
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00178/jose.00178/10.21105.jose.00178.pdf) :page_facing_up: :point_left:

**Comment by acocac** [comment]
Hi @sharondenisse — you volunteered to review for JOSE (The Journal of Open Source Education). Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks! 🙏
Title: "From Maps to Models - Tutorials for structural geological modeling using GemPy and GemGIS"
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00178/jose.00178/10.21105.jose.00178.pdf) 📄 👈

**Comment by acocac** [comment]
@AlexanderJuestel, thanks for the submission. It looks in line with the scope of JOSE. Note I've already asked to suggested reviewers their availability. I'll try to reach them via e-mail too.

**Comment by jwagemann** [comment]
Hi @acocac ,
happy to function as reviewer for this submission. Will try to review it in the course of the next two weeks.
Julia

**Comment by acocac** [comment]
Hello @jwagemann, thanks for confirming your availability! I'm waiting the response of the second suggested reviewer. Hope to confirm here when we start the Review Process soon!

**Comment by acocac** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by acocac** [comment]
@whedon assign @jwagemann as reviewer

**Comment by whedon** [comment]
OK, @jwagemann is now a reviewer

**Comment by acocac** [comment]
Hi @BenjMy — you volunteered to review for JOSE (The Journal of Open Source Education). Could you take a look at this submission and let us know if you might be able to volunteer a review for us (with a flexible deadline of mid-Jan 2023)? 
Thanks! 🙏 
Title: "From Maps to Models - Tutorials for structural geological modeling using GemPy and GemGIS" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00178/jose.00178/10.21105.jose.00178.pdf) 📄 👈

**Comment by BenjMy** [comment]
Hi @acocac ,
Happy to review this submission.

**Comment by acocac** [comment]
@whedon assign @BenjMy as reviewer

**Comment by whedon** [comment]
OK, @BenjMy is now a reviewer

**Comment by acocac** [comment]
@whedon add @jwagemann as reviewer

**Comment by whedon** [comment]
OK, @jwagemann is now a reviewer

**Comment by labarba** [comment]
Thank you, all — your contributions are greatly appreciated, and make this adventure in scholarly publication possible! 🙏

**Comment by acocac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/185.
