### ISSUE TITLE
[PRE REVIEW]: flashr: An R package that creates flashcards

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#182]
**Submitting author:** @JeffreyRStevens (<a href="http://orcid.org/0000-0003-2375-1360">Jeffrey R Stevens</a>)
**Repository:** <a href="https://github.com/JeffreyRStevens/flashr" target ="_blank">https://github.com/JeffreyRStevens/flashr</a>
**Version:** v0.0.4
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0/status.svg)](https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0"><img src="https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0/status.svg)](https://jose.theoj.org/papers/f8b9e547ef043dcdcb2afb94700ac4b0)
```

**Author instructions**

Thanks for submitting your paper to JOSE @JeffreyRStevens. **Currently, there isn't an JOSE editor assigned** to your paper.

@JeffreyRStevens if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (1451.9 files/s, 103222.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               10             61            232            480
JSON                             1              0              0            169
YAML                             5             16             15            160
Markdown                         3             40              0            112
Rmd                              2             61            111             36
-------------------------------------------------------------------------------
SUM:                            21            178            358            957
-------------------------------------------------------------------------------


Statistical information for the repository 'ceef4cb66c5ae18833afbf5e' was
gathered on 2022/08/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #182 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by JeffreyRStevens** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by JeffreyRStevens** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00182/jose.00182/10.21105.jose.00182.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00182/jose.00182/10.21105.jose.00182.pdf) :page_facing_up: :point_left:

**Comment by JeffreyRStevens** [comment]
Potential reviewers from the list include Kelly Bodwin, Nic Weber, and Luke Johnston.

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by JeffreyRStevens** [comment]
Is @allisonhorst available to edit my package? If not, I can look for other possible editors.

**Comment by labarba** [comment]
hi @JeffreyRStevens – I have made a scope query on this submission, which looks like a small package (<500 lines of R). We have an internal voting process for scope queries, so stay tuned.

**Comment by JeffreyRStevens** [comment]
@labarba, looking forward to hearing back on this.

**Comment by JeffreyRStevens** [comment]
@labarba, when can I expect to hear back on the vote?

**Comment by labarba** [comment]
Hello @JeffreyRStevens – as I've already communicated by email, the board discussed this submission and decided that the contribution is insufficient for a journal paper. We look for substantial scholarly contribution, like any journal, and admitting that such a deliberation is subjective, we make our best effort to assess scope queries as a group.

(Leaving this note here for the record.)

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
