### ISSUE TITLE
[PRE REVIEW]: Special relativity in R: the lorentz package

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#187]
**Submitting author:** @RobinHankin (<a href="http://orcid.org/0000-0001-5982-0415">Robin Hankin</a>)
**Repository:** <a href="https://github.com/RobinHankin/lorentz" target ="_blank">https://github.com/RobinHankin/lorentz</a>
**Version:** 1.1-0
**Editor:** @arm61
**Reviewers:** @HaoZeke, @IanHawke
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1/status.svg)](https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1"><img src="https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1/status.svg)](https://jose.theoj.org/papers/316a824a674ee61d79bd0bdb07d07ba1)
```

**Author instructions**

Thanks for submitting your paper to JOSE @RobinHankin. **Currently, there isn't an JOSE editor assigned** to your paper.

@RobinHankin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 765

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (408.5 files/s, 81019.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              1              1              1           2693
R                               14            310             76           1210
Markdown                         3             72              0            419
TeX                              5             49              0            414
Rmd                              4            122            243            108
YAML                             1              6              1             16
make                             1              2              0              8
-------------------------------------------------------------------------------
SUM:                            29            562            321           4868
-------------------------------------------------------------------------------


Statistical information for the repository '4ce31e3b33b10eefbcbe7e0f' was
gathered on 2022/12/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00187/jose.00187/10.21105.jose.00187.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00187/jose.00187/10.21105.jose.00187.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.48550/ARXIV.2012.15149 is OK
- 10.48550/ARXIV.2212.07005 is OK
- 10.48550/ARXIV.1812.11589 is OK
- 10.21105/jose.00091 is OK

MISSING DOIs

- 10.1007/bf02550347 may be a valid DOI for title: Thomas precession: its underlying gyrogroup axioms and their use in hyperbolic geometry and relativistic physics
- 10.1063/1.168517 may be a valid DOI for title: Teaching special relativity with a computer
- 10.1119/1.4938057 may be a valid DOI for title: Visualizing relativity: the OpenRelativity project
- 10.1002/andp.19053220607 may be a valid DOI for title: Über einen die Erzeugung und Verwandlung des Lichtes betreffenden heuristischen Gesichtspunkt
- 10.1007/978-94-015-3445-1_5 may be a valid DOI for title: Electromagnetic phenomena in a system moving with any velocity smaller than that of light
- 10.1007/978-3-663-19510-8_9 may be a valid DOI for title: Kosmologische Betrachtungen zur allgemeinen Relativitätstheorie

INVALID DOIs

- None
```

**Comment by RobinHankin** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by RobinHankin** [comment]
Hello, not sure if a human reads this.  My suggestions for reviewers would be:

1.  Markus P\"ossel <poessel@hda-hd.de>    - influential worker in the field of  relativity education 
2. Ian Hawke <I.Hawke@soton.ac.uk>  -  editor for a previous JOSE paper of mine which dealt with SR

**Comment by labarba** [comment]
@arm61 — might you be able to edit this submission? As this would be your first editing assignment, you can count of me to help along the way. Let me know! (If you're ready to take it on, you can run @whedon assign me as editor right here!)

**Comment by labarba** [comment]
We still do not have an assigned handling editor, but I wonder if we can entice Gabriele Bozzola, @Sbozzolo, to help us as a reviewer? (By complete coincidence, he just followed me on Fosstodon, ha ha! I followed back ☺️)

**Comment by Sbozzolo** [comment]
Hi @labarba, unfortunately R falls outside of my expertise. So, I think I wouldn't be able to provide an insightful review, but I will be available to answer any question on the science that you or other reviewers might have.

**Comment by labarba** [comment]
Thanks for popping in here, @Sbozzolo ! Appreciate it. It looked like a lucky strike when I saw you are a numerical relativist. Do you know anyone who could help us with this review?

**Comment by Sbozzolo** [comment]
> Thanks for popping in here, @Sbozzolo ! Appreciate it. It looked like a lucky strike when I saw you are a numerical relativist. Do you know anyone who could help us with this review?

I'd be happy to help, but language is a barrier here. And, in general, I suspect it will be tough to find someone in the relativity and gravitational physics community, since we use primarily Python, Julia, C/C++, and Fortran. From a cursory look at this package, my impression is that it does not implement very sophisticated relativistic calculations, so you probably don't need a domain expert to follow what is going on (the paper itself claims that the package is meant to be accessible to undergraduate students). 

One person that I see in the [list of volunteers for JOSE](https://docs.google.com/spreadsheets/d/1gQ_KZnJx-lyJwiuHBp9rE6b2ugMkJZzigvt4QLQHCH8/edit#gid=0) is HaoZeke, who lists R as one of their preferred languages and molecular dynamics simulations as one of their topics (which suggests a physics background). 

From the [JOSS list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822), I can see AlexAxthelm, which lists R and "physics, education" as their interests. This is the only partial match I found in the first 750 lines of the document, which gives you an idea of how niche is this combination of programming language and topic.

**Comment by arm61** [comment]
Happy to handle the editing of this, but on annual leave until the 3rd so can pick it up then.

**Comment by arm61** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @arm61

**Comment by arm61** [comment]
Hey, @HaoZeke! Would you be interested in helping out and reviewing this work?

**Comment by HaoZeke** [comment]
Hi @arm61, happy to help out, but I'm a little backlogged, so I might get to this after the 15th at the earliest. If that's alright, I took a preliminary peek at the code-base and I will be able to handle the technical (`R`) review as well as the physics (at the level hinted at in the paper).

**Comment by arm61** [comment]
Fantastic thanks @HaoZeke! I will hunt a bit today for a second reviewer.

**Comment by arm61** [comment]
@whedon assign @HaoZeke as reviewer

**Comment by whedon** [comment]
OK, @HaoZeke is now a reviewer

**Comment by arm61** [comment]
Still working on finding a second reviewer. @RobinHankin do you know of others working in physics with experience in R?

**Comment by RobinHankin** [comment]
Hello Andrew, I have to say that the intersection between relativistic
physics and R is almost nonexistent  [a situation I hope to improve with
this submission!].   You might ask Zurab Silagadze,  ***@***.***>
who I have been discussing the work with.   also Rachel E. Scherr <
***@***.***> and
Andrew Harris ***@***.***>
 who work in physics education and astronomy in R respectively.

Best wishes

Robin

--
Robin K. S. Hankin
Associate Professor, computational statistics

**Comment by arm61** [comment]
Just am update that I am still working on finding a second reviewer!

**Comment by RobinHankin** [comment]
thanks for this, I appreciate it!

with best wishes

Robin
--
Robin K. S. Hankin
Associate Professor, computational statistics

**Comment by arm61** [comment]
I am pleased to say that we have a second reviewer!

**Comment by arm61** [comment]
@whedon add @IanHawke as reviewer

**Comment by whedon** [comment]
OK, @IanHawke is now a reviewer

**Comment by arm61** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/196.
