### ISSUE TITLE
[PRE REVIEW]: FANGS - Fire Applications with Next-Generation Satellites

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#189]
**Submitting author:** @sabrinaszeto (<a href="http://orcid.org/0000-0002-3050-837X"></a>)
**Repository:** <a href="https://gitlab.eumetsat.int/eumetlab/atmosphere/fire-monitoring" target ="_blank">https://gitlab.eumetsat.int/eumetlab/atmosphere/fire-monitoring</a>
**Version:** 1.0
**Editor:** @yabellini
**Reviewers:** @RomiNahir
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec/status.svg)](https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec"><img src="https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec/status.svg)](https://jose.theoj.org/papers/30a1735810dca44db249d61bbf397dec)
```

**Author instructions**

Thanks for submitting your paper to JOSE @sabrinaszeto. **Currently, there isn't an JOSE editor assigned** to your paper.

@sabrinaszeto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1161

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00189/jose.00189/10.21105.jose.00189.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00189/jose.00189/10.21105.jose.00189.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.80 s (16.6 files/s, 31633.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                25              0          54330           2258
Markdown                         2             73              0            197
Python                           1             18             49             80
YAML                             1              0              0             48
TeX                              1              3              0             39
-------------------------------------------------------------------------------
SUM:                            30             94          54379           2622
-------------------------------------------------------------------------------


Statistical information for the repository '1418f3d01a24ab697cad9a5b' was
gathered on 2022/12/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Sabrina Szeto                   24         19681          19392           99.97
jwagemann                        1             9              4            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Sabrina Szeto               294            1.5          0.0               14.29
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41598-017-00116-9 is OK
- 10.5281/zenodo.7463073 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@yabellini – this submission also sounds like your cup of tea. Maybe you prefer to edit this one, rather than #188 ...take your pick and we'll find another editor for the other submission. Or, if you're really keen, you can take them both! 🤓

**Comment by yabellini** [comment]
Yes on this one!

**Comment by yabellini** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @yabellini

**Comment by labarba** [comment]
Thank you, @yabellini – let me know how I can help. We aim to have two reviews assigned before starting the review issue. Good hunting!

**Comment by sabrinaszeto** [comment]
Hi there @labarba and @yabellini, this is my first submission to JOSE. Thanks for all you do as editors! A quick question, what does it mean to have "two reviews assigned"?

**Comment by labarba** [comment]
hi @sabrinaszeto – this is the Pre-Review issue. Here, we assign a handling editor (in this case, @yabellini had volunteer to handle the submission), who in turn looks for two willing reviewers. They will be assigned here running a command with our trusty bot `@whedon`, which enables their permissions and registers them in the backend. Then the editor will start the review in a new GitHub issue, which will automatically post a review checklist for both reviewers. Please have a look at our [documentation](https://openjournals.readthedocs.io/en/jose/).

**Comment by yabellini** [comment]
@whedon assign @andrewmaclachlan as reviewer

**Comment by whedon** [comment]
OK, @andrewmaclachlan is now a reviewer

**Comment by yabellini** [comment]
Update: I'm still looking for a second reviewer, @sabrinaszeto if you have any recommendations of potential reviewers to contact, please share them with me .

**Comment by yabellini** [comment]
@andrewmaclachlan than you for agreeing to review this paper and let me know if you have any questions about the process.

**Comment by sabrinaszeto** [comment]
Hi @yabellini, I will ask around and send you some recommendations. Is it okay if I send this to you via email or LinkedIn message? Thank you!

**Comment by yabellini** [comment]
Yea! Of course. My email yabellini@gmail.com. Thank you so much.

**Comment by yabellini** [comment]
@whedon assign @RomiNahir as reviewer

**Comment by whedon** [comment]
OK, @RomiNahir is now a reviewer

**Comment by yabellini** [comment]
Hi @andrewmaclachlan and  @RomiNahir ! Thanks you so much for agree to review this work.

**Comment by yabellini** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/197.
