### ISSUE TITLE
[PRE REVIEW]: Ecological Forecasting and Dynamics: A graduate course on the fundamentals of time series and forecasting in ecology

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#190]
**Submitting author:** @ethanwhite (<a href="http://orcid.org/0000-0001-6728-7745">Ethan P. White</a>)
**Repository:** <a href="https://github.com/weecology/forecasting-course" target ="_blank">https://github.com/weecology/forecasting-course</a>
**Version:** v2.1.0
**Editor:** @acocac
**Reviewers:** @arokem, @gvdr
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8/status.svg)](https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8"><img src="https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8/status.svg)](https://jose.theoj.org/papers/05268bf72723410e76e9d991ad956db8)
```

**Author instructions**

Thanks for submitting your paper to JOSE @ethanwhite. **Currently, there isn't an JOSE editor assigned** to your paper.

@ethanwhite if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (1515.9 files/s, 91577.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                       112           1371              0           4127
JSON                             2              0              0            977
HTML                             3             33              0            194
TeX                              1             17              0            180
YAML                             5             25             52            161
Rmd                              3            123            263            118
TOML                             2             37             65            100
R                                1             11              2             39
Bourne Shell                     1              0             14              3
SVG                              1              0              0              2
-------------------------------------------------------------------------------
SUM:                           131           1617            396           5901
-------------------------------------------------------------------------------


Statistical information for the repository '07778cdbbe81d385e6459b71' was
gathered on 2023/01/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/ecy.3709 is OK
- 10.1002/ecy.2373 is OK
- 10.1073/pnas.1710231115 is OK
- 10.1101/332783 is OK
- 10.1093/biosci/bix025 is OK
- 10.7717/peerj.4278 is OK
- 10.1111/oik.03726 is OK
- 10.1177/002248718703800308 is OK
- 10.1002/ecy.3431 is OK
- 10.2218/ijdc.v10i1.351 is OK
- 10.1111/2041-210X.13104 is OK
- 10.21105/jose.00139 is OK
- 10.12688/f1000research.3-62.v2 is OK
- 10.1111/ele.12353 is OK
- 10.1371/journal.pbio.3000125 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.9790/7388-05616670 is INVALID
- 10.1890/0012-9658(2003)084[1412:TETTWU]2.0.CO;2 is INVALID
```

**Comment by ethanwhite** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00190/jose.00190/10.21105.jose.00190.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00190/jose.00190/10.21105.jose.00190.pdf) :page_facing_up: :point_left:

**Comment by ethanwhite** [comment]
I added the missing metadata for `date` (note that not having this [doesn't produce an error using GH Actions](https://github.com/weecology/forecasting-course/actions/runs/3839250382)) and released as `v2.1.1`.

The DOIs that are flagged are the correct DOIs:

* The first one does not resolve but is the [DOI given in the paper]()

![Screenshot from 2023-01-04 14-01-25](https://user-images.githubusercontent.com/744427/210630612-a8187712-ab47-4827-8889-2705cb211aa6.png)

* The second one resolves correctly via the url <https://doi.org/10.1890/0012-9658(2003)084[1412:TETTWU]2.0.CO;2>.

**Comment by labarba** [comment]
The DOI checker is imperfect and can give false warnings.

**Comment by labarba** [comment]
For the paper by Bada and Olusegun, you may want to add the [full URL to the PDF](https://iosrjournals.org/iosr-jrme/papers/Vol-5%20Issue-6/Version-1/I05616670.pdf) (it is an open access journal). This is locator hard to find, in fact, because strangely Google Scholar lands on the Academia.edu deposit, not the journal landing page. 

Note that the full journal name is **IOSR Journal of Research & Method in Education (IOSR-JRME)** (https://iosrjournals.org/iosr-jrme.html). There is _another journal_ with the name "International Journal of Research & Method in Education," (https://www.tandfonline.com/journals/cwse20) so one has to be careful. I was a bit suspicious of this at first (is it a copy cat journal?), but the article itself is highly cited...

**Comment by labarba** [comment]
@whedon invite @acocac as editor

**Comment by whedon** [comment]
@acocac has been invited to edit this submission.

**Comment by labarba** [comment]
it appears that IOSR Journals are considered predatory by several sources 😬

**Comment by acocac** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by ethanwhite** [comment]
> it appears that IOSR Journals are considered predatory by several sources grimacing

We are citing the paper based on its content not the journal or publisher reputation. This is a well regarded paper, which, as you note, is very well cited. It's also actively referenced as a source for broad educational initiatives (e.g., https://showcase.ems.psu.edu/node/106, https://www.buffalo.edu/catt/develop/theory/constructivism.html). This high usage rate is because it is an effective introduction and review. I think that makes it the best citation here since anyone engaging with the citation in this context will likely be looking for an understandable summary and review and this is the best one I've found. That said, if citing journals by this publisher is a concern let me know and we can either supplement or replace the citation with other sources.

**Comment by acocac** [comment]
👋  @ethanwhite, happy to moderate and find reviewers for your submission. Feel free to provide recommendations of potential reviewers from @whedon list reviewers.

**Comment by acocac** [comment]
@whedon list reviewers

**Comment by acocac** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by ethanwhite** [comment]
> Did not mean it as a concern for citing the paper... but a possible explanation for the broken DOI deposit.

Ah, that makes sense. And yes their DOI infrastructure definitely seems sloppy at best.

**Comment by ethanwhite** [comment]
> :wave: @ethanwhite, happy to moderate and find reviewers for your submission. Feel free to provide recommendations of potential reviewers from @whedon list reviewers.

Good folks (github handles without @) to review this submission on the provided list include:
* jhollist (ecology + R)
* arokem (time-series +R)
* gvdr (ecology + R)
* jsta (ecology + R)
* fmichonneau (ecology + R)
* jwagemann (environmental science + R)
* andrewmaclachlan (environmental science + R)

**Comment by acocac** [comment]
Hi @AoifeHughes — you've expressed interest to volunteer to review for JOSE (The Journal of Open Source Education). Could you take a look at this submission and let us know if you might be able to volunteer a review for us? We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time.
Thanks! 🙏
Title: "Ecological Forecasting and Dynamics: A graduate course on the fundamentals of time series and forecasting in ecology" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00190/jose.00190/10.21105.jose.00190.pdf) 📄 👈

**Comment by acocac** [comment]
@whedon assign @acocac as editor

**Comment by whedon** [comment]
OK, the editor is @acocac

**Comment by acocac** [comment]
Hi @gvdr — you've expressed interest to review for JOSE (The Journal of Open Source Education). Could you take a look at this submission and let us know if you might be able to volunteer a review for us? We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time.
Thanks! 🙏
Title: "Ecological Forecasting and Dynamics: A graduate course on the fundamentals of time series and forecasting in ecology" [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00190/jose.00190/10.21105.jose.00190.pdf) 📄 👈

**Comment by gvdr** [comment]
Hi @acocac  I'm on it now. :-D

**Comment by acocac** [comment]
> Hi @acocac I'm on it now. :-D

Giulio - Cool! Thank you

**Comment by acocac** [comment]
@whedon assign @gvdr as reviewer

**Comment by whedon** [comment]
OK, @gvdr is now a reviewer

**Comment by acocac** [comment]
@whedon assign @arokem as reviewer

**Comment by whedon** [comment]
OK, @arokem is now a reviewer

**Comment by acocac** [comment]
@whedon add @gvdr as reviewer

**Comment by whedon** [comment]
OK, @gvdr is now a reviewer

**Comment by acocac** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/198.
