### ISSUE TITLE
[PRE REVIEW]: R for Data Analysis: An open-source resource for teaching and learning analytics with R

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#195]
**Submitting author:** @TrevorFrench (<a href="http://orcid.org/0000-0002-6246-2249">Trevor French</a>)
**Repository:** <a href="https://github.com/TrevorFrench/R-for-Data-Analysis" target ="_blank">https://github.com/TrevorFrench/R-for-Data-Analysis</a>
**Version:** 1.0.0
**Editor:** @stats-tgeorge
**Reviewers:** @tomsing1, @corybrunson
**Managing EiC:** Jordan Gorzalski

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45/status.svg)](https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45"><img src="https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45/status.svg)](https://jose.theoj.org/papers/5918c67cc21dfcfdca46eb925cec7e45)
```

**Author instructions**

Thanks for submitting your paper to JOSE @TrevorFrench. **Currently, there isn't an JOSE editor assigned** to your paper.

@TrevorFrench if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 689

**Comment by whedon** [comment]
PDF failed to compile for issue #195 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (414.7 files/s, 192566.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            32            933            132          22469
CSS                              4             36             12           1838
JavaScript                      11            200            197           1768
JSON                             9              0              0            794
XML                              1              0              0            131
TeX                              2             10              0            115
YAML                             1              7              0             64
Markdown                         2             33              0             52
-------------------------------------------------------------------------------
SUM:                            62           1219            341          27231
-------------------------------------------------------------------------------


Statistical information for the repository '4b2b85ba49271abb33419741' was
gathered on 2023/02/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Trevor French                    6          6293           4128          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Trevor French              2165           34.4          0.2                9.10
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ijinfomgt.2016.01.006 is INVALID because of 'https://doi.org/' prefix
```

**Comment by labarba** [comment]
@whedon invite @stats-tgeorge as editor

**Comment by whedon** [comment]
@stats-tgeorge has been invited to edit this submission.

**Comment by stats-tgeorge** [comment]
@whedon assign me

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by stats-tgeorge** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @stats-tgeorge

**Comment by stats-tgeorge** [comment]
Hello @TrevorFrench. Looks like you have included the necessary pieces for submission and your paper is in the JOSE scope. I will start to identify reviewers!

**Comment by stats-tgeorge** [comment]
Hello, @atrisovic, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by atrisovic** [comment]
Hey @stats-tgeorge I'm afraid I have too many things on my todo list now and I wouldn't want to cause a delay here :/

**Comment by stats-tgeorge** [comment]
Hello, @sestelo, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by sestelo** [comment]
sorry @stats-tgeorge but I'm currently with a lot of work and I can't take anything else! :(

**Comment by stats-tgeorge** [comment]
Hello, @nickbearman, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by nhejazi** [comment]
@stats-tgeorge, this seems like a very thoughtfully written book and I would normally be eager to provide some input; however, I am currently facing a host of approaching deadlines and will not be able to provide a timely review -- my apologies for this.

**Comment by nickbearman** [comment]
Sorry @stats-tgeorge I'm not going to have time to review this currently

**Comment by neuroimaginador** [comment]
I'm so sorry, but at this moment I will not be able to review this
submission (although it seems quite interesting) due to other duties.

**Comment by stats-tgeorge** [comment]
Hello, @SantosRAC, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by stats-tgeorge** [comment]
Hello, @Stomsing1, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by stats-tgeorge** [comment]
Hello, @tomsing1, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by tomsing1** [comment]
@stats-tgeorge Happy to review!

**Comment by stats-tgeorge** [comment]
@tomsing1  Wonderful thank you. I'm still looking for at least 1 more reviewer before the whole process gets started. Please read through the reviewer documentation (if you are not familiar) when you ave some time. Available [here](https://openjournals.readthedocs.io/en/jose/reviewer_guidelines.html).

**Comment by stats-tgeorge** [comment]
Hello, @corybrunson, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by stats-tgeorge** [comment]
Hello, @njtierney, you signed up to review for JOSE. Would you be willing to review for a submission titled "R for Data Analysis: An open-source resource for teaching and learning analytics with R”? Let me know if you're available and willing. Thank you!

**Comment by corybrunson** [comment]
Hi @stats-tgeorge, i may be able to, though it may take longer than a typical software package review. What is the expected or preferred turnaround for a book-length resource such as this?

**Comment by njtierney** [comment]
Hi @stats-tgeorge - I would be happy to however I am on leave for the next 2 weeks, back on the 29th March - I'll be free from the 29th March until April 27th to review.

**Comment by stats-tgeorge** [comment]
@corybrunson around a month? We don't review a lot of resources similar to this. Does that sound like ti would work for you?

**Comment by corybrunson** [comment]
@stats-tgeorge i should be able to. At least i can give you plenty of notice if it'll be any longer.

**Comment by stats-tgeorge** [comment]
@njtierney  thank you for the response. I am going to get the review moving along but I will reach out if we need another in a few weeks (it it doesn't progress for some reason, things happen).

**Comment by stats-tgeorge** [comment]
@whedon assign @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is now a reviewer

**Comment by stats-tgeorge** [comment]
@whedon add @corybrunson as reviewer

**Comment by whedon** [comment]
OK, @corybrunson is now a reviewer

**Comment by stats-tgeorge** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/202.

**Comment by tomsing1** [comment]
@stats-tgeorge Sorry, would you mind reissuing the reviewer invitation URL? It seems to have expired. Thank you!

**Comment by stats-tgeorge** [comment]
@whedon add @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is now a reviewer

**Comment by stats-tgeorge** [comment]
@tomsing1 Let me know if that didn't work. Thank you again for your time!

**Comment by labarba** [comment]
Interesting... I notice that our bot added @tomsing1 twice to the list of reviewers at the top of this thread.

<img width="380" alt="Screen Shot 2023-04-02 at 3 24 29 PM" src="https://user-images.githubusercontent.com/4800109/229374465-c12891ea-0650-40a1-abb3-3dbc46755dad.png">

I didn't know that could happen! As the reviewer list carries over to the published paper, I'll try removing the re-inviting... 

@stats-tgeorge We also have a command `@whedon re-invite … as reviewer` for when the invitation expires.

**Comment by labarba** [comment]
@whedon remove @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is no longer a reviewer

**Comment by labarba** [comment]
@whedon add @tomsing1 as reviewer

**Comment by whedon** [comment]
OK, @tomsing1 is now a reviewer
