### ISSUE TITLE
[PRE REVIEW]: Manim Slides: A Python package for presenting Manim content anywhere

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#199]
**Submitting author:** @jeertmans (<a href="http://orcid.org/0000-0002-5579-5360">Jérome Eertmans</a>)
**Repository:** <a href="https://github.com/jeertmans/manim-slides" target ="_blank">https://github.com/jeertmans/manim-slides</a>
**Version:** v4.9.2
**Editor:** @magsol
**Reviewers:** @behollister, @bryanwweber
**Managing EiC:** Jordan Gorzalski

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9/status.svg)](https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9"><img src="https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9/status.svg)](https://jose.theoj.org/papers/6cea80a2e0854602e095da04908cfdb9)
```

**Author instructions**

Thanks for submitting your paper to JOSE @jeertmans. **Currently, there isn't an JOSE editor assigned** to your paper.

@jeertmans if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 786

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.13 s (389.7 files/s, 37176.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          15            552            223           2143
Markdown                        18            274              0            656
YAML                            13             60             57            469
HTML                             1             68              5            218
TOML                             1             11              6             90
TeX                              1              5              0             48
DOS Batch                        1              8              1             26
Bourne Shell                     1             10              0             11
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            52            992            299           3670
-------------------------------------------------------------------------------


Statistical information for the repository 'd346620dc5f778fd1c193234' was
gathered on 2023/03/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Fairlight8                       1            10              2            0.19
Federico Galatolo               22           505             35            8.66
Jérome Eertmans                 99          3941           1257           83.41
Linus Heck                       6            75             43            1.89
MikeGillotti                     1            15              4            0.30
Tomasz Dądela                    1            15            192            3.32
Wu Tingfeng                      1            53             34            1.40
Wucheng Zhang                    1             3              0            0.05
pre-commit-ci[bot]               4            24             22            0.74
yang-fighter                     1             1              1            0.03

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Fairlight8                   10          100.0          0.2               20.00
Federico Galatolo           112           22.2          1.1                0.00
Jérome Eertmans            2723           69.1          4.3                5.29
Linus Heck                   16           21.3         20.8               12.50
MikeGillotti                 11           73.3          4.4                0.00
Tomasz Dądela                13           86.7          3.1               23.08
Wu Tingfeng                  21           39.6          4.7               14.29
pre-commit-ci[bot]           11           45.8          4.4                0.00
yang-fighter                  1          100.0          2.0                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00199/jose.00199/10.21105.jose.00199.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00199/jose.00199/10.21105.jose.00199.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@whedon invite @magsol as editor

**Comment by whedon** [comment]
@magsol has been invited to edit this submission.

**Comment by labarba** [comment]
@magsol Have a look at this submission 👀 
https://eertmans.be/manim-slides/

It makes slides using the `manim` Python package. Cool!

**Comment by magsol** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by magsol** [comment]
@whedon add @behollister as reviewer

**Comment by whedon** [comment]
OK, @behollister is now a reviewer

**Comment by magsol** [comment]
@whedon add @bryanwweber as reviewer

**Comment by whedon** [comment]
OK, @bryanwweber is now a reviewer

**Comment by magsol** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/206.
