### ISSUE TITLE
[PRE REVIEW]: CFD Python: the 12 steps to Navier-Stokes equations

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#20]
**Submitting author:** @labarba (<a href="http://orcid.org/0000-0001-5812-2711">Lorena A. Barba</a>)
**Repository:** <a href="https://github.com/barbagroup/CFDPython" target ="_blank">https://github.com/barbagroup/CFDPython</a>
**Version:** v1.0
**Editor:** @kyleniemeyer
**Reviewers:** @nicoguaro, @petebachant

**Author instructions**

Thanks for submitting your paper to JOSE @labarba. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@labarba if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00020/jose.00020/10.21105.jose.00020.pdf)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00020/jose.00020/10.21105.jose.00020.pdf)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00020/jose.00020/10.21105.jose.00020.pdf)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00020/jose.00020/10.21105.jose.00020.pdf)

**Comment by labarba** [comment]
Maybe one of these gentle humans would like to volunteer a review?
@petebachant @nicoguaro @leouieda @wigging @franktoffel @AlexS12
(picked among CFD Python stargazers on GitHub)

**Comment by nicoguaro** [comment]
@labarba, I could do it.

**Comment by petebachant** [comment]
I'd be willing to review as well.

**Comment by kyleniemeyer** [comment]
Great, thanks @nicoguaro and @petebachant!

**Comment by kyleniemeyer** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @petebachant as reviewer

**Comment by whedon** [comment]
OK, @petebachant is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/21. Feel free to close this issue now!

**Comment by kyleniemeyer** [comment]
ok @labarba @nicoguaro @petebachant the review will take place over in #21
