### ISSUE TITLE
[PRE REVIEW]: Planet_LB: Lattice-Boltzmann solutions for planetary geodynamics problems

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#201]
**Submitting author:** @thecraigoneill (<a href="http://orcid.org/0000-0002-6034-1881">Craig O&#39;Neill</a>)
**Repository:** <a href="https://github.com/thecraigoneill/planet_LB" target ="_blank">https://github.com/thecraigoneill/planet_LB</a>
**Version:** v1.0.0
**Editor:** @nicoguaro
**Reviewers:** @brmather, @jfpa
**Managing EiC:** Lorena Barba

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode".

## Status

[![status](https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136/status.svg)](https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136"><img src="https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136/status.svg)](https://jose.theoj.org/papers/483df4a80d8cb5d9e3fd5a6d9d7fa136)
```

**Author instructions**

Thanks for submitting your paper to JOSE @thecraigoneill. **Currently, there isn't an JOSE editor assigned** to your paper.

@thecraigoneill if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (183.1 files/s, 44699.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            121             94            568
Jupyter Notebook                 5              0           1704            508
Markdown                         2             33              0             56
TeX                              1              4              0             47
YAML                             1              6              4             29
-------------------------------------------------------------------------------
SUM:                            13            164           1802           1208
-------------------------------------------------------------------------------


Statistical information for the repository '1981966cc44a824318e9cbaa' was
gathered on 2023/03/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Craig O'Neill                    6            70             14           10.26
thecraigoneill                   3           731              4           89.74

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Craig O'Neill                56           80.0          0.6               10.71
thecraigoneill              727           99.5          4.6               12.10
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00201/jose.00201/10.21105.jose.00201.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00201/jose.00201/10.21105.jose.00201.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-1-4471-7423-3 is OK
- 10.1016/j.pepi.2007.06.009 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@thecraigoneill – your paper has a lot of issues with references, and also the figure needs size adjustment. Please make this fixes, and when done you can run the command `@whedon generate pdf` alone in a comment here.

To make intermediate tests of the paper compilation, you can use https://whedon.theoj.org

**Comment by thecraigoneill** [comment]
Potential reviewer is https://github.com/brmather 
Ben has published with JOSS and is familiar with the process, and this code.
C

**Comment by thecraigoneill** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00201/jose.00201/10.21105.jose.00201.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00201/jose.00201/10.21105.jose.00201.pdf) :page_facing_up: :point_left:

**Comment by thecraigoneill** [comment]
@labarba formatting issues are fixed.

**Comment by nicoguaro** [comment]
@labarba, yes, I am willing to edit this submission.

**Comment by labarba** [comment]
@whedon assign @nicoguaro as editor

**Comment by nicoguaro** [comment]
@brmather, @lheagy, would you be interested in reviewing this submission for JOSE? It concerns a _Python package for 2D geodynamics using a lattice Boltzmann approach_.

**Comment by lheagy** [comment]
Thanks for reaching out! I am sorry, but I don't have time at the moment to take on this review

**Comment by brmather** [comment]
Sure, @nicoguaro I would be happy to provide a review.

**Comment by nicoguaro** [comment]
@whedon add @brmather as reviewer

**Comment by whedon** [comment]
OK, @brmather is now a reviewer

**Comment by nicoguaro** [comment]
@jfpa, would you be interested in reviewing this submission for JOSE? It concerns a _Python package for 2D geodynamics using a lattice Boltzmann approach_.

**Comment by jfpa** [comment]
yes, please count me in.

**Comment by nicoguaro** [comment]
@whedon add @jfpa as reviewer

**Comment by whedon** [comment]
OK, @jfpa is now a reviewer

**Comment by nicoguaro** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/205.
