### ISSUE TITLE
[PRE REVIEW]: ChooChoo the Checklist tool

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#203]
**Submitting author:** @lucydot (<a href="http://orcid.org/0000-0002-2992-9871">Lucy Whalley</a>)
**Repository:** https://github.com/lucydot/ChooChoo
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @ttimbers
**Reviewers:** @LittleAprilFool, @ggeorg02
**Managing EiC:** Jordan Gorzalski

 

## Status

[![status](https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5/status.svg)](https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5"><img src="https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5/status.svg)](https://jose.theoj.org/papers/e4199f0adb4eaf3e28d5976b25612fb5)
```

**Author instructions**

Thanks for submitting your paper to JOSE @lucydot. **Currently, there isn't an JOSE editor assigned** to your paper.

@lucydot if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/3159450.3159548 is OK
- 10.1145/3159450.3159548 is OK
- 10.14786/FLR.V2I1.24 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1186/s12909-022-03632-z is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 963

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (670.3 files/s, 47045.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        24            465              0            886
Python                          12            249            162            676
YAML                             4             96              5            408
TeX                              1              4              0             55
JavaScript                       1              0              0              6
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                            43            814            167           2037
-------------------------------------------------------------------------------


Statistical information for the repository '82ca687c05d8d1f8a6efbeb4' was
gathered on 2023/03/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lucy Whalley                   248          2536           1321           99.87
choochoo-bot                     1             4              1            0.13

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lucy Whalley               1090           43.0         11.2                7.98
choochoo-bot                  3           75.0         10.4                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00203/jose.00203/10.21105.jose.00203.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00203/jose.00203/10.21105.jose.00203.pdf) :page_facing_up: :point_left:

**Comment by lucydot** [comment]
@whedon list commands

**Comment by lucydot** [comment]
@whedon commands

**Comment by lucydot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00203/jose.00203/10.21105.jose.00203.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00203/jose.00203/10.21105.jose.00203.pdf) :page_facing_up: :point_left:

**Comment by lucydot** [comment]
Hello! A note on reviewers...as this is a domain agnostic tool I think the possible reviewer list is quite broad. Familiarity with Github, Github actions and Python would certainly be useful - and reviewers who uses Github for hosting teaching content might be best as they might have a better appreciation for the project motivation. Looking at the spreadsheet - possible reviewers might be:  lechten gcdeshpande mattforshaw stefania11

**Comment by labarba** [comment]
@diazrenata Have a look at this submission 👀 
Would you be available to edit this? I realize you're more of an R person than Python, but the functionality here is mostly around GitHub... let me know what you think (feel free to ping me on Slack).

**Comment by ppxasjsm** [comment]
I could potentially act as a reviewer for this, if it is at all helpful!

**Comment by labarba** [comment]
Thank you, @ppxasjsm — that is most helpful. `@diazrenata` stepped down as editor, and so we need to find an alternative handling editor. Stay tuned.

**Comment by labarba** [comment]
@ShanEllis — would you accept handling this submission as editor? (We have one volunteer to review, yay!)

**Comment by lucydot** [comment]
Hello, just giving this a little ping @labarba @ShanEllis let me know if there is anything I can help with to move things along

**Comment by ttimbers** [comment]
@labarba - I have just returned from leave and would be happy to step up as editor for this (I have a passion for checklists...)

**Comment by labarba** [comment]
Awesome, thank you! FYI, JOSE has been upgraded to the latest more powerful bot: `@editorialbot` — I myself haven't had a chance to try it yet, so here goes...

**Comment by labarba** [comment]
@editorialbot assign @ttimbers as editor

**Comment by labarba** [comment]
@ppxasjsm – You had volunteered to contribute a review for JOSE back in May. Are you still able to do it? We've assigned an editor who will look for a second reviewer before starting the Review issue.

**Comment by ttimbers** [comment]
@whedon assign @LittleAprilFool as reviewer

**Comment by ttimbers** [comment]
@editorialbot assign @LittleAprilFool as reviewer

**Comment by ttimbers** [comment]
@editorialbot commands

**Comment by ttimbers** [comment]
@editorialbot add @LittleAprilFool as reviewer

**Comment by lucydot** [comment]
Hello @ttimbers @LittleAprilFool @ppxasjsm

Awkward timing but I am on Annual Leave until the 8th of August (without any internet)! 

Hope that works ok with the review process. I will check in on this ASAP after getting back from camping.

Best,

Lucy

**Comment by ttimbers** [comment]
@editorialbot add @ggeorg02 as reviewer

**Comment by ttimbers** [comment]
@editorialbot start review

**Comment by ppxasjsm** [comment]
Sorry I missed this, not sure why I didn't get an email notification with me mentioned specifically. I can still review, but I see you have now already found two willing people!
