### ISSUE TITLE
[PRE REVIEW]: An R Companion for Introduction to Data Mining

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#212]
**Submitting author:** @mhahsler (<a href="http://orcid.org/0000-0003-2716-1405">Michael Hahsler</a>)
**Repository:** https://github.com/mhahsler/Introduction_to_Data_Mining_R_Examples
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @stats-tgeorge
**Reviewers:** @hughshanahan, @rudeboybert
**Managing EiC:** Lorena Barba

## Status

[![status](https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07/status.svg)](https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07"><img src="https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07/status.svg)](https://jose.theoj.org/papers/1c21e289cb9c887b65cb58740f947f07)
```

**Author instructions**

Thanks for submitting your paper to JOSE @mhahsler. **Currently, there isn't an JOSE editor assigned** to your paper.

@mhahsler if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". 

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01686 is OK
- 10.18637/jss.v091.i01 is OK
- 10.18637/jss.v025.i03 is OK
- 10.32614/RJ-2017-047 is OK
- 10.18637/jss.v028.i05 is OK

MISSING DOIs

- 10.1002/0471687545.ch1 may be a valid DOI for title: Introduction to Data Mining

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 532

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.20 s (56.9 files/s, 22896.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            19            695             45          11519
JavaScript                      17            852           1220           6172
Rmd                              9           1116           2249           1284
CSS                             10             96             81            856
TeX                              3             81              0            665
SVG                              1              0              0            288
Markdown                         3             29              0             97
YAML                             3              1              0             19
R                                2              1              3              5
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            68           2871           3598          20906
-------------------------------------------------------------------------------


Statistical information for the repository '4279c59c22f532017b9213c9' was
gathered on 2023/06/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Michael Hahsler                  7         10163           1919          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Hahsler            8244           81.1          1.7               50.01
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00212/jose.00212/10.21105.jose.00212.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00212/jose.00212/10.21105.jose.00212.pdf) :page_facing_up: :point_left:

**Comment by mhahsler** [comment]
Here are two reviewer suggestions from the list:
* Kelly Bodwin
* Abhinav Maurya

**Comment by xuanxu** [comment]
@editorialbot generate pdf

**Comment by xuanxu** [comment]
@editorialbot generate pdf

**Comment by xuanxu** [comment]
@editorialbot generate pdf

**Comment by xuanxu** [comment]
@editorialbot generate pdf

**Comment by mhahsler** [comment]
@editorialbot generate pdf

**Comment by mhahsler** [comment]
@editorialbot generate pdf

**Comment by mhahsler** [comment]
@xuanxu the pdf generation script seems to die when adding an image (not finding the journal logo?)

```
Error running filter /usr/local/share/openjournals/data/filters/add-images.lua:
File  not found in resource path
stack traceback:
	/usr/local/share/openjournals/data/filters/add-images.lua:4: in upvalue 'insert'
	/usr/local/share/openjournals/data/filters/add-images.lua:9: in function 'Meta'
```

I am not sure how to fix this.

**Comment by xuanxu** [comment]
Yes, is something we are looking into, we've updated the PDF compilation step and this is probably some misconfiguration in our part.

**Comment by xuanxu** [comment]
@editorialbot generate pdf

let's try again

**Comment by mhahsler** [comment]
@whedon commands

**Comment by mhahsler** [comment]
@editorialbot commands

**Comment by mhahsler** [comment]
@editorialbot list editors

**Comment by mhahsler** [comment]
@labarba Hi. There was a technical issue with creating the pdf. The issue was resolved. What are the next steps for the review process? Best regards, Michael

**Comment by stats-tgeorge** [comment]
@mhahsler I apologize for the delay. Since it has been many month, can you confirm you would still like this reviewed?

**Comment by mhahsler** [comment]
@stats-tgeorge Thank you for your reply. It has been a while, but we are still teaching the course and I am still interested having the companion reviewed.

**Comment by stats-tgeorge** [comment]
@editorialbot assign @stats-tgeorge as editor

**Comment by stats-tgeorge** [comment]
@mhahsler great! To start, looking at your JOSE paper there are some missing pieces. See https://github.com/mhahsler/Introduction_to_Data_Mining_R_Examples/issues/5#issue-2071103726

**Comment by stats-tgeorge** [comment]
@editorialbot commands

**Comment by stats-tgeorge** [comment]
@editorialbot list reviewers

**Comment by stats-tgeorge** [comment]
Hello @kbodwin, Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!

**Comment by stats-tgeorge** [comment]
Hello @ahmaurya, Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!

**Comment by stats-tgeorge** [comment]
Hello @Hughshanahan, Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!

**Comment by stats-tgeorge** [comment]
Hello @rudeboybert, Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!

**Comment by stats-tgeorge** [comment]
Good morning @mhahsler , I am still working on this. I will be reaching out to potential reviewers outside of Github. Please stay tuned and thank you for being very patient!

**Comment by stats-tgeorge** [comment]
Good morning @mhahsler I have identified two reviewers! They asked for a long deadline but at least we are making progress. I will be making some updates here to create the review version.

**Comment by stats-tgeorge** [comment]
@editorialbot assign @hughshanahan as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot assign @hughshanahan as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot commands

**Comment by stats-tgeorge** [comment]
@editorialbot add @hughshanahan as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot add @rudeboybert as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot start review

**Comment by stats-tgeorge** [comment]
Hello @gvdr, you are on our list of potential reviewers for JOSE. Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!

**Comment by stats-tgeorge** [comment]
Hello @trallard, you are on our list of potential reviewers for JOSE. Michael Hahsler has submitted a data mining companion book to JOSE for other instructors to use. Would you be willing to review the submission? Your time and efforts will be greatly appreciated!
