### ISSUE TITLE
[PRE REVIEW]: An Introduction to Applied Bioinformatics: a free, open, and interactive text.

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#23]
**Submitting author:** @gregcaporaso (<a href="http://orcid.org/0000-0002-8865-1670">James Gregory Caporaso</a>)
**Repository:** <a href="https://github.com/caporaso-lab/An-Introduction-To-Applied-Bioinformatics/blob/master/paper.md" target ="_blank">https://github.com/caporaso-lab/An-Introduction-To-Applied-Bioinformatics/blob/master/paper.md</a>
**Version:** 0.1.3-dev
**Editor:** @tracykteal
**Reviewers:** @AstrobioMike

**Author instructions**

Thanks for submitting your paper to JOSE @gregcaporaso. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@gregcaporaso if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #23 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by labarba** [comment]
@tracykteal This submission is squarely on your field. Given the extent of the materials, I suggest you find three reviewers and divvy up the content for them to review. All could check installation, and so on, but could focus on just a section of the content.

**Comment by tracykteal** [comment]
@astrobiomike would you be available to review? We can divide the content into sections for the pedagogy/content, so perhaps you could pick a section to review.

**Comment by AstrobioMike** [comment]
@tracykteal 

Absolutely! Looking forward to it :) I'll post here with thoughts on specific section(s) after I get to look over things more closely

**Comment by gregcaporaso** [comment]
@tracykteal, would it be possible to get a status update on this? It looks like review hasn't started yet - is that accurate?

**Comment by labarba** [comment]
@whedon assign @AstrobioMike as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @AstrobioMike

**Comment by labarba** [comment]
@tracykteal You were looking for a second reviewer for this submission, correct? Once you identify one, use `@whedon add @username as reviewer` and _then_ start the review (that way you get two checklists in the review issue, automatically).

**Comment by gregcaporaso** [comment]
Hi @tracykteal and @labarba, has review started for this manuscript? Thanks for the update.

**Comment by tracykteal** [comment]
@AstrobioMike submitted a review via email. Sorry, I needed to trigger the start of the review, so it could be completed here. Doing that now.

**Comment by tracykteal** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/27. Feel free to close this issue now!
