### ISSUE TITLE
JOSE Review - comments on "Self-Guided Decision Support Groundwater Modelling with Python " [Documentation section]

### ISSUE THREAD

**Issue by incsanchezro** [openjournals/jose-reviews#244]
Thank you for putting effort into building up the documentation of your repository. My comments aim to enhance the collaborative aspects of the repository. I hope you find them insightful.

**Comments:**

1. The authors have articulated the need for this educational framework, targeting the environmental modellers and decision-makers as specific audiences that could benefit from its implementation. The framework's usage and installation instructions are detailed.

2. A comprehensive workflow is recommended for the written and framework documentation. This addition should clearly outline the self-learning process, including learning objectives, module prerequisites, and potential implementations. It should make it easier for users to navigate the software autonomously or for educators to integrate it into their teaching methodologies, provided they possess the necessary expertise.

3. The repository's current documentation needs specific guidelines for community involvement in the module's collaborative development. This oversight could be rectified by establishing clear pathways for third-party contributions, issue reporting, and support-seeking, fostering a more engaged and supportive community around the framework. 

4. Additionally, clarifying the project's funding sources and outlining strategies for its long-term sustainability would provide further transparency and confidence in the framework's continued evolution and support.

**Comment by rhugman** [comment]
Thank you @incsanchezro for your comprehensive review. Please see below replies and updates.

Kind regards,
-R  

# Reply to https://github.com/openjournals/jose-reviews/issues/244  

> **Comments:**
> 1. The authors have articulated the need for this educational framework, targeting the environmental modellers and decision-makers as specific audiences that could benefit from its implementation. The framework's usage and installation instructions are detailed. 

Appreciated.

> 2. A comprehensive workflow is recommended for the written and framework documentation. This addition should clearly outline the self-learning process, including learning objectives, module prerequisites, and potential implementations. It should make it easier for users to navigate the software autonomously or for educators to integrate it into their teaching methodologies, provided they possess the necessary expertise.

We appreciate the suggestion and agree in principle. We had purposefully left it open ended, as as we tend to find that most users have unique issues that result in each taking their own path. 

Nevertheless, we have added learning objectives and prerequisites in the "Contents and Instructional Design" section of the manuscript and to the README. Furthermore we have included an "example workflow" schematic outline. 

We feel that the existing "workflow" outlined in the [README](https://github.com/gmdsi/GMDSI_notebooks/tree/jose-review#organization-of-the-tutorial-notebooks) provides sufficient guidance to the self-learning process. Furthermore, each of the Notebooks has an introductory section where the learning objectives are usually outlined, along with how these are related to real-world applications.

> 3. The repository's current documentation needs specific guidelines for community involvement in the module's collaborative development. This oversight could be rectified by establishing clear pathways for third-party contributions, issue reporting, and support-seeking, fostering a more engaged and supportive community around the framework.

We have included a "Contributing" section in the README. See commit  
 https://github.com/gmdsi/GMDSI_notebooks/commit/bf5229a4884892a2b9af1e1f018ddde87e66e1d7

> 4. Additionally, clarifying the project's funding sources and outlining strategies for its long-term sustainability would provide further transparency and confidence in the framework's continued evolution and support.

Funding and support for the project is described in the Acknowledgements section of the README. See https://github.com/gmdsi/GMDSI_notebooks#acknowledgments
