### ISSUE TITLE
JOSE Review - comments on "Self-Guided Decision Support Groundwater Modelling with Python " [Pedagogy / Instructional design ]

### ISSUE THREAD

**Issue by incsanchezro** [openjournals/jose-reviews#245]
As this repository has its origins in the classroom and was guided by teaching praxis, I noticed its clarity regarding how it can be used as part of class teaching. My comments below aim to enhance the pedagogical framework, making it clearer for both students and professors. Furthermore, allowing its broader use of the repository. I hope you find them useful!

**Comments**

1. While the educational modules provide valuable information, the learning objectives across all sections need to be explicitly stated. It's recommended that the authors dedicate efforts to delineating these objectives and clearly indicating the prerequisite knowledge necessary for each module. This clarity will significantly enhance learners' ability to align their expectations with the module's demands. 

2. The framework's current presentation on decision-making within the context of environmental modelling requires clarity. The authors should further elaborate on their methodology and precisely define what is encompassed by 'decision-making' in this specialized field. Such clarification would give learners a more coherent understanding of the module's objectives and applications.

3. Furthermore, expanding the authors' pedagogical strategies regarding the support of learners through the "how to use" and "how to think" processes could further enrich the learning experience. I suggest amplification of these two elements in the written document and specific activities into the modules that provide opportunities for the acquisition of skills and knowledge.

4. The use of Notebooks as a medium for the framework is highly commendable. It presents a user-friendly interface that simplifies the learning process and makes the content more accessible. This choice effectively reduces the cognitive load, making the framework easier to follow and engage with. The notebooks are generally well-documented, with only minor typos affecting the overall quality.

**Comment by rhugman** [comment]
Thank you @incsanchezro for your insightful comments.

> As this repository has its origins in the classroom and was guided by teaching praxis, I > noticed its clarity regarding how it can be used as part of class teaching. My comments below > aim to enhance the pedagogical framework, making it clearer for both students and professors. > Furthermore, allowing its broader use of the repository. I hope you find them useful!
> 
> **Comments**
> 
> 1. While the educational modules provide valuable information, the learning objectives across > all sections need to be explicitly stated. It's recommended that the authors dedicate efforts > to delineating these objectives and clearly indicating the prerequisite knowledge necessary > for each module. This clarity will significantly enhance learners' ability to align their > expectations with the module's demands.

We appreciate the suggestion and agree in principle. See response to https://github.com/openjournals/jose-reviews/issues/244

> 2. The framework's current presentation on decision-making within the context of environmental > modelling requires clarity. The authors should further elaborate on their methodology and > precisely define what is encompassed by 'decision-making' in this specialized field. Such > clarification would give learners a more coherent understanding of the module's objectives > and applications.

We have added clarifying text to the Statement of Need section of the paper.

> 3. Furthermore, expanding the authors' pedagogical strategies regarding the support of learners > through the "how to use" and "how to think" processes could further enrich the learning > experience. I suggest amplification of these two elements in the written document and > specific activities into the modules that provide opportunities for the acquisition of skills > and knowledge.

We feel this is already accomplished organically within the Notebooks. Each of these go through the steps of "how to implement" whilst discussing the implications of the choices made, whilst demonstrating and discussing alternative approaches.

> 4. The use of Notebooks as a medium for the framework is highly commendable. It presents a > user-friendly interface that simplifies the learning process and makes the content more > accessible. This choice effectively reduces the cognitive load, making the framework easier > to follow and engage with. The notebooks are generally well-documented, with only minor typos > affecting the overall quality.

Appreciated.
