### ISSUE TITLE
JOSE Review - comments on "Self-Guided Decision Support Groundwater Modelling with Python " [JOSE paper]

### ISSUE THREAD

**Issue by incsanchezro** [openjournals/jose-reviews#246]
Your paper draft is insightful and engaging. I appreciate your effort in presenting the story behind the repository! Below, you can find some specific comments that you can use to strengthen the paper's theoretical framework and ensure further references.

**Comments**

1. The draft of the paper presents a collaborative endeavour by including a comprehensive list of authors and their affiliations. While the statement of need is both clear and compelling. I suggest a further literature review that solidifies the work's relevance and application. This would enhance the identification of the target audience and the framework's educational significance, thereby strengthening its foundation.

2. The description of the learning materials and their sequence is good. I suggest the addition of a comprehensive workflow. This workflow could outline the self-learning process, incorporating learning objectives, prerequisites for each module, and potential implementations. Such enhancements aim to provide a more robust structure for engagement and understanding among educators and learners alike.

3. Additionally, the endeavour to gather student software feedback is recognized as valuable. Yet, the methodology for capturing this feedback invites improvement to ensure rigour. Recommendations include diversifying the focus groups beyond graduate students to encompass instructors and stakeholders (target audience) and enhancing data collection methods for more effective feedback on the tool's usability.

4. The narrative of the paper effectively conveys the story of the framework's development and the authors' expertise, enriching the content with a personal touch that underscores the project's depth. The diligent citation of all archival references, complete with DOIs for papers, datasets, and software, exemplifies a rigorous adherence to academic standards. Such meticulous attention to detail further asserts the module's integrity, credibility, and invaluable role as a teaching and learning resource.

**Comment by rhugman** [comment]
> Your paper draft is insightful and engaging. I appreciate your effort in presenting the story behind the repository! Below, you can find some specific comments that you can use to strengthen the paper's theoretical framework and ensure further references.
> 
> **Comments**
> 
> 1. The draft of the paper presents a collaborative endeavour by including a comprehensive list of authors and their affiliations. While the statement of need is both clear and compelling. I suggest a further literature review that solidifies the work's relevance and application. This would enhance the identification of the target audience and the framework's educational significance, thereby strengthening its foundation.

We have included a more comprehensive literature review providing examples of real-world applications and relevance of the tools and techniques presented in the Notebooks.


> 2. The description of the learning materials and their sequence is good. I suggest the addition of a comprehensive workflow. This workflow could outline the self-learning process, incorporating learning objectives, prerequisites for each module, and potential implementations. Such enhancements aim to provide a more robust structure for engagement and understanding among educators and learners alike.

We appreciate the suggestion and agree in principle. See response to https://github.com/openjournals/jose-reviews/issues/244

> 3. Additionally, the endeavour to gather student software feedback is recognized as valuable. Yet, the methodology for capturing this feedback invites improvement to ensure rigour. Recommendations include diversifying the focus groups beyond graduate students to encompass instructors and stakeholders (target audience) and enhancing data collection methods for more effective feedback on the tool's usability.

We appreciate the feedback. We will endeavour to do so in the future.

> 4. The narrative of the paper effectively conveys the story of the framework's development and the authors' expertise, enriching the content with a personal touch that underscores the project's depth. The diligent citation of all archival references, complete with DOIs for papers, datasets, and software, exemplifies a rigorous adherence to academic standards. Such meticulous attention to detail further asserts the module's integrity, credibility, and invaluable role as a teaching and learning resource.

Appreciated.
