### ISSUE TITLE
[REVIEW]: Mikrokosmos: an educational lambda calculus interpreter

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#29]
**Submitting author:** @mroman42 (<a href="http://orcid.org/0000-0003-3158-1226">Mario Román</a>)
**Repository:** <a href="https://github.com/mroman42/mikrokosmos" target ="_blank">https://github.com/mroman42/mikrokosmos</a>
**Version:** v0.8.0
**Editor:** @RobertTalbert
**Reviewer:** @aj2duncan,  @MattForshaw
**Archive:** <a href="https://doi.org/10.5281/zenodo.1470226" target="_blank">10.5281/zenodo.1470226</a>

## Status

[![status](http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34/status.svg)](http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34"><img src="http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34/status.svg)](http://jose.theoj.org/papers/8324e9aa1019760e987673f55e335f34)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mroman42/mikrokosmos" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aj2duncan,  @MattForshaw please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @RobertTalbert know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mroman42/mikrokosmos">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.0)?
- [x] **Authorship:** Has the submitting author (@mroman42) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mroman42/mikrokosmos">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.8.0)?
- [x] **Authorship:** Has the submitting author (@mroman42) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aj2duncan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00029/jose.00029/10.21105.jose.00029.pdf)

**Comment by labarba** [comment]
OK, @RobertTalbert — I manually added a second review checklist above. We're good to go.

👋  @aj2duncan, @MattForshaw — Thank you for agreeing to review for JOSE! This is where the actin happens. Each of you has a review checklist above. Feel free to ask questions here, and to open new issues on the submission's repository, if you feel the need.

**Comment by aj2duncan** [comment]
I've had some difficulty getting the Jupyter Notebook version working on Windows. Please see [mroman42/mikrokosmos#45](https://github.com/mroman42/mikrokosmos/issues/45) Anyone else have this problem?

Command line version installs and works just fine.

**Comment by MattForshaw** [comment]
Suggesting the authors add a more prominent statement where users should seek support. https://github.com/mroman42/mikrokosmos/issues/47

**Comment by aj2duncan** [comment]
@RobertTalbert I'm not entirely sure how it works from here but I'm pretty happy that @mroman42 has satisfied the only issue I had. I really like the project and think the documentation is very good. Let me know if you need anything else from me.

**Comment by MattForshaw** [comment]
Likewise, @mroman42 addressed my comment very quickly. I am very happy for this to proceed.

**Comment by labarba** [comment]
Do I take it that both reviewers are recommending publication, at this point?

**Comment by aj2duncan** [comment]
Hi @labarba - same here. Thanks.

**Comment by labarba** [comment]
OK. 

👋 @RobertTalbert --- You can give the paper an editorial check now, suggest any improvements you'd like to see, and then let me know you're ready to accept.

**Comment by RobertTalbert** [comment]
Will do, probably early next week. (Drowning in Assistant Chair duties right now - remind me why I signed up to do that?)

**Comment by RobertTalbert** [comment]
@labarba I've had a look at the paper and have no other suggestions, so I think this one is good to go.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00029/jose.00029/10.21105.jose.00029.pdf)

**Comment by labarba** [comment]
@mroman42 — could you tweak the paper as follows?

1. paragraph 3: "Following (Barendregt, 1984)" ... if the reference is part of the sentence, it should be formatted as: "Following Barendregt (1984)"

2. "as described in (De Bruijn, 192)" ... here, you can remove the "as described in" and simply put the reference at the end of the sentence. It will make it more readable, given the large distance you have between subject and verb ("works").

3. "standard algorithm from (Hindley & Seldin, 2008)" ... same as 1.

4. "see (Sorensen & Urzyczyn, 2006)" ... same.

5. "textbooks such as (Wadler, 2015) or (Girard, Taylor, & Lafont, 1989)" ... same

6. page 2: "installation and usage instructions ... are also described" ... change verb to "given" or "provided"?

7. "described in (Wadler, 2015)" ... "depicted in (Wadler, 2007)" ... "justified in (Danierlson, Hughes, Jansson, & Gibbons, 2006)" ... same as 1. 

8. Find other examples in page 3.

**Comment by labarba** [comment]
In summary, when the citation is part of the sentence, then use: Author (year). If the citation is not part of the sentence, then it should appear in parenthesis.
E.g.
* "We take inspiration from Smith et al. (2006) to ... "
* "The code implements Theory 1 (Jones 2012) and Theory 2 (Roberts 2014) to obtain ... "

For the syntax to obtain brackets in the right places, see: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

**Comment by mroman42** [comment]
Thank you very much. Commit mroman42/mikrokosmos@a5e9c879cfa9b35fe99c786bc61fad3bf8775b56 addresses these corrections and changes some propositions to make the name of the author appear as part of the sentence. Please let me know if any other change is required.

**Comment by labarba** [comment]
@whedoon generate pdf

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00029/jose.00029/10.21105.jose.00029.pdf)

**Comment by labarba** [comment]
@mroman42 — apologies for the delay (I just came back this weekend from a three-talk tour and I was slammed).

We're ready to publish your submission, once you deposit an archive on Zenodo (or a similar service: Figshare, Dryad, etc.). Once you get a DOI for the archive, give it to us here, and we'll publish your JOSE paper!

**Comment by mroman42** [comment]
If I have done everything correctly (please let me know if something else is needed) the DOI is 10.5281/zenodo.1470226 (https://zenodo.org/record/1470226).

@labarba @RobertTalbert @aj2duncan @MattForshaw Thank you very much for all the feedback; it has been very useful for the project.

**Comment by labarba** [comment]
Almost ... the author list on the Zenodo archive does not match the author list of the paper. On Zenodo, we have "Mario Román; Pedro A. García-Sánchez" ... on the JOSE paper, just Mario Román. You may need to manually change the metadata in the Zenodo entry.

**Comment by mroman42** [comment]
Thank you; I have manually changed the metadata. https://zenodo.org/record/1470226

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.1470226 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1470226" target="_blank">10.5281/zenodo.1470226</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/3

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/3, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/4
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00029](https://doi.org/10.21105/jose.00029)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00029/status.svg)](https://doi.org/10.21105/jose.00029)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00029">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00029/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00029/status.svg
   :target: https://doi.org/10.21105/jose.00029
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00029/status.svg)](https://doi.org/10.21105/jose.00029)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future.
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3ODA=

**Comment by labarba** [comment]
This paper is now published in JOSE !!!

@aj2duncan, @MattForshaw — Thank you for your review and being a part in this adventure in new publishing!

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
