### ISSUE TITLE
[PRE REVIEW]: ThermoState: A State manager for Thermodynamics Courses

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#30]
**Submitting author:** @bryanwweber (<a href="http://orcid.org/0000-0003-0815-9270">Bryan W. Weber</a>)
**Repository:** <a href="https://github.com/bryanwweber/thermostate" target ="_blank">https://github.com/bryanwweber/thermostate</a>
**Version:** v0.4.1
**Editor:** @kyleniemeyer
**Reviewers:** @william-pfalzgraff, @scls19fr

**Author instructions**

Thanks for submitting your paper to JOSE @bryanwweber. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@bryanwweber if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00030/jose.00030/10.21105.jose.00030.pdf)

**Comment by bryanwweber** [comment]
From the list of reviewers, I'd suggest @william-pfalzgraff

**Comment by kyleniemeyer** [comment]
Hi @william-pfalzgraff, would you be willing to serve as one of the reviewers for this submission?

**Comment by william-pfalzgraff** [comment]
Sure, I would be willing to review this.

**Comment by kyleniemeyer** [comment]
Thanks @william-pfalzgraff! @scls19fr has also agreed via email to review. I will add you both and get this started.

**Comment by kyleniemeyer** [comment]
@whedon add @william-pfalzgraff as reviewer

**Comment by whedon** [comment]
OK, @william-pfalzgraff is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @scls19fr as reviewer

**Comment by whedon** [comment]
OK, @scls19fr is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/33. Feel free to close this issue now!
