### ISSUE TITLE
[PRE REVIEW]: nbgrader: A Tool for Creating and Grading Assignments in the Jupyter Notebook

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#31]
**Submitting author:** @jhamrick (<a href="http://orcid.org/0000-0002-3860-0429">Jessica B. Hamrick</a>)
**Repository:** <a href="https://github.com/jupyter/nbgrader" target ="_blank">https://github.com/jupyter/nbgrader</a>
**Version:** v0.5.4
**Editor:** @labarba
**Reviewers:** @MattForshaw

**Author instructions**

Thanks for submitting your paper to JOSE @jhamrick. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jhamrick if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00031/jose.00031/10.21105.jose.00031.pdf)

**Comment by labarba** [comment]
@whedon assign @dsblank as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dsblank

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/32. Feel free to close this issue now!

**Comment by dsblank** [comment]
(I am listed as an author; is that still ok?)

**Comment by labarba** [comment]
Hmm ... that sounds like a COI.

**Comment by labarba** [comment]
Jessica had suggested you as a reviewer on an email a while back, and I didn't check the author list!

**Comment by MattForshaw** [comment]
Hi @labarba, I'm happy to review if that would be helpful.

**Comment by labarba** [comment]
We are going to need another reviewer, who is not listed as author. Gah.
Can you suggest anyone?

**Comment by labarba** [comment]
Thanks @MattForshaw! You're familiar with nbgrader already? Can you briefly tell me your background to review this?

**Comment by jhamrick** [comment]
Sorry for the confusion, I suggested @dsblank before we had actually finalized the author list so yeah I would definitely think that is now a COI.

Thanks for volunteering @MattForshaw !

**Comment by MattForshaw** [comment]
> Thanks @MattForshaw! You're familiar with nbgrader already? Can you briefly tell me your background to review this?

No existing familiarity with nbgrader, but plenty of experience using notebooks as a data science educator, so I hope that would be something useful I could bring to a review.

**Comment by labarba** [comment]
@MattForshaw : Did you have another look, and are confident you want to do this review?

**Comment by MattForshaw** [comment]
@labarba Very happy to take this on. 👍

**Comment by labarba** [comment]
You're good to go! The review will occur at https://github.com/openjournals/jose-reviews/issues/32 and I will now close this issue. Thanks!
