### ISSUE TITLE
[REVIEW]: nbgrader: A Tool for Creating and Grading Assignments in the Jupyter Notebook

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#32]
**Submitting author:** @jhamrick (<a href="http://orcid.org/0000-0002-3860-0429">Jessica B. Hamrick</a>)
**Repository:** <a href="https://github.com/jupyter/nbgrader" target ="_blank">https://github.com/jupyter/nbgrader</a>
**Version:** v0.5.4
**Editor:** @labarba
**Reviewers:** @MattForshaw, @jedbrown
**Archive:** <a href="https://doi.org/10.5281/zenodo.2532780" target="_blank">10.5281/zenodo.2532780</a>

## Status

[![status](http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29/status.svg)](http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29"><img src="http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29/status.svg)](http://jose.theoj.org/papers/d86e078cd3990138cc6e630331410d29)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jupyter/nbgrader" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@MattForshaw, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jupyter/nbgrader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.4)?
- [x] **Authorship:** Has the submitting author (@jhamrick) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jupyter/nbgrader">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.5.4)?
- [x] **Authorship:** Has the submitting author (@jhamrick) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dsblank it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00032/jose.00032/10.21105.jose.00032.pdf)

**Comment by labarba** [comment]
👋 @dsblank — Thanks for agreeing to review! Here is where the action happens. You have a review checklist above: feel free to open issues, as needed, in the submission repository, mentioning them here for a link-back. Our [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines) explain what to do, but you can also ask questions here and I'll be glad to help.

**Comment by dsblank** [comment]
Unfortunately I cannot review this paper as I am an author. But please add me to the list of willing reviewers!

**Comment by labarba** [comment]
@jedbrown — Would you be able to contribute a review for the `nbgrader` package? I think you use it already, which should make the review go smoothly…

**Comment by jedbrown** [comment]
I can review.

**Comment by labarba** [comment]
@whedon add @jedbrown as reviewer

**Comment by whedon** [comment]
OK, @jedbrown is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
Can't start a review when the review has already started

**Comment by labarba** [comment]
Oops. thought we were in the Pre-Review issue, but no!
I will manually add a review checklist for @jedbrown now.

**Comment by labarba** [comment]
Hi @MattForshaw, @jedbrown — 👋 
Wondering here what your progress might be with this review for JOSE. Thanks!

**Comment by jedbrown** [comment]
ETA end of this week.

**Comment by labarba** [comment]
@MattForshaw — We've not heard from you about an ETA for this review, but I see you have checked off several items on the review list. Could you update us? Many thanks!

**Comment by MattForshaw** [comment]
Hi @labarba, I've set aside two hours tonight to finish the rest of the checklist for you. Hope this is okay.

**Comment by MattForshaw** [comment]
Hi @labarba, I am very happy to say nbgrader has passed with flying covers. An impressive submission.

**Comment by jedbrown** [comment]
Is there documentation of the branching scheme? The branch `0.5.x` is neither a subset nor superset of `master`. Most branching schemes would merge one way or the other. Also, the tags are "lightweight" as opposed to "annotated" so `git describe` fails without the `--tags` option. Also, the paper is build from `master` which is not a descendant of `v0.5.4`.

I filed a couple issues relating to testing. They are not mandatory to address at this time, but I'd like authors to have a chance to respond.

Some references need capitalization help (see PR).

**Comment by jhamrick** [comment]
Hi Jed and Matt, thanks for the review! Just wanted to send a quick note to
say I am a bit overwhelmed with other stuff at the moment, but will try to
address your PRs soon. (Thanks @willinc and @dsblank for handling some of
this already)

The branching scheme is based on the one IPython and I believe some of the
other Jupyter projects use, which is to create release branches and
backport PRs onto them from master. For example, after 0.5.0 was released,
we start developing stuff on master for the 0.6.0 release including major
backward incompatible changes. But occasionally there are bug fixes that
warrant another release sooner. Thus we backport the smaller bugfix changes
to 0.5.x to create intermediate releases 0.5.1, 0.5.2, etc.

**Comment by jedbrown** [comment]
Okay, fair enough regarding branches [^1]. I'm more familiar with JOSS, but presume JOSE is similar in that upon acceptance, you would tag a release of the post-review version including the paper sources and archive that to Zenodo. If that's the case and you wish to review the 0.5.x branch (as listed above), I think it would be appropriate to move the paper into the 0.5.x branch so that it will be part of the archive.

IPython uses annotated tags and I would recommend it for new nbgrader tags.

[^1]: I usually branch from the maintenance branch if I'm doing a bug fix, and always merge into 'master', thus avoiding need for a cherry-picked backport. A cosmetic `git merge --strategy=ours 0.5.x` would tie up the graph and make `git describe` more sensible. Anyway, this is wildly tangential.

**Comment by jhamrick** [comment]
I've created a new release (0.5.5) with the nbgrader paper on the 0.5.x branch, so that there is a release that corresponds with the paper being reviewd. See: https://github.com/jupyter/nbgrader/pull/1050

I'll keep that branch open until the review here is complete, in case there's any last changes that need to go into it. Thanks for all the suggestions!

**Comment by labarba** [comment]
I see only a couple of unchecked item in the review checklist. Are there more change requests pending?

**Comment by jhamrick** [comment]
I think I have managed to address all the comments at this point---unless
there  is anything else on @jedbrown 's end the only thing remaining is for
me to make the 0.5.5 release and update the version here to be 0.5.5. But I
would just like to hear from him first before I do that in case there's
anything else that needs to go in!

**Comment by jedbrown** [comment]
@whedon generated pdf from branch 0.5.x

**Comment by jedbrown** [comment]
@whedon generate pdf from branch 0.5.x

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch 0.5.x. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00032/jose.00032/10.21105.jose.00032.pdf)

**Comment by jedbrown** [comment]
Looks good to me. Looks like the housekeeping mainly landed in 'master', but it wasn't essential to the paper anyway. My understanding is that you will tag `v0.5.5` on branch '0.5.x' upon acceptance (prior to archival on Zenodo). Regarding authorship, I assume that any listed authors that have not authored commits in the repository have made other significant contributions to the project and that authors of a modest number of commits (such as Auberon Lopez, Lucas Kushner, and Ella Chao) are more appropriate to recognize collectively under Project Jupyter. (I checked the box under this assumption; the core team is certainly among the authors listed for the paper.)

My last nit would be to check capitalization of "notebook" for consistency. (The Jupyter4Edu consensus was that "Jupyter Notebook" refers to the software while "Jupyter notebook" is a notebook.)

**Comment by jhamrick** [comment]
Yes, I just got back from the holidays and will fix the capitalization
tonight and make the 0.5.5 release tonight!

**Comment by jhamrick** [comment]
> Regarding authorship, I assume that any listed authors that have not authored commits in the repository have made other significant contributions to the project and that authors of a modest number of commits (such as Auberon Lopez, Lucas Kushner, and Ella Chao) are more appropriate to recognize collectively under Project Jupyter. 

Yes. In determining authorship I reached out to everyone who had made commits to the project and asked who wanted to be included as an author, following the process outlined here: https://github.com/jupyter/governance/blob/master/papers.md#process-for-journal-of-open-source-software-joss

See https://github.com/jupyter/nbgrader/pull/973 for all the discussion on author contributions and the writing of the paper itself.

> My last nit would be to check capitalization of "notebook" for consistency. (The Jupyter4Edu consensus was that "Jupyter Notebook" refers to the software while "Jupyter notebook" is a notebook.)

See: https://github.com/jupyter/nbgrader/pull/1057

**Comment by jedbrown** [comment]
Fantastic process! Thanks.

**Comment by labarba** [comment]
OK! Since we're ready to publish, would you do the merging kung fu that you have planned, then make a Zenodo deposit of the whole repo, and post the DOI here?

**Comment by jhamrick** [comment]
Done! Here is the DOI from zenodo: 10.5281/zenodo.2532780

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2532780 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2532780" target="_blank">10.5281/zenodo.2532780</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/20

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/20, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/21
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00032](https://doi.org/10.21105/jose.00032)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, everyone! 
This iconic JOSE paper is now published.

Huge thanks to @MattForshaw and @jedbrown for their review:
https://twitter.com/LorenaABarba/status/1082023133681463296

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00032/status.svg)](https://doi.org/10.21105/jose.00032)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00032">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00032/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00032/status.svg
   :target: https://doi.org/10.21105/jose.00032
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00032/status.svg)](https://doi.org/10.21105/jose.00032)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3ODA=

**Comment by jhamrick** [comment]
Fantastic, thanks so much @labarba @jedbrown and @MattForshaw !!!

**Comment by willingc** [comment]
Thanks everyone for getting this done.

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
