### ISSUE TITLE
[REVIEW]: Org-Coursepack

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#34]
**Submitting author:** @joonro (<a href="http://orcid.org/0000-0002-5895-163X">Joon Ro</a>)
**Repository:** <a href="https://github.com/joonro/Org-Coursepack" target ="_blank">https://github.com/joonro/Org-Coursepack</a>
**Version:** v1.2.0
**Editor:** @csev
**Reviewer:** @pschloss, @gregcaporaso
**Archive:** <a href="https://doi.org/10.5281/zenodo.2539667" target="_blank">10.5281/zenodo.2539667</a>

## Status

[![status](http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c/status.svg)](http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c"><img src="http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c/status.svg)](http://jose.theoj.org/papers/b79c2f06fe0c85c5389086bec9b8287c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/joonro/Org-Coursepack" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@pschloss & @gregcaporaso, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @csev know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/joonro/Org-Coursepack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.2.0
- [x] **Authorship:** Has the submitting author (@joonro) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/joonro/Org-Coursepack">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.2.0
- [x] **Authorship:** Has the submitting author (@joonro) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @pschloss, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00034/jose.00034/10.21105.jose.00034.pdf)

**Comment by labarba** [comment]
@pschloss, @gregcaporaso — Thank you for agreeing to review this submission for JOSE. We're so grateful for your volunteer efforts! This is where the action happens. You will work through the checklist above, and ask questions here as needed. You may also open issues in the submission's repository, and post a link here.

**Comment by pschloss** [comment]
The manuscript describes a tool to be used in the Org mode of emacs to generate a course bundle with a syllabus, handouts, and slides. I like the idea of having a single styling that can be applied across all layers of a course packet. The authors point out that this is often done using various tools such as MS Word and PowerPoint. Another advantage is the ability to use text-based files that could be maintained under version control to track the changes to a course's content over time and foster collaboration.

To be transparent, I've never been successful in using emacs. Whether the package works as described needs to be reviewed by someone else. But, I found it difficult to navigate the documentation and templates. I could see something like this being a motivation to learn emacs and engage in this type of material in the future. Unfortunately, I find accessing the package at this level impenetrable. The installation notes state, "Clone the repo or download the ZIP archive". Again, I don't know much about emacs, but that seems pretty minimalist. Are there commands within emacs that would need to be run to load the package? Where in a directory structure in relation to the templates do I need to be to use the package? How would I build the examples? Descriptions of these steps should probably be in the README. The authors are clear that the package is for people with "basic knowledge of Org mode" and so the package is not for me. I worry that the community of people with this level of knowledge is pretty limited.

If possible, I would encourage the authors to separate the templates from the organization in their repo organization. Although the material is elsewhere, I think the README could use a more expansive description of how the repository is organized.

*Example Usage / Functionality documentation.* Could the authors perhaps create a video or set of annotated screenshots that shows how to generate one of the example course packets?

*Community guidelines.*  I would encourage the authors to create a CONTRIBUTION.md file in their repository that indicates how the community can engage with the developers to help with further development.

**Comment by pschloss** [comment]
apologies to @gregcaporaso if i accidentally checked/unchecked anything from your checklist!

**Comment by gregcaporaso** [comment]
The authors present Org-Coursepack, a set of tools for deriving lecture materials (slides, handouts, syllabus, exams) using emacs/Org. I'm probably not an ideal reviewer for this work as I've never used Org, and I rarely use emacs. If the other review (@patschloss) is also not an emacs/Org user, than I think it would make sense to consider adding a third reviewer who is more familar with these tools (I avoiding reading his review while preparing mine). 

I have reviewed the example lecture materials and project documentation, and the resulting course materials do seem very nicely organized. I can see how Org-Coursepack use by an instructor would be beneficial to a class. 

> Version: Does the release version given match the GitHub release (v1.0.1)

The most recent release version on GitHub is 1.1.0 - that doesn't match this version number, but does match a version number.


I created a few specific issues that I think would be important to address before publication:

 - [ ] https://github.com/joonro/Org-Coursepack/issues/1

 - [ ] https://github.com/joonro/Org-Coursepack/issues/2

 - [ ] https://github.com/joonro/Org-Coursepack/issues/3

**Comment by gregcaporaso** [comment]
> apologies to @gregcaporaso if i accidentally checked/unchecked anything from your checklist!

No worries! And apologies if I checked/unchecked any of yours (I got lost in that comment block a couple of times and worried that I may have messed with your list).

**Comment by joonro** [comment]
@pschloss and @gregcaporaso, thank you so much for your valuable comments. We will work to address them and report back.

**Comment by joonro** [comment]
Dear @pschloss, we just added [CONTRIBUTING.md](https://github.com/joonro/Org-Coursepack/blob/feature/CONTRIBUTING.md/CONTRIBUTING.md) (commit: https://github.com/joonro/Org-Coursepack/commit/51c28d283995fdac8ce6f54d9284c03751b6f5ad) to address your comment regarding _Community guidelines_. Please let me know if you need anything else regarding this issue. 

We will add the quickstarter guide with screenshots. We believe that will address your comment regarding _Example Usage / Functionality documentation_. Thank you very much!

**Comment by pschloss** [comment]
Thanks for adding the CONTRIBUTING.md file. I'm not seeing the quickstarter guide. Given that neither @gregcaporaso nor I have much experience with OrgMode or emacs, it would be ideal if @labarba could find someone to finish the review who does have experience. Perhaps Naupaka Zimmerman (gh: naupaka) or Kara Woo (gh: karawoo) would be up for it?

**Comment by joonro** [comment]
Yes we are working on the quickstarter guide. I will report back when it is done!

**Comment by joonro** [comment]
Dear @pschloss and @gregcaporaso, 

We have made significant updates to make Org-Coursepack more approachable to a wider audience, even those who are new to OrgMode or Emacs. Please see the updated [repo](https://github.com/joonro/Org-Coursepack). Specifically, based on your feedback, we focused on the following two things.

First was creating the [Quickstart guide](https://joonro.github.io/Org-Coursepack/Lectures/01%20Course%20Introduction.html#quickstart-guide). This guide provides step-by-step instructions with screenshots of examples so that users can jumpstart a new course construction.

Second, we substantially improved the installation instructions based on your comments. As a part of this update, we added an example init file for Emacs, which (a) includes basic user settings and (b) automatically installs necessary packages required to use the `Org-Coursepack`. We apologize for not including these instructions previously.

We realized from your valuable comments the importance of making the Org-Coursepack more approachable to various levels of users, and thus, have made a concerted effort to achieve this. Please let us know if you have any other comments or suggestions. Thank you for your time, and happy holidays!

**Comment by pschloss** [comment]
I recommend publication

**Comment by pschloss** [comment]
Yes

Sent frim my iPhone, expext more typos then nirmal

**Comment by labarba** [comment]
@gregcaporaso 👋  — You have a few unchecked items in the review checklist. Are you still working on your review?

**Comment by gregcaporaso** [comment]
Yes, I am - I should be done by the end of this week @labarba .

**Comment by gregcaporaso** [comment]
The new quickstart guide looks great - thanks @joonro! 

There are two items in my list that I can't check off yet:

> Version: Does the release version given match the GitHub release (v1.0.1)?

The version listed on this page is 1.0.1, but the most recent version of the project is 1.1.0. I suspect this just needs to be updated on this page. 

> Tests: Are there automated tests or manual steps described so that the function of the software can be verified?

There are not automated tests - this came up in https://github.com/joonro/Org-Coursepack/issues/1. The quickstart guide could be viewed as tests that can be run manually, though that may be too time consuming to reasonably be run every time a PR is issued or merged. Do other Org projects have automated tests associated with them? Matching the testing approach for other Org projects is probably what should be considered sufficient for this project.

**Comment by joonro** [comment]
Thank you @gregcaporaso. Regarding the version number difference, I don't think I can update the issue. I was wondering if that is something you can modify so it reflects the number on the repo?  @labarba, Please let me know if I need to do something to update it.

We will look into incorporating some automated test and report back soon!

**Comment by labarba** [comment]
@whedon set v1.1.0 as version

**Comment by whedon** [comment]
OK. v1.1.0 is the version.

**Comment by labarba** [comment]
Our lovely bot `whedon` can change the version 😁

**Comment by joonro** [comment]
Thank you!

**Comment by joonro** [comment]
Dear @gregcaporaso, 

We just finished adding automated tests to the repo using Travis CI as you requested. They include exporting of all course contents (syllabus, lecture, exam, and assignment) from the semester template Org file. In addition, the tests load the example init file before exporting contents and thus the validity of the init file (Emacs package installation and other settings) is automatically checked as well. 

Please let me know if you need anything else, and thank you very much.

**Comment by joonro** [comment]
I just updated the repo with improved testing - now it also includes testing of `org-coursepack-update-lecture-metadata` script as well as updating of class schedule table.

**Comment by gregcaporaso** [comment]
All changes look good, I recommend publication.

**Comment by labarba** [comment]
Both reviewers have recommended publication. Hooray!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00034/jose.00034/10.21105.jose.00034.pdf)

**Comment by juanklopper** [comment]
Absolutely great.  Thank you all.

**Comment by labarba** [comment]
@joonro — I do have one editorial request: that you add a section heading *Statement of Need*, as described in the [Author Guidelines](http://jose.theoj.org/about#author_guidelines). You can put under that heading the paragraphs in your paper that address the need for `Org-Coursepack`.

**Comment by labarba** [comment]
Also, please add a section heading before the *References* list.

**Comment by joonro** [comment]
@labarba I just added the two headings and pushed the changes. Thank you very much!

**Comment by joonro** [comment]
@pschloss and @gregcaporaso, thank you so much -- we really appreciated your feedback!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00034/jose.00034/10.21105.jose.00034.pdf)

**Comment by labarba** [comment]
OK, @joonro! Now we'll need you to make an archive on Zenodo (make sure to edit the title and author list there to match the paper), and report the archive DOI here.

**Comment by labarba** [comment]
@whedon set v1.2.0 as version

**Comment by whedon** [comment]
OK. v1.2.0 is the version.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2539667 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2539667" target="_blank">10.5281/zenodo.2539667</a> is the archive.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/23
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00034](https://doi.org/10.21105/jose.00034)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by joonro** [comment]
Dear @labarba, I'm so sorry, I just noticed that the second author's first name is missing a hyphen (should be Jae-Eun Namkoong instead of Jae Eun Namkoong). Would it be possible to change this?

**Comment by labarba** [comment]
Did you fix the paper source?

@arfon — Can you help me? I'm not sure what to do here: the author wants a hot fix on the author name. Can we update the PDF with `@whedon generate pdf`? Do we have to do something else with the Crossref deposit if the paper is fixed after publication?

**Comment by joonro** [comment]
Yes I just fixed the paper source. I'm sorry again for the inconveniences!

**Comment by arfon** [comment]
> @arfon — Can you help me? I'm not sure what to do here: the author wants a hot fix on the author name. Can we update the PDF with @whedon generate pdf? Do we have to do something else with the Crossref deposit if the paper is fixed after publication?

Unfortunately Whedon doesn't currently support updates like this. If you still have Whedon installed locally then you'll need to do the download and compile steps locally. I can then update the repos with the latest PDF and update the Crossref metadata.

**Comment by labarba** [comment]
Thanks, @arfon — I used `whedon` locally to re-download the submission repository to `whedon/tmp`, I re-compiled with `bundle exec whedon compile 34`, copied the files over to the local  `jose-papers` repo in the correct folder, then pushed to the remote (both the PDF and XML files).

Should I now run `bundle exec whedon deposit 34` locally, and that will do it?

**Comment by labarba** [comment]
BTW, I got this warning after the compilation:

```
[WARNING] Missing character: There is no ― in font [lmroman10-regular]:mapping=tex-text;!
tmp/34/10.21105.jose.00034.pdf
```

... but the PDF looks OK to me.

**Comment by arfon** [comment]
> Should I now run `bundle exec whedon deposit 34`

Yes, that should do it.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00034/status.svg)](https://doi.org/10.21105/jose.00034)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00034">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00034/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00034/status.svg
   :target: https://doi.org/10.21105/jose.00034
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00034/status.svg)](https://doi.org/10.21105/jose.00034)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3ODA=

**Comment by labarba** [comment]
Congratulations, @joonro! 🎉 

Sincere thanks to @pschloss, @gregcaporaso for their careful reviews 🙏

**Comment by labarba** [comment]
https://twitter.com/JOSE_TheOJ/status/1085239274902077441

**Comment by joonro** [comment]
Thank you so much @labarba for all your help!! And thank you @pschloss and @gregcaporaso for your insightful reviews!

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
