### ISSUE TITLE
[PRE REVIEW]: Python for Atmosphere and Ocean Scientists

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#36]
**Submitting author:** @DamienIrving (<a href="http://orcid.org/0000-0003-1258-5002">Damien Irving</a>)
**Repository:** <a href="https://github.com/carpentrieslab/python-aos-lesson" target ="_blank">https://github.com/carpentrieslab/python-aos-lesson</a>
**Version:** v1.0.0
**Editor:** @willingc
**Reviewers:** @darothen, @RobTheOceanographer

**Author instructions**

Thanks for submitting your paper to JOSE @DamienIrving. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@DamienIrving if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @willingc it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00036/jose.00036/10.21105.jose.00036.pdf)

**Comment by labarba** [comment]
👋  @willingc  — I've assigned this submission to you as handling editor. Since this will be your first editing assignment, let me know if you need to bounce ideas about selecting reviewers. Check out the [Editor's Guide](https://github.com/labarba/jose/blob/master/EditorsGuide.md) I put together: it describes the editor workflow, including needed `@whedon` commands.

**Comment by labarba** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by DamienIrving** [comment]
In terms of suggested reviewers, the following people have a strong background/interest in educating atmosphere and ocean scientists on best practices for python programming (and data science more generally): @darothen, @RobTheOceanographer, @nicolasfauchereau

@lwasser might also be a potential reviewer, as she has recently been involved in developing geospatial Data Carpentry lessons (that are aimed at a slightly different audience than my lessons)

**Comment by labarba** [comment]
@willingc — The author gave several suggestions for reviewers, and I also notice a hands-up response. Have you been able to look into getting this review started? Please let me know if there is any way I can help you.

**Comment by darothen** [comment]
Hey @DamienIrving and @willingc - I'd be happy to help out here! Please send any instructions my way and I can jump on this ASAP.

**Comment by labarba** [comment]
Thank you, @darothen ! 
I will now add you as reviewer for this submission, but stay tuned while we look for a second reviewer. In the meantime, have a look at the [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines) and let me know if you have any questions.

**Comment by labarba** [comment]
@whedon assign @darothen as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @darothen

**Comment by labarba** [comment]
Once we start the review, that will start a new issue thread, and you will have a review checklist to go through, while you enter comments in the thread and possibly open issues on the submission repository. For example, have a look at a review concluded recently: https://github.com/openjournals/jose-reviews/issues/29

**Comment by labarba** [comment]
@RobTheOceanographer — Does your thumbs-up above mean that you agree to review this submission for JOSE?

**Comment by RobTheOceanographer** [comment]
Hiya @labarba, my thumbs up was a general show of support... but I guess I could review the submission, sure.

**Comment by labarba** [comment]
Thanks for acquiescing @RobTheOceanographer 😁

**Comment by labarba** [comment]
@whedon add @RobTheOceanographer as reviewer

**Comment by whedon** [comment]
OK, @RobTheOceanographer is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/37. Feel free to close this issue now!
