### ISSUE TITLE
[PRE REVIEW]: A graduate student-led participatory live-coding quantitative methods course in R: Experiences on initiating, developing, and teaching

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#39]
**Submitting author:** @lwjohnst86 (<a href="http://orcid.org/0000-0003-4169-2616">Luke W. Johnston</a>)
**Repository:** <a href="https://github.com/UofTCoders/rcourse" target ="_blank">https://github.com/UofTCoders/rcourse</a>
**Version:** v2.1.0
**Editor:** @juanklopper
**Reviewers:** @jhollist, @MattForshaw

**Author instructions**

Thanks for submitting your paper to JOSE @lwjohnst86. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lwjohnst86 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @tracykteal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@tracykteal) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #39 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #39 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/orcid_validator.rb:12:in `initialize': undefined method `strip' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:91:in `block in check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:89:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon.rb:70:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
Hi @lwjohnst86 👋 — you are missing an ORCID for co-author Lindsay Coome.

**Comment by labarba** [comment]
👋  @tracykteal — The submitting author requested you as handling author. Ping me if you have any issues!

**Comment by tracykteal** [comment]
@whedon assign @tracykteal as editor

**Comment by whedon** [comment]
OK, the editor is @tracykteal

**Comment by lwjohnst86** [comment]
@labarba Do all authors need to have an ORCID? She doesn't have one.

**Comment by labarba** [comment]
JOSE needs all authors to have an ORCID. Can you request that she get one?

**Comment by labarba** [comment]
👋  @lwjohnst86 — Did you talk with your co-author about getting an ORCID? We'll need that to process the paper. Let us know!

**Comment by lwjohnst86** [comment]
Yes, they finally responded just last night. I will updated now. I assume I just make that change to the repo and not have to make a new tag?

**Comment by labarba** [comment]
Just make the change in the paper metadata! Then you can run `@whedon generate pdf` yourself to feel the power of our bot.

**Comment by lwjohnst86** [comment]
Amazing!! Looks great :smile:

**Comment by labarba** [comment]
👋  @tracykteal — Any ideas for reviewers here?

**Comment by tracykteal** [comment]
Thanks, I've sent out emails. Will add here once they respond.

**Comment by lwjohnst86** [comment]
:wave: Hi, just giving a ping to see what the progress is like. Thanks!

**Comment by labarba** [comment]
Hi @tracykteal — this submission is waiting for you to assign reviewers for a while now. Can you update us on your status? Thanks!

**Comment by lwjohnst86** [comment]
Any word on this? It's been a while.

**Comment by labarba** [comment]
I've reached out to @tracykteal by email now. Thanks for the ping.

**Comment by labarba** [comment]
👋  @K8hertweck — You signed up to review for JOSE a while back, marking R as language and biology as domain context ... could you have a look at this submission, and let me know if you'd be willing to contribute a review? Thank you!

**Comment by labarba** [comment]
Hi, @jhollist — We're looking for reviewers for this JOSE submission, have a look! Might you be able to contribute here? Thank you! 🙏

**Comment by labarba** [comment]
Maybe @jsta could help us out? We're in need of reviewers for this submission to JOSE. Have a look and let me know if you're up for it ... Merci! 😎

**Comment by jhollist** [comment]
I should have some time next week, so count me in.

**Comment by labarba** [comment]
@whedon assign @jhollist as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jhollist

**Comment by labarba** [comment]
Thank you, @jhollist — we're looking for a second reviewer, and we'll then start the review issue.

**Comment by MattForshaw** [comment]
@labarba @tracykteal I would be happy to help out on this one.

**Comment by labarba** [comment]
Thank you, @MattForshaw ! 
I will add you now and start the review.

**Comment by labarba** [comment]
@whedon add @MattForshaw as reviewer

**Comment by whedon** [comment]
OK, @MattForshaw is now a reviewer

**Comment by labarba** [comment]
@whedon assign @juanklopper as editor

**Comment by whedon** [comment]
OK, the editor is @juanklopper

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/49. Feel free to close this issue now!
