### ISSUE TITLE
[PRE REVIEW]: A course on Geographic Data Science

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#40]
**Submitting author:** @darribas (<a href="http://orcid.org/0000-0002-6274-1619">Daniel Arribas-Bel</a>)
**Repository:** <a href="https://github.com/darribas/gds18" target ="_blank">https://github.com/darribas/gds18</a>
**Version:** v4.0
**Editor:** @labarba
**Reviewers:** @lheagy, @jsta

**Author instructions**

Thanks for submitting your paper to JOSE @darribas. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@darribas if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@labarba) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #40 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by labarba** [comment]
👋  @lheagy — Would you like to review this submission to JOSE? Looks right up your alley! (If you're unable, could you recommend someone else? Thanks!)

**Comment by lheagy** [comment]
Hi @labarba: This looks really interesting! I would be happy to review :)

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00040/jose.00040/10.21105.jose.00040.pdf)

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1080/02680510701619976 may be missing for title: Designing Learning Objects for Online Learning
- https://doi.org/10.4324/9781315763309-4 may be missing for title: Principles of enquiry-based learning
- https://doi.org/10.2307/1183338 may be missing for title: Inverting the classroom: A gateway to creating an inclusive learning environment
- https://doi.org/10.1080/10618600.2017.1384734 may be missing for title: 50 years of data science
- https://doi.org/10.1007/978-3-642-01976-0_3 may be missing for title: Interactive techniques and exploratory spatial data analysis
- https://doi.org/10.1177/0160017607301605 may be missing for title: Supervised regionalization methods: A survey

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon check references

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.2307/1183338 is OK
- http://doi.org/10.1080/10618600.2017.1384734 is OK
- http://doi.org/ISBN:978-0-471-73545-8 is OK
- http://doi.org/10.1177/0160017607301605  is OK

MISSING DOIs

- https://doi.org/10.1080/02680510701619976 may be missing for title: Designing Learning Objects for Online Learning
- https://doi.org/10.4135/9781526401717.n4 may be missing for title: Principles of enquiry-based learning

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@darribas : You shouldn't use the `doi` field for ISBNs (that turns into a broken link). The two "missing DOIs" suggested by `whedon` are false leads.

**Comment by labarba** [comment]
Also, you need { } around GIS in https://github.com/darribas/gds18/blob/1cac024f860caa9bbd31b47df937b9377daf724a/paper.bib#L83

**Comment by jsta** [comment]
I'm happy to contribute a review on this paper @labarba

**Comment by labarba** [comment]
@whedon add @jsta as reviewer

**Comment by whedon** [comment]
OK, @jsta is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/42. Feel free to close this issue now!
