### ISSUE TITLE
[PRE REVIEW]: Tutorial for Developing Image-Guided Intervention Modules Using 3D Slicer

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#41]
**Submitting author:** @lgroves6 (<a href="http://orcid.org/0000-0002-9654-9190">Leah Groves</a>)
**Repository:** <a href="https://github.com/lgroves6/IGTTutorialWebsite" target ="_blank">https://github.com/lgroves6/IGTTutorialWebsite</a>
**Version:** v1.0.0
**Editor:** @juanklopper
**Reviewers:** @jcfr, @fedorov

**Author instructions**

Thanks for submitting your paper to JOSE @lgroves6. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lgroves6 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @juanklopper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@juanklopper) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00041/jose.00041/10.21105.jose.00041.pdf)

**Comment by juanklopper** [comment]
@lgroves6 thank you for your submission.  I am a couple of hours late to reply, but it's been a busy weekend of gunshot violence here in Cape Town and I have been operating 'till early morning every day.  No 3D image guidence here.  Just my two hands and a scalpel. :)

I'd love to learn more about your project.  I note that @labarba has mentioned that a README file is a good place to start.  Could you please populate that for me.  I will study your PDF submission (and the website) as soon as I can, then we can start working on the paper and get some reviewers assigned.

Juan.

**Comment by lgroves6** [comment]
Hello Juan,

Sorry for the late reply, I hope this e-mail find you well. I hope the gun violence has since settled down. I have populated the ReadMe file for you to review.

Please let me know what the next steps are.

Regards,

Leah

**Comment by labarba** [comment]
@lgroves6 — I'm confused ... I don't see any updates on your README.md: still empty!

**Comment by juanklopper** [comment]
@lgroves6 from what I can see, it is an _exceptional_ (static) instructional resource.  I need to hear from @labarba, though, how she sees it fit into our developing ideas around the type of resource we accept for publication.  This is a journal for publishing computational learning modules and educational software according to our website.  A good start therefor would probably be to refer to the work as a learning module instead of a blog as is in the current manuscript (and on the web).
@labarba what are your thoughts?

**Comment by lgroves6** [comment]
Hello again,

I am confused as to why you are unable to view the README file. Please try to view it through this link https://github.com/lgroves6/Tutorial-for-developing-image-guided-intervention-modules-using-3D-slicer/blob/master/README.md.

Let me know if this works.

Regards,

Leah

________________________________

**Comment by labarba** [comment]
I agree with @juanklopper that the use of the term "blog" is confusing. A blog is a rolling sequence of dated posts, often written in personal tones. I don't see that you have dated posts on this webpage. Why call it a blog?

**Comment by lgroves6** [comment]
Hello all,

I have updated the proper README file, as I didn’t realize I had updated the wrong directory. It is now within the proper directory and can be found at this link:
https://github.com/lgroves6/IGTTutorialWebsite/blob/master/paper.md. I have also removed the work blog from the README and paper.md files. You are correct that the term blog is perhaps not the best vocabulary, so we are very happy to term it a learning module.

Please let me know what else you need from me or any changes that should be made.

Thank you for getting back to us and being thorough with your assessment.

Regards,

Leah Groves

________________________________

**Comment by juanklopper** [comment]
Thanks @lgroves6 I am happy with those changes.  Perhaps it is time to consider approaching reviewers.  You are free to suggest potential experts.  @labarba do you have anyone in mind that we may approach?

**Comment by lgroves6** [comment]
Hello again, 

I have reach out to a few experts who are interested in being potential reviewers. They are all experts as they are some of the major 3D Slicer developers. 

Reviewer information:
 Jean-Christophe Fillion-Robin (@jcfr, jcfr@kitware.com)
  Andrey Fedorov (@fedorov, fedorov@bwh.harvard.edu)
  Matt M (@thewtex, matt.mccormick@kitware.com) 

Please let me know if there is any additional information that you need, or anything else I need to do within the review process.

**Comment by juanklopper** [comment]
I have contacted these individuals.

**Comment by juanklopper** [comment]
PS, please let them know about my email address juan.klopper@uct.ac.za  I don't want the post to land up in their spam folders :)

**Comment by jcfr** [comment]
@lgroves6  Thanks again for involving us in the review process, I will review in the next few days.

**Comment by fedorov** [comment]
Is this where we should review? The title of the issue says "prereview".

**Comment by labarba** [comment]
@whedon assign @jcfr as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jcfr

**Comment by labarba** [comment]
@whedon add @fedorov as reviewer

**Comment by whedon** [comment]
OK, @fedorov is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/46. Feel free to close this issue now!
