### ISSUE TITLE
[PRE REVIEW]: Aero Python: classical aerodynamics of potential flow using Python

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#43]
**Submitting author:** @labarba (<a href="http://orcid.org/0000-0001-5812-2711">Lorena A. Barba</a>)
**Repository:** <a href="https://github.com/barbagroup/AeroPython" target ="_blank">https://github.com/barbagroup/AeroPython</a>
**Version:** 0.0
**Editor:** @kyleniemeyer
**Reviewers:** @weymouth, @Juanlu001

**Author instructions**

Thanks for submitting your paper to JOSE @labarba. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@labarba if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kyleniemeyer it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@kyleniemeyer) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #43 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    15    0    15    0     0     68      0 --:--:-- --:--:-- --:--:--    68
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.jose.00043.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00043/jose.00043/10.21105.jose.00043.pdf)

**Comment by labarba** [comment]
👋 @kyleniemeyer — This is the second JOSE submission from Barbagroup. Thanks for editing!

**Comment by labarba** [comment]
As for reviewers, @Juanlu001 just finished a review for JOSS, but he'd be great for this one; I hope he'd be willing to volunteer the time 😁 
If not, maybe he can suggest someone else from the @AeroPython network? (name coincidence! see [tweet](https://twitter.com/LorenaABarba/status/464041427169583104) from 2014)

**Comment by kyleniemeyer** [comment]
@labarba Yep, I've got this one! It may take me a few days but I will work on finding some reviewers, if those you mentioned are not available.

**Comment by weymouth** [comment]
I'm happy to do a review

Gabriel D Weymouth
_______________________________________________
"Computers are useless. They can only give you answers." Pablo Picasso

**Comment by Juanlu001** [comment]
Beautiful coincidence indeed :) I agree that @AlexS12 would be a great reviewer for this one, but if he's busy I will gladly do it myself (starting next week)

**Comment by kyleniemeyer** [comment]
@weymouth @Juanlu001 I'd appreciate reviews from both of you, thanks! No worry on waiting until next week or so.

**Comment by kyleniemeyer** [comment]
@whedon add @weymouth as reviewer

**Comment by whedon** [comment]
OK, @weymouth is now a reviewer

**Comment by kyleniemeyer** [comment]
@whedon add @Juanlu001 as reviewer

**Comment by whedon** [comment]
OK, @Juanlu001 is now a reviewer
