### ISSUE TITLE
[PRE REVIEW]: Emacs-reveal: A software bundle to create OER presentations

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#48]
**Submitting author:** @lechten (<a href="http://orcid.org/0000-0002-3064-147X">Jens Lechtenbörger</a>)
**Repository:** <a href="https://gitlab.com/oer/emacs-reveal" target ="_blank">https://gitlab.com/oer/emacs-reveal</a>
**Version:** v3.0.2
**Editor:** @katyhuff
**Reviewers:** @jrosen48, @markgalassi

**Author instructions**

Thanks for submitting your paper to JOSE @lechten. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@lechten if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #48 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/48/paper.md): could not find expected ':' while scanning a simple key at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋  @lechten — Can you try deleting the lines before the paper metadata? Then run `@whedon generate pdf` to see if our bot can compile the paper.

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00048/jose.00048/10.21105.jose.00048.pdf)

**Comment by lechten** [comment]
The proof seems fine to me.

Concerning reviewers: Among the first list linked above, maybe @houshuang's interests in education/learning and Javascript match this paper. In a second link, whedon pointed to JOSS reviewers. What that on purpose? Initially, I submitted the paper to JOSS and was redirected here. In this [JOSS issue](https://github.com/openjournals/joss-reviews/issues/1386), two potential reviewers stated their interest in this paper. Would it be appropriate to invite them here?

**Comment by labarba** [comment]
The second link is pointing to the wrong reviewer list. Thanks for reporting! Nevertheless, if potential reviewers were found there, we can certainly invite them here.

**Comment by labarba** [comment]
👋   @jrosen48 and @markgalassi  — you expressed interest in reviewing this submission for JOSS ... we are the sister journal targeting software for education and computational learning modules. Are you willing to review it for us?

**Comment by jrosen48** [comment]
Hi, yes, I'd be happy to!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by markgalassi** [comment]
Lorena> 👋 @jrosen48 and @markgalassi — you expressed interest in
    Lorena> reviewing this submission for JOSS ... we are the sister
    Lorena> journal targeting software for education and computational
    Lorena> learning modules. Are you willing to review it for us?

I will be happy to.  Please point me to your journal's guidelines for
reviewers.

**Comment by lechten** [comment]
@labarba Do I have do to anything now? What happens next?

**Comment by labarba** [comment]
@willingc — could you handle this submission as editor? We already have two reviewers who have offered to contribute a review.

**Comment by labarba** [comment]
@whedon assign @jrosen48 as reviewer

**Comment by labarba** [comment]
@whedon add @markgalassi as reviewer

**Comment by labarba** [comment]
@katyhuff — could you handle this JOSE submission as editor? We already have two reviewers who have offered to contribute a review, and are assigned, and we are ready to start the review.

**Comment by katyhuff** [comment]
Sure!

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/50. Feel free to close this issue now!

**Comment by katyhuff** [comment]
Hi @markgalassi @jrosen48 , thanks for volunteering to review. You'll find reviewer guidelines at  http://jose.theoj.org/about#reviewer_guidelines. 
Now, I'll close this issue and we'll start the review over in #50 , where you'll see a review checklist.
