### ISSUE TITLE
[REVIEW]: Emacs-reveal: A software bundle to create OER presentations

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#50]
**Submitting author:** @lechten (<a href="http://orcid.org/0000-0002-3064-147X">Jens Lechtenbörger</a>)
**Repository:** <a href="https://gitlab.com/oer/emacs-reveal" target ="_blank">https://gitlab.com/oer/emacs-reveal</a>
**Version:** v3.0.3
**Editor:** @katyhuff
**Reviewer:** @jrosen48, @markgalassi
**Archive:** <a href="https://doi.org/10.5281/zenodo.3357438" target="_blank">10.5281/zenodo.3357438</a>

## Status

[![status](http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b/status.svg)](http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b"><img src="http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b/status.svg)](http://jose.theoj.org/papers/51d19b9c42e3115a548acd4a1cad377b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/oer/emacs-reveal" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jrosen48 & @markgalassi, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @katyhuff know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/oer/emacs-reveal">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v3.0.3
- [x] **Authorship:** Has the submitting author (@lechten) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/oer/emacs-reveal">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v3.0.3
- [ ] **Authorship:** Has the submitting author (@lechten) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [ ] **Example usage:** Do the authors include examples of how to use the software?
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jrosen48, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by labarba** [comment]
👋 @jrosen48, @markgalassi — Folks, this is where the review happens. You both have a review checklist at the top, to guide you through the process by checking off items to review. The version item is something we can check off in the end, as we will ask the authors to do a release after any revisions. Statement of need should be a section in the paper (the checklist has it also in the Documentation, but that's optional). 

Feel free to ask any questions here, and @katyhuff will help you out. You can also post questions to the author, or open issues in the submission repository.

Please tick off your Conflict of Interest and Code of Conduct items ASAP, so we all see the review has started. Thanks!

**Comment by markgalassi** [comment]
Dear @labarba, this is my first time so I'm feeling awkward and it took me a while to get the flow going.  I have checked off the items I am comfortable checking off.  I see no submit button after checking them, so I'm guessing you record them in real time (but please tell me if I'm wrong).  I have several suggestions for the paper.  How does that back-and-forth go?

**Comment by labarba** [comment]
@markgalassi — You can post comments right here with revision requests to the author.

**Comment by katyhuff** [comment]
@jrosen48 : Sorry I've been out of touch here. What is the status of your review?
@markgalassi : Thanks for getting started. How is your review progress going? A JOSE review involves checking submissions against a checklist of essential features and details in the submitted work. You can leave your brief review comments here in the comments. We also encourage reviewers to file issues against the submitted repository’s issue tracker. When you have completed your review, please leave a comment in the review issue saying so.

**Comment by jrosen48** [comment]
Hi all, I'm so sorry for the delay. I've moved through a few review items but have a few more to go. I will try to complete this by the end of this week (Friday, 6/14). I'm sorry again. Thanks!

**Comment by labarba** [comment]
@whedon remind @jrosen48 in 4 days

**Comment by whedon** [comment]
Reminder set for @jrosen48 in 4 days

**Comment by jrosen48** [comment]
As it didn't appear here automatically (did I not create the link correctly?), here is an issue I filed related to the statement of need: https://gitlab.com/oer/emacs-reveal/issues/9

**Comment by jrosen48** [comment]
A very brief issue regarding the absence of tests: https://gitlab.com/oer/emacs-reveal/issues/10

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by lechten** [comment]
Thanks, @jrosen48 for your feedback! I responded to your issues, and the new article proof reflects changes to the paper.

**Comment by jrosen48** [comment]
Thanks @lechten  - just responded to each of the comments (and have updated my review checklist accordingly!).

**Comment by whedon** [comment]
:wave: @jrosen48, please update us on how your review is going.

**Comment by labarba** [comment]
That was your automated reminder that I [set]( https://github.com/openjournals/jose-reviews/issues/50#issuecomment-500560838), @jrosen48. I see you could be getting close to recommending publication. What's your status, @markgalassi?

**Comment by labarba** [comment]
hi folks — I just sent an email to @markgalassi to ask for a status update. Stay tuned.

**Comment by katyhuff** [comment]
Thanks.

**Comment by lechten** [comment]
@labarba, @markgalassi  Any news on the status of this review? Anything that I could do?

**Comment by labarba** [comment]
The reviewer has gone MIA and is not responsive here or on email. @katyhuff: could you take executive action to complete the review without him?

**Comment by katyhuff** [comment]
Yes. I'll handle this sometime in the next day.

**Comment by whedon** [comment]
Reminder set for @katyhuff in 1 day

**Comment by katyhuff** [comment]
In the absense of our second reviewer, I have conducted a review myself. Though I'm not an emacs user, I am an avid reveal user. Thank you for this contribution @lechten . I have left some minor review comments below, but will be conducting final checks (with my handling editor hat on) in the coming moments. 

## Review checklist for @katyhuff

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/oer/emacs-reveal">repository url</a>?

I was confused by this at first. The repository is very small, with very few substantive files. However, it points to the more substantial associated repository in the same organization: https://gitlab.com/oer/emacs-reveal-howto. While the kernel of the functionality is in the main repository, much of the substance is in the howto repo.

- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

Yes, though it would be helpful if it were made clear what portions of the repository were covered by which licenses (as there are 3.... ). @lechten : am I missing something with regard to which content is covered by which licenses?

- [x] **Version:** Does the release version given match the GitHub release (v3.0.2)?
- [x] **Authorship:** Has the submitting author (@lechten) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)
(no performance claims. )

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)

I am not an emacs user (I use vim), but I followed the logic nonetheless. While I didn't fully deploy the system, I think I have it installed now. I can't test it very well, as I quickly become lost in emacs keybindings. The howto repo was essential to understanding this process and comprehending the contribution.

- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
(see issues raised by @jrosen48  and closed by @lechten .)

- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by katyhuff** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/02680510903482132 is OK
- 10.1109/MCSE.2011.41 is OK
- 10.21240/mpaed/34/2019.03.02.X is OK
- 10.11647/obp.0019.10 is OK
- 10.14742/ajet.2258 is OK
- 10.1145/1409360.1409377 is OK
- 10.3991/ijet.v8i1.2539 is OK
- 10.1002/tl.469 is OK
- 10.1007/978-1-4842-0076-6 is OK
- 10.21105/jose.00034 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by katyhuff** [comment]
Thank you @jrosen48  for your review -- we couldn't do this without you.
I appreciate your start on this review @markgalassi -- I'm sorry you weren't able to finish it, but I do hope that you will let us know ASAP if you have any blocking concerns about this work being accepted.

Thank you @lechten for a strong submission and for engaging actively in the review process! I have looked over the paper, double-checked all the DOI links, and have conducted a high-level review of the code itself. Everything looks ship-shape to me, though I will note one minor comment I have made above regarding the many license files being a bit confusing. I believe I can check the box, but if you have the will, I believe the repository would be improved by more clarity regarding the interpretation of the licenses folder.

At this point, please double-check the paper yourself, review any lingering details in your code/readme/etc., and then make an archive of the reviewed software in Zenodo/figshare/other service. **Please be sure that the DOI metadata (title, authors, etc.) matches this JOSS submission.** Once that's complete, please update this thread with the DOI of the archive, and I'll move forward with accepting the submission. Until then, now is your moment for final touchups!

**Comment by lechten** [comment]
@katyhuff Many thanks for taking care of the second review on such short notice!

Concerning licensing: Did you see the file [LICENSE](https://gitlab.com/oer/emacs-reveal/blob/master/LICENSE) or only the folder LICENSES? The challenge is that included software and resources come with different license terms. Thus, as explained in file [LICENSE](https://gitlab.com/oer/emacs-reveal/blob/master/LICENSE) I decided to go with the [REUSE](https://reuse.software/) approach: Files should either have a header indicating which free and open license among LICENSES applies or a separate file ending in ".license" (such as [paper.md.license](https://gitlab.com/oer/emacs-reveal/blob/master/paper.md.license)). I hope that I did not forget any such indicator.

I'll check out Zenodo next.

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by lechten** [comment]
I uploaded the current version: https://doi.org/10.5281/zenodo.3357438

**Comment by markgalassi** [comment]
after a month of travel I became very sick; can't keep up at all for the
last two months.  I'm sorry but I will have to step aside on this one.

**Comment by lechten** [comment]
@markgalassi I'm truly sorry to read this. I sincerely hope that you get well soon!

**Comment by katyhuff** [comment]
I'm also very sorry to hear it and am very grateful for your early effort on the review.

**Comment by katyhuff** [comment]
@whedon set v3.0.3 as version

**Comment by whedon** [comment]
OK. v3.0.3 is the version.

**Comment by katyhuff** [comment]
@whedon set 10.5281/zenodo.3357438 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3357438" target="_blank">10.5281/zenodo.3357438</a> is the archive.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by labarba** [comment]
@jrosen48 — you still have an unchecked item in the checklist (Functionality documentation). Can you see if you're satisfied with that, and issue your recommendation here?

**Comment by jrosen48** [comment]
HI @labarba, I'm sorry about that, I am satisfied with this (and have updated that item, accordingly!).

**Comment by katyhuff** [comment]
Thank you @jrosen48 

@labarba  I believe this is ready to accept!

**Comment by labarba** [comment]
@lechten — you have included the software repository in the list of references. JOSE papers have the repository (and archive) added as part of the margin decorators on the first page, so we ask that  you don't add it in the text or references.

**Comment by labarba** [comment]
In the section on Functionality, I find a couple of _in-text citations_, meaning, the citation is a part of speech in a sentence. E.g. "see Smith (2009)," or "as described in Smith (2009)." In those cases, please use the correct [Citation syntax](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax) to suppress the brackets.

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by lechten** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00050/jose.00050/10.21105.jose.00050.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/38

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/38, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by lechten** [comment]
@labarba Wow, that was fast. Many thanks for checking the citations. I rewrote some parts to avoid nested parentheses and parentheses following each other, which does indeed look much better.

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/39
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00050](https://doi.org/10.21105/jose.00050)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @lechten, your JOSE paper is now published! 🚀 

Sincere thanks to our editor: @katyhuff, and the reviewers: @jrosen48, @markgalassi — we greatly appreciate your contribution to JOSE 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00050/status.svg)](https://doi.org/10.21105/jose.00050)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00050">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00050/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00050/status.svg
   :target: https://doi.org/10.21105/jose.00050
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00050/status.svg)](https://doi.org/10.21105/jose.00050)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jose

**Comment by labarba** [comment]
Tweet announcing this paper:

https://twitter.com/JOSE_TheOJ/status/1157928348024225792

**Comment by lechten** [comment]
@jrosen48,  @katyhuff, @labarba, @markgalassi Many thanks to all of you, I learned a lot during this process! 

I would be happy to help in the future and signed up as reviewer.

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
