### ISSUE TITLE
[PRE REVIEW]: Happy Belly Bioinformatics: an open-source resource dedicated to helping biologists utilize bioinformatics

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#51]
**Submitting author:** @AstrobioMike (<a href="http://orcid.org/0000-0001-7750-9145">Michael D. Lee</a>)
**Repository:** <a href="https://github.com/AstrobioMike/AstrobioMike.github.io" target ="_blank">https://github.com/AstrobioMike/AstrobioMike.github.io</a>
**Version:** v1.1.1
**Editor:** @labarba
**Reviewers:** @luizirber, @JasonJWilliamsNY

**Author instructions**

Thanks for submitting your paper to JOSE @AstrobioMike. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@AstrobioMike if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #51 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #51 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-a1723d160bb6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@AstrobioMike : You're missing the line `bibliography: paper.bib` in the header of your paper. Can you push this fix?

**Comment by AstrobioMike** [comment]
Ah thanks, sorry about that!

**Comment by AstrobioMike** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00051/jose.00051/10.21105.jose.00051.pdf)

**Comment by AstrobioMike** [comment]
Some potential reviewers from the list might be: @JasonJWilliamsNY; @ShahneRodgers; @luizirber; @HadrienG

Thanks for your time and consideration, folks :)

**Comment by labarba** [comment]
👋  @JasonJWilliamsNY — would you like to contribute your first JOSE review? 😁

**Comment by luizirber** [comment]
I never did a JOSE review, but would love to try it out =]

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @luizirber as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @luizirber

**Comment by labarba** [comment]
Thank you, @luizirber! Stay tuned as we find a second reviewer, and then we'll start the review.

**Comment by JasonJWilliamsNY** [comment]
@labarba I am able to help out with review

**Comment by labarba** [comment]
@whedon add @JasonJWilliamsNY as reviewer

**Comment by whedon** [comment]
OK, @JasonJWilliamsNY is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/53. Feel free to close this issue now!
