### ISSUE TITLE
[PRE REVIEW]: mLEARn: An Implementation of Multi-layer Perceptron in C++

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#55]
**Submitting author:** @kalu-o (<a href="http://orcid.org/0000-0002-8152-4863">Kalu U. Ogbureke</a>)
**Repository:** <a href="https://github.com/kalu-o/mLEARn" target ="_blank">https://github.com/kalu-o/mLEARn</a>
**Version:** v1.0.1
**Editor:** @willingc
**Reviewers:** @dsblank, @trallard

**Author instructions**

Thanks for submitting your paper to JOSE @kalu-o. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kalu-o if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @willingc it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@willingc) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #55 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
👋 @willingc — The author suggested you as editor for this submission. Let me know if you can handle this one for JOSE. Thanks!

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #55 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '22 May 2019' (JSON::ParserError)
	from /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/compilers.rb:106:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/compilers.rb:12:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #55 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse': 784: unexpected token at '22 May 2019' (JSON::ParserError)
	from /app/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/compilers.rb:106:in `pdf_from_markdown'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/lib/whedon/compilers.rb:12:in `generate_pdf'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:56:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-379fcd917139/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
I don't see anything wrong with the paper metadata ... @arfon: would you have a quick look for us?

**Comment by arfon** [comment]
> I don't see anything wrong with the paper metadata ... @arfon: would you have a quick look for us?

Yeah, this is my fault. Fixing in https://github.com/openjournals/jose/pull/31

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00055/jose.00055/10.21105.jose.00055.pdf)

**Comment by arfon** [comment]
OK, fixed. Apologies for accidentally breaking things...

**Comment by labarba** [comment]
@dsblank — Would you be willing to contribute a review for JOSE? The submission is titled "mLEARn: An Implementation of Multi-layer Perceptron in C++" Let me know!

**Comment by willingc** [comment]
Sure thing @labarba. How many folks do you wish to have review from? 2 or 3?

**Comment by labarba** [comment]
We want two reviewers. A third reviewer can be invited to help when the submission is outside the "comfort zone" for the editor.

**Comment by dsblank** [comment]
Sure, I can help with this.

**Comment by labarba** [comment]
@whedon assign @dsblank as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @dsblank

**Comment by labarba** [comment]
Thanks, @dsblank! Hang tight while @willingc finds a second reviewer

**Comment by willingc** [comment]
Hi @trallard, I saw your name on the list of potential reviewers and thought you would be a good reviewer. Would you be willing to contribute a review for JOSE? The submission is titled "mLEARn: An Implementation of Multi-layer Perceptron in C++" Let me know! Thanks.

**Comment by trallard** [comment]
Hi @willingc sure, I would love to help with the review

**Comment by labarba** [comment]
@whedon add @trallard as reviewer

**Comment by whedon** [comment]
OK, @trallard is now a reviewer

**Comment by labarba** [comment]
Thanks for volunteering to review, @trallard! I will start the review now.

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/59. Feel free to close this issue now!

**Comment by willingc** [comment]
Thanks @labarba for starting the review.
