### ISSUE TITLE
[PRE REVIEW]: M4: Metals, Magnets, and Miscellaneous Materials

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#58]
**Submitting author:** @albi3ro (<a href="http://orcid.org/0000-0002-2127-8453">Christina Colleen Lee</a>)
**Repository:** <a href="https://github.com/albi3ro/M4" target ="_blank">https://github.com/albi3ro/M4</a>
**Version:** v_jose-submit
**Editor:** @katyhuff
**Reviewers:** @IanHawke, @william-pfalzgraff

**Author instructions**

Thanks for submitting your paper to JOSE @albi3ro. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@albi3ro if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #58 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #58 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: affiliations, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
👋  @albi3ro —You will need to add the missing fields to the paper metadata. 
See error: `Paper YAML header is missing expected fields: affiliations, bibliography `

**Comment by labarba** [comment]
@katyhuff — The author suggested you as handling editor for this JOSE submission, but I know you're already editing another. Let me know if you're willing to do one more... otherwise, perhaps @moorepants will be willing? (although not quite aligned with area of interest/expertise). Help!

**Comment by moorepants** [comment]
I'll be on vacation for the next two weeks, so I couldn't do it until July 11th.

**Comment by katyhuff** [comment]
I'm swamped this week, but I can take a look at this next week.

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #58 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: affiliations, bibliography (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-18b9a37e7f54/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by katyhuff** [comment]
@albi3ro Please let me know you are able to update the paper metadata to include the missing fields ( `affiliations, bibliography` as suggested by @labarba above) . At that point, I'll begin assigning reviewers.

**Comment by albi3ro** [comment]
I updated `paper.md`, so it should work now.  

I don't have an affiliation at the moment, so I created an affiliation named "Independent Researcher".  But if you can a different protocol for no affiliations, I can change that.

**Comment by katyhuff** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf)

**Comment by albi3ro** [comment]
Do I need to do anything more now?

**Comment by labarba** [comment]
Your editor, @katyhuff, will be looking for reviewers for the submission. You could help if you find someone on [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE that you can recommend!

**Comment by katyhuff** [comment]
Thanks @labarba -- and @albi3ro I'm sorry for the delay. I apologize, I thought you were still working on the bibliography part of the request. @albi3ro:  Please note that your bibliography still doesn't appear (now, simply because you don't reference anything).


In any case, I believe that I have identified a couple of appropriate reviewers whom I'll invite now. If you have suggestions, of course, they are more than welcome.

**Comment by katyhuff** [comment]
@leios : James Schloss, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education) ? This submission is in need of expertise in physics as well as familiarity with the systems and languages involved (julia, jupyter). I think you would be an excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.


* Title: M4: Metals, Magnets, and Miscellaneous Materials 
* Summary: ... the wonders of materials all around you, and some of the revolutions that are shocking the field. Posts are converted jupyter notebooks with Julia code, and are meant for interaction.
* Article Proof:  https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf
* Submitting author: @albi3ro (Christina Colleen Lee)
* Repository: https://github.com/albi3ro/M4
* Website: http://albi3ro.github.io/M4/
* Version: v_jose-submit

**Comment by katyhuff** [comment]
@trallard : Tania Allard, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education) ? This submission is in need of expertise in materials as well as familiarity with the systems and languages involved (julia, jupyter). I think you would be an excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.


* Title: M4: Metals, Magnets, and Miscellaneous Materials 
* Summary: ... the wonders of materials all around you, and some of the revolutions that are shocking the field. Posts are converted jupyter notebooks with Julia code, and are meant for interaction.
* Article Proof:  https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf
* Submitting author: @albi3ro (Christina Colleen Lee)
* Repository: https://github.com/albi3ro/M4
* Website: http://albi3ro.github.io/M4/
* Version: v_jose-submit

**Comment by leios** [comment]
@katyhuff There might be a slight conflict of interest here. @albi3ro Is a good friend of mine.

**Comment by trallard** [comment]
Hey @katyhuff I would love to take this on.

The problem is I have another review that I want to complete before going on leave on the 27th. I can try and make some advances on this (though) I cannot promise anything. Or move it forward after the 14th of August.

Would this work for y'all?

**Comment by katyhuff** [comment]
@leios : Thanks for letting me know. It's up to you to decide whether you can make an impartial evaluation of this work. Our official policy is: 

```
JOSS Conflict of Interest Policy
The definition of a conflict of Interest in peer review is a circumstance that makes you “unable to make an impartial scientific judgment or evaluation.” (PNAS Conflict of Interest Policy). JOSS is concerned with avoiding any actual conflicts of interest, and being sufficiently transparent that we avoid the appearance of conflicts of interest as well.

As a reviewer, COIs are your present or previous association with any authors of a submission: recent (past four years) collaborators in funded research or work that is published; and lifetime for the family members, business partners, and thesis student/advisor or mentor. In addition, your recent (past year) association with the same organization of a submitter is a COI, for example, being employed at the same institution.

If you have a conflict of interest with a submission, you should disclose the specific reason to the submissions’ editor. This may lead to you not being able to review the submission, but some conflicts may be recorded and then waived, and if you think you are able to make an impartial assessment of the work, you should request that the conflict be waived. For example, if you and a submitter were two of 2000 authors of a high energy physics paper but did not actually collaborate. Or if you and a submitter worked together 6 years ago, but due to delays in the publishing industry, a paper from that collaboration with both of you as authors was published 2 year ago. Or if you and a submitter are both employed by the same very large organization but in different units without any knowledge of each other.

Declaring actual, perceived, and potential conflicts of interest is required under professional ethics. If in doubt: ask the editors.```

Do you think that, despite being friends, you can make a thorough and impartial assessment of this work?

**Comment by katyhuff** [comment]
@trallard Thanks for letting me know. I'll try to find someone else, as it sounds like your plate is pretty full.  

@albi3ro : Can you recommend anyone?

**Comment by katyhuff** [comment]
@lheagy : Lindsay Heagy, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education)? This submission is in need of expertise in physics as well as familiarity with the systems and languages involved (julia, jupyter). Though I know your scientific domain is somewhat outside of the materials science focused physics in this work, your experience in Julia, education, and the physical sciences make you a potentially excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.


* Title: M4: Metals, Magnets, and Miscellaneous Materials 
* Summary: ... the wonders of materials all around you, and some of the revolutions that are shocking the field. Posts are converted jupyter notebooks with Julia code, and are meant for interaction.
* Article Proof:  https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf
* Submitting author: @albi3ro (Christina Colleen Lee)
* Repository: https://github.com/albi3ro/M4
* Website: http://albi3ro.github.io/M4/
* Version: v_jose-submit

**Comment by labarba** [comment]
I wonder if @IanHawke could help with this review ... Ian—this submission to JOSE consists of Jupyter notebooks using Julia, addressing physics of materials. Could you have a look and consider if you could contribute a review?

**Comment by katyhuff** [comment]
Thanks @labarba !

**Comment by labarba** [comment]
Another person who might be able to help with this JOSE review is @dga_smith (more chemistry than physics background, I think, but materials science sits at some intersection of those fields).

@dga_smith — Could you have a look at this JOSE submission and consider if you could contribute a review? Or perhaps you can think of someone else who could?
[ Here's the article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf)

**Comment by IanHawke** [comment]
Technically I think I can do this, yes (with some brushing up). As far as timing goes I will only be able to start toward the end of next week, and probably only have time to cover the straightforward part of the checklist before having to stop for a week. I would hope to be able to comment on all the material by the end of the month. Sorry I can't promise anything faster.

**Comment by lheagy** [comment]
Thanks for thinking of me @katyhuff; this looks like an interesting set of resources! I am a bit conference over-loaded for the next few weeks, so realistically it would likely be mid-august before I could take a look... Please feel free to keep me on the list as a back-up, if you are still in need of someone in a few weeks time

**Comment by IanHawke** [comment]
A bit of a drive-by start to the review process, I'm afraid: I won't be able to follow up until a week from now.

**Comment by katyhuff** [comment]
@whedon assign @IanHawke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @IanHawke

**Comment by katyhuff** [comment]
Thanks for agreeing @IanHawke !
Thanks for letting me know @lheagy . I'll try for one more reviewer, but will let you know if I can't find anyone.

**Comment by katyhuff** [comment]
@william-pfalzgraff : William Pfalzgraff are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education)? This submission is in need of expertise in materials science (physics, chemistry) as well as familiarity with the systems and languages involved (julia, jupyter). Though I know your scientific domain is somewhat outside of the materials science focus in this work, and your computational experience may not include Julia. However, your breadth of experience in other programming languages, as well as your expertise in education and the chemical sciences make you a potentially excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.


* Title: M4: Metals, Magnets, and Miscellaneous Materials 
* Summary: ... the wonders of materials all around you, and some of the revolutions that are shocking the field. Posts are converted jupyter notebooks with Julia code, and are meant for interaction.
* Article Proof:  https://github.com/openjournals/jose-papers/blob/jose.00058/jose.00058/10.21105.jose.00058.pdf
* Submitting author: @albi3ro (Christina Colleen Lee)
* Repository: https://github.com/albi3ro/M4
* Website: http://albi3ro.github.io/M4/
* Version: v_jose-submit

**Comment by william-pfalzgraff** [comment]
Hi @katyhuff. I'm currently on vacation, but I'd be able to start my review next week (the week of July 29).  Would that work?

**Comment by katyhuff** [comment]
That would be fantastic @william-pfalzgraff . Thank you.

**Comment by katyhuff** [comment]
@whedon add @william-pfalzgraff as reviewer

**Comment by whedon** [comment]
OK, @william-pfalzgraff is now a reviewer

**Comment by katyhuff** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/61. Feel free to close this issue now!

**Comment by katyhuff** [comment]
@albi3ro Thank you for your patience. I've now found reviewers, and we'll be able to start the review discussion over in #61. Please keep an eye on that issue for comments from reviewers in the next couple of weeks. 

@william-pfalzgraff @IanHawke Thank you for volunteering! Let's move over to #61 where we'll conduct the review!
