### ISSUE TITLE
[REVIEW]: mLEARn: An Implementation of Multi-layer Perceptron in C++

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#59]
**Submitting author:** @kalu-o (<a href="http://orcid.org/0000-0002-8152-4863">Kalu U. Ogbureke</a>)
**Repository:** <a href="https://github.com/kalu-o/mLEARn" target ="_blank">https://github.com/kalu-o/mLEARn</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @trallard, @rasbt
**Archive:** <a href="https://doi.org/10.5281/zenodo.5093771" target="_blank">10.5281/zenodo.5093771</a>

## Status

[![status](http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b/status.svg)](http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b"><img src="http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b/status.svg)](http://jose.theoj.org/papers/60d6aba965ea6bdc929c9b7b1f46b44b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kalu-o/mLEARn" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dsblank & @trallard, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @willingc know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kalu-o/mLEARn">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v1.0.0
- [x] **Authorship:** Has the submitting author (@kalu-o) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kalu-o/mLEARn">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.0
- [x] **Authorship:** Has the submitting author (@kalu-o) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dsblank, @trallard it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00059/jose.00059/10.21105.jose.00059.pdf)

**Comment by labarba** [comment]
👋 @dsblank, @trallard — Thank you for agreeing to review this submission to JOSE. This is where it happens: you both have a checklist at the top of this issue to help you along. Feel free to post questions here and open issues on the submission repository, if needed. The version item is something we can check off in the end, as we will ask the authors to do a release after any revisions. Statement of need should be a section in the paper (the checklist has it also in the Documentation, but that's optional).

Please tick off your Conflict of Interest and Code of Conduct items ASAP, so we all see the review has started. Thanks!

**Comment by labarba** [comment]
Our [Reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) cover briefly our expectations.

**Comment by labarba** [comment]
@dsblank, @trallard — hi folks! May we have an update from you on the status of your review? Thank you! 🙏

**Comment by labarba** [comment]
@dsblank, @trallard — hello, there! Could we have a status update from you both on your review for JOSE? Thanks!

**Comment by trallard** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00059/jose.00059/10.21105.jose.00059.pdf)

**Comment by trallard** [comment]
@whedon  check references

**Comment by trallard** [comment]
@kalu-o The paper has a clear statement of need, but the docs in the repository are lacking this. 
I think this should be added to make this explicit in the docs.

**Comment by dsblank** [comment]
Hi all. I am having a hard time wrapping my head around the form of the publication, and how much responsibility to, say, cite previous work.

**Comment by kalu-o** [comment]
> Hi all. I am having a hard time wrapping my head around the form of the publication, and how much responsibility to, say, cite previous work.

Hi,
Did you mean citation of previous works are not sufficient? I understand from the paper guideline that technical details are not necessary.

**Comment by kalu-o** [comment]
> @kalu-o The paper has a clear statement of need, but the docs in the repository are lacking this.
> I think this should be added to make this explicit in the docs.

Hi,
Besides README.md, which other "doc" should reflect this?

**Comment by labarba** [comment]
> Hi all. I am having a hard time wrapping my head around the form of the publication, and how much responsibility to, say, cite previous work.

@dsblank —The publication is a summary, an "advertisement," of the scholarship contained in the software submission. The software is meant to be used in the teaching of machine learning. In the paper, the authors should cite similar efforts where others have created educational software or learning materials to teach similar topics.

**Comment by labarba** [comment]
@willingc, @dsblank, @trallard — Can we have a status update on this review?

**Comment by trallard** [comment]
@whedon  check references

**Comment by trallard** [comment]
Sorry for taking so long to complete this review. 
I have gone over the functionality and performance of the package and did not find any major issues. 

I opened an issue on the main repo to add a clear statement of need to the main README. 
I believe that is the only outstanding item from my side.

**Comment by dsblank** [comment]
Wow, didn't realize that this was blocking on me! Please remove me from the reviewers.

**Comment by dsblank** [comment]
Wow, didn't realize that this was blocking on me! Please remove me from the reviewers.

**Comment by dsblank** [comment]
Wow, didn't realize that this was blocking on me! Please remove me from the reviewers.

**Comment by labarba** [comment]
@whedon remove @dsblank as reviewer

**Comment by whedon** [comment]
OK, @dsblank is no longer a reviewer

**Comment by labarba** [comment]
Thanks for popping in, @dsblank — and happy retirement!

**Comment by labarba** [comment]
@abuccts 👋  — Hello! You signed up as a reviewer for JoSE a while back, with interest in machine learning and others. Would you be able to contribute a review for this submission? 
**mLEARn: An Implementation of Multi-layer Perceptron in C++**
https://github.com/openjournals/jose-reviews/issues/59

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@whedon add @rasbt as reviewer

**Comment by whedon** [comment]
OK, @rasbt is now a reviewer

**Comment by labarba** [comment]
hi @rasbt 👋 
Thank you for agreeing to review this submission to the Journal of Open Source Education! We really appreciate it. 

This submission consists of a software library for students to play around with a multi-layer perceptron and come to understand the algorithm. You have a review checklist at the top of this review thread to guide you. Have a look at the [JOSE scope](https://jose.theoj.org/about#submitting), and ask any questions you may have right here!

**Comment by rasbt** [comment]
Hi everyone,
just a short heads-up. I got a bit delayed by finals' week and one more paper deadline, but getting to this review is a big item on my todo-list for next week!

**Comment by rasbt** [comment]
This submission looks really good overall, just had a few minor points that should be addressed before accepting. Posted them here: https://github.com/kalu-o/mLEARn/issues/3

**Comment by labarba** [comment]
Thanks so much for reviewing this JOSE submission, @rasbt 🙏 

 @kalu-o — Thank you for your extreme patience, as JOSE nearly ground to a halt in 2020. We're just resurfacing and beginning to re-organize. Could you have a look at the minor comments? I will be glad to move this to publication finally!

**Comment by labarba** [comment]
@kalu-o — Please check the second figure in the paper: it goes outside the margin. Maybe you can rearrange the diagrams? Consider adding figure numbers and captions.

**Comment by labarba** [comment]
hi @trallard — You reviewed this JOSE submission a while back, and only left unchecked the box for Statement of Need. The paper does include this section, while the README in the repo has a brief aim, as follows:

> The aim of mLEARn is to provide a simple and extendable machine learning platform for students in courses involving C++ and machine learning.

I don't think we need to require a JOSE-style Statement of Need on the README, so let's be satisfied with the current form.

Once published, it would be nice if @kalu-o added the JOSE badge on the README!

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by labarba** [comment]
@kalu-o 👋  — We have received a new review for your JOSE submission, with minor revision requests. Could you have a look and let us know when it's ready? We'll be glad to move this to publication soon.

**Comment by kalu-o** [comment]
> @kalu-o — Please check the second figure in the paper: it goes outside the margin. Maybe you can rearrange the diagrams? Consider adding figure numbers and captions.

@labarba The issues are now addressed. Many thanks.

**Comment by kalu-o** [comment]
> @kalu-o  — We have received a new review for your JOSE submission, with minor revision requests. Could you have a look and let us know when it's ready? We'll be glad to move this to publication soon.

Apologies for getting back late. The issues have been addressed ( I think). Many thanks to all for their time.

**Comment by labarba** [comment]
hi @kalu-o — good to hear from you. 

👋 @rasbt — could you pop in to see if the minor issues you raised in your review have been addressed? This submission might be near the finish line now! Thanks so much...

**Comment by labarba** [comment]
@rasbt — We just need a confirmation from you here that the authors have addressed your review comments, and you recommend publication. Thanks!

**Comment by rasbt** [comment]
@labarba I just looked at the feedback and file-change diffs, and it looks like all my concerns were addressed. Happy to recommend it for publication now.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@kalu-o — We now have two reviewers who have completed their review, and we are close to the finish line! After a minor revision in the paper (see my comments below), the final steps you will take are:

- [ ] make a tagged release on the repository, and report the version number here so I can update the metadata
- [ ] make a full deposit of the repository in Zenodo (or equivalent service), and report the archive DOI here, to enter it in the metadata
- [ ] manually edit the archive title and author list as needed to match the JOSE paper

My only comment on the paper is that I miss a passage that explains to readers how they might potentially use the software in their teaching and learning context. If you have used it within a course, it helps to describe briefly how it was used. Mostly, though, what we want is to make it easier for another instructor or a self-learner to visualize how they might reuse your artifacts. Have a look at the ["What should my paper contain?"](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain) of our documentation.

**Comment by kalu-o** [comment]
> @kalu-o — We now have two reviewers who have completed their review, and we are close to the finish line! After a minor revision in the paper (see my comments below), the final steps you will take are:
> 
> * [ ]  make a tagged release on the repository, and report the version number here so I can update the metadata
> * [ ]  make a full deposit of the repository in Zenodo (or equivalent service), and report the archive DOI here, to enter it in the metadata
> * [ ]  manually edit the archive title and author list as needed to match the JOSE paper
> 
> My only comment on the paper is that I miss a passage that explains to readers how they might potentially use the software in their teaching and learning context. If you have used it within a course, it helps to describe briefly how it was used. Mostly, though, what we want is to make it easier for another instructor or a self-learner to visualize how they might reuse your artifacts. Have a look at the ["What should my paper contain?"](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain) of our documentation.

@labarba ---- Thanks for the update.
1. I made a tagged release (v1.0.0): https://github.com/kalu-o/mLEARn/archive/refs/tags/v1.0.0.tar.gz
2. The DOI: 10.5281/zenodo.5093771

The issue you raised at the end has aso been addressed.

**Comment by labarba** [comment]
@whedon set v1.0.0 as version

**Comment by whedon** [comment]
OK. v1.0.0 is the version.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.5093771 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5093771" target="_blank">10.5281/zenodo.5093771</a> is the archive.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00059/jose.00059/10.21105.jose.00059.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@kalu-o 👋  – please merge this PR with minor edits, and I'l proceed to publish your paper!
https://github.com/kalu-o/mLEARn/pull/4

**Comment by kalu-o** [comment]
> @kalu-o 👋 – please merge this PR with minor edits, and I'l proceed to publish your paper!
> [kalu-o/mLEARn#4](https://github.com/kalu-o/mLEARn/pull/4)

@labarba --done.

**Comment by labarba** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @openjournals/jose-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/59

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/59, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/2647868.2654889 is OK

MISSING DOIs

- 10.1007/978-1-4613-8505-9_4 may be a valid DOI for title: Stochastic estimation of the maximum of a regression function
- 10.1109/icassp.2013.6638947 may be a valid DOI for title: Speech Recognition with Deep Recurrent Neural Networks
- 10.1163/156854293x00449 may be a valid DOI for title: Role of nonlinear dynamical properties of a modelled bursting neuron in information processing and storage
- 10.21236/ad0241531 may be a valid DOI for title: Adaptive switching circuits

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/60
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/jose.00059](https://doi.org/10.21105/jose.00059)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @kalu-o, your JOSE paper is published! 🚀 

Huge and sincere thanks to the Reviewers: @trallard, @rasbt — your contribution makes this adventure possible 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00059/status.svg)](https://doi.org/10.21105/jose.00059)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00059">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00059/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00059/status.svg
   :target: https://doi.org/10.21105/jose.00059
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00059/status.svg)](https://doi.org/10.21105/jose.00059)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-jose

**Comment by kalu-o** [comment]
> Congratulations, @kalu-o, your JOSE paper is published! 🚀
> 
> Huge and sincere thanks to the Reviewers: @trallard, @rasbt — your contribution makes this adventure possible 🙏

Thanks to the editor and reviewers for making this possible!

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
