### ISSUE TITLE
[PRE REVIEW]: BeamBending: a teaching aid for 1-D shear-force and bending-moment diagrams

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#60]
**Submitting author:** @alfredocarella (<a href="http://orcid.org/0000-0001-8340-3427">Alfredo Carella</a>)
**Repository:** <a href="https://github.com/alfredocarella/simplebendingpractice" target ="_blank">https://github.com/alfredocarella/simplebendingpractice</a>
**Version:** v1.0.0
**Editor:** @moorepants
**Reviewers:** @desgarcia, @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSE @alfredocarella. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@alfredocarella if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00060/jose.00060/10.21105.jose.00060.pdf)

**Comment by moorepants** [comment]
@labarba I can edit this one if you'd like and I have some people in mind that could review.

**Comment by labarba** [comment]
Excellent, @moorepants, thanks! 🚀

**Comment by labarba** [comment]
@whedon assign @moorepants as editor

**Comment by whedon** [comment]
OK, the editor is @moorepants

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00060/jose.00060/10.21105.jose.00060.pdf)

**Comment by alfredocarella** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00060/jose.00060/10.21105.jose.00060.pdf)

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #60 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.131/79b57ea0c878a4d1c6b821b76fb63e0aaa54b28e.shtml': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : 
  
  
  
  
  
  
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA Invalid bit depth (104)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.131/79b57ea0c87
8a4d1c6b821b76fb63e0aaa54b28e.shtml (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.497 ...a0c878a4d1c6b821b76fb63e0aaa54b28e.shtml}

Looks like we failed to compile the PDF

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00060/jose.00060/10.21105.jose.00060.pdf)

**Comment by alfredocarella** [comment]
Hi there! Thanks for starting the review process so promptly.
The paper includes a stubborn figure that keeps being placed at the end; sorry about that.

**Comment by moorepants** [comment]
@alfredocarella To fit as an "open-source learning module" you need to fit this criteria "Examples include Jupyter notebooks or plaintext/markup language documents like LaTeX, R Markdown, and ReST for course/lesson content and associated notes, with embedded or associated code snippets/programs." I'm not finding the documents + associated notes in your repository.

**Comment by alfredocarella** [comment]
@moorepants The lesson content is a chapter of the documentation (3 consecutive pages including code snippets) starting here: https://alfredocarella.github.io/simplebendingpractice/background.html
After going through that content, the concepts can be applied starting from this example: https://alfredocarella.github.io/simplebendingpractice/examples/example_1.html
which is also provided in the form of an online hosted Jupyter notebook.

**Comment by moorepants** [comment]
Ok, that's what I was looking for. Thank you. I think this meets the basic criteria, I'll round up some reviewers.

**Comment by moorepants** [comment]
FYI, I have four requests to review out and will update here if any agree.

**Comment by moorepants** [comment]
@faradai2008 or @nagordon, would either of you be interested in reviewing this article submitted to the Journal of Open Source Education on a package for teaching about beam bending mechanics?

**Comment by moorepants** [comment]
Destiny Garcia (@desgarcia) from UC Davis has agreed to be a reviewer. I'm still hoping to get one more additional reviewer.

Destiny, you can begin reviewing the submitted paper, software repository, and software documentation from the links above, but the review checklist will be created in a new github issue once I get the second reviewer (here is an example you can check out to see how it works: https://github.com/openjournals/jose-reviews/issues/44)

**Comment by moorepants** [comment]
@whedon assign @desgarcia as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @desgarcia

**Comment by moorepants** [comment]
@alfredocarella Do you have any other suggested reviewers?

**Comment by moorepants** [comment]
@nicoguaro Might you be interested in being a reviewer for this submission to the Journal of Open Source Education? I see that you have written a Python based continuum mechanics package that gives you unique experience for reviewing this similar software and materials.

**Comment by moorepants** [comment]
@buddyd16 Might you be interested in being a reviewer for this submission to the Journal of Open Source Education? I see that you have written a Python based structural engineering package that gives you unique experience for reviewing this similar software and materials.

**Comment by nicoguaro** [comment]
@moorepants I can review it.

**Comment by moorepants** [comment]
Fantastic! @nicoguaro Please read the reviewer guidelines here: http://jose.theoj.org/about#reviewer_guidelines and both reviewers should note that this is an "open-source educational materials/learning module" submission.

**Comment by moorepants** [comment]
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment]
OK, @nicoguaro is now a reviewer

**Comment by moorepants** [comment]
Now that we have two reviewers I will open the actual review issue with the checklist. @nicoguaro and @desgarcia, you can review at your own pace and bring up any discussions on the new issue. I would like to target two weeks for the reviews to be completed (by August 9th). Let me know if that will be an issue. Thank you again for your time and expertise in reviewing.

**Comment by moorepants** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/65. Feel free to close this issue now!

**Comment by moorepants** [comment]
Closing, if any other reviewers would like to join please respond in issue #65.

**Comment by alfredocarella** [comment]
@whedon generate pdf

I am sending the pdf generation command here in order to avoid polluting the other issue with useless output.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00060/jose.00060/10.21105.jose.00060.pdf)
