### ISSUE TITLE
[PRE REVIEW]: FAIR_Bioinfo: a turnkey training course and protocol for reproducible computational biology

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#63]
**Submitting author:** @thomasdenecker (<a href="http://orcid.org/0000-0003-1421-7641">Thomas DENECKER</a>)
**Repository:** <a href="https://github.com/thomasdenecker/FAIR_Bioinfo" target ="_blank">https://github.com/thomasdenecker/FAIR_Bioinfo</a>
**Version:** v1.2.0
**Editor:** @labarba
**Reviewers:** @k8hertweck, @lexnederbragt

**Author instructions**

Thanks for submitting your paper to JOSE @thomasdenecker. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@thomasdenecker if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00063/jose.00063/10.21105.jose.00063.pdf)

**Comment by labarba** [comment]
@whedon assign @k8hertweck as reviewer

**Comment by labarba** [comment]
@k8hertweck — Thank you for agreeing to review this submission for JOSE. We will want to find a second reviewer before starting the review (on a separate GitHub issue). But feel free to start looking at the submission, and browse our [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines). More soon!

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon add @lexnederbragt as reviewer

**Comment by whedon** [comment]
OK, @lexnederbragt is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/68. Feel free to close this issue now!
