### ISSUE TITLE
[PRE REVIEW]: Data Carpentry for Business (Python and SQL)

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#64]
**Submitting author:** @TacNayn (<a href="http://orcid.org/0000-0002-9520-5652">Hao Xi</a>)
**Repository:** <a href="https://github.com/data-lessons/SQL-business" target ="_blank">https://github.com/data-lessons/SQL-business</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @TacNayn. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@TacNayn if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00064/jose.00064/10.21105.jose.00064.pdf)

**Comment by labarba** [comment]
I'm having a little trouble finding all the materials and understanding how this submission is organized. The submission summary includes this note:

> Since the learning module contains two topics (one about SQL and one about Python), the contents are stored in two separate repositories. The submitted repository is the SQL learning module, another part is stored at https://zllu2.github.io/python-business/

That last URL points to a website. The "Edit on GitHub" link on the footer points to this repo: https://github.com/zllu2/python-business
... which is a fork of this one: https://github.com/data-lessons/python-business

The URL provided on submission (at the top of this issue) is:
 https://github.com/data-lessons/SQL-business
It's contents indicate to me there should be a website to go along with it, but I could not find a link to that website.

This organization is unhelpful for our review. Also, the JOSE workflow for publication ends with making an archive of the materials in a Zenodo deposit. Both the archive and the submission URL are linked to on the margin decorators of the first page. This workflow is unsuited for a submission that is spread to two separate repos.

Moreover, the SQL portion of this submission is based on "SQL for Ecology," while the Python pard is derived from "Python Novice Inflammation" and "Python of Ecology." Neither of these is published in JOSE. But readers would need to know how much of a derived work this is, and what is new.

**Comment by TacNayn** [comment]
Hello Lorena,  

Thanks for the reviews. I am sorry that the materials are messy... 
The website for SQL part is: https://data-lessons.github.io/SQL-business/ 
The website for Python part is: https://zllu2.github.io/python-business/

I am a little confused about how to organize the materials since we have one paper for two websites. Should I just submit one of it?   

"https://zllu2.github.io/python-business/" is the final version for the Python workshop. I previously made a draft on "https://github.com/data-lessons/python-business", but other people have been working on the forked repo (the zllu2 one) afterwards.  

Many Data Carpentry workshops are built based on others. But a lot of them are not in JOSE. Should I include a table in the paper to show what specific materials are derived?

**Comment by labarba** [comment]
👋 @TacNayn — It's been a long time getting back to you on this submission to JOSE, and for that I apologize. The members of the editorial board have been having a bunch of discussions, triggered by your submission. We also reached out to the team at Data Carpentry, and getting their reply also took time.

Here's the bottom line: we decided to _not_ put this submission through review. We came to the conclusion that we are uneasy with publishing in JOSE learning modules that are a remix of open materials by other authors who (1) are not co-authors of the remix, or (2) have not published the original work so it can be cited. 

Your submission raised a lot of discussion in the board. On one hand, we do want to encourage the remixing of openly licensed materials. That's the purpose of open sharing! On the other hand, JOSE was born to provide authorship credit to those who develop open learning content (or educational software). We will need to continue discussing how to handle the publication of remixed content. Should the developers of the original content be co-authors? (In open-source software, we might say yes.) If not, how should the previous authors be credited? Should we require that a substantial portion of the remix should be original materials? We still don't know the best answers to these questions, and for now, decided to hold back from publishing papers in this danger zone.

I hope you understand our predicament. If you are in touch with the authors of the original lessons you based your work on, perhaps you can encourage them to submit to JOSE. Or maybe you and they can be co-authors of a new submission. The bottom line is that we prefer if the original authors receive commensurate credit for their work, either in JOSE or elsewhere.
