### ISSUE TITLE
[REVIEW]: BeamBending: a teaching aid for 1-D shear-force and bending-moment diagrams

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#65]
**Submitting author:** @alfredocarella (<a href="http://orcid.org/0000-0001-8340-3427">Alfredo Carella</a>)
**Repository:** <a href="https://github.com/alfredocarella/simplebendingpractice" target ="_blank">https://github.com/alfredocarella/simplebendingpractice</a>
**Version:** v1.0.1
**Editor:** @moorepants
**Reviewer:** @desgarcia, @nicoguaro
**Archive:** <a href="https://doi.org/10.5281/zenodo.3383748" target="_blank">10.5281/zenodo.3383748</a>

## Status

[![status](http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5/status.svg)](http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5"><img src="http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5/status.svg)](http://jose.theoj.org/papers/8f3c2cbbcd7338364864a8c8e7155fa5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/alfredocarella/simplebendingpractice" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@desgarcia & @nicoguaro, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @moorepants know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alfredocarella/simplebendingpractice">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@alfredocarella) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/alfredocarella/simplebendingpractice">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@alfredocarella) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @desgarcia, @nicoguaro it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by nicoguaro** [comment]
@moorepants, should the repository include two license files?

@alfredocarella, do you have a DOI for your reference? Also, I would suggest another reference that is not in Norwegian, preferably in English.

**Comment by moorepants** [comment]
> @moorepants, should the repository include two license files?

I'm personally fine with a single license for all materials in the repository. Some people license code separately than other content (text, images, etc.). That is fine too.

**Comment by alfredocarella** [comment]
> @alfredocarella, do you have a DOI for your reference? Also, I would suggest another reference that is not in Norwegian, preferably in English.

@nicoguaro Sorry about the late answer. 
I have unfortunately not found any DOI for Bell's book, but its ISBN (978-82-450-1685-7) is given in the file `paper.bib`.
As you very well point out, it is probably a good idea to have a reference in English. I have therefore added "Statics and Mechanics of Materials" by F. Beer (ISBN 978-0-07-339816-7). The relevant sections (i.e. where the topic is introduced) are 12.1 and 12.2.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by nicoguaro** [comment]
@alfredocarella, it seems that the package only supports statically determined beams with (exactly) one pinned and one roller support. Maybe it is a good idea to explicitly mention this in the documentation and in the paper.

It seems a little bit confusing to me to use interchangeably pinned and fixed. Since the support doesn't constrain rotations.

**Comment by alfredocarella** [comment]
@nicoguaro, thanks for two useful comments. I have done the following to address them:
* The mentioned limitations in package scope (i.e. only statically determined beams with one pinned and one roller support) is now explicitly mentioned in the documentation, class docstrings, `paper.md`, and `README.md`.
* I have also changed all code and documentation references from "fixed support" to "pinned support", in hopes of making it clearer.

@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by nicoguaro** [comment]
@moorepants, I have some questions regarding the "common" practices in JOSE.

- How specific should the community guidelines be?

- Is it OK to suggest to use vector (instead of raster) graphics in the documentation? This would make easier to repurpose the lessons, and even let to automate the translation of them.

**Comment by nicoguaro** [comment]
@alfredocarella, I opened [issue #1](https://github.com/alfredocarella/simplebendingpractice/issues/1) regarding the tests.

I also have some comments regarding units, that might be important considering that this is educational content:

- Units should be preceded by a space (see [SI Brochure](http://www.bipm.org/en/si/si_brochure/), [§5.3.3](http://www.bipm.org/en/publications/si-brochure/section5-3.html)). This is done sometimes in the package/documentation and sometimes is not.

- The package assume a non-SI system of units (m, kN, kN·m). I think that a (brief) mention of the units would be useful.

- Units should be roman in roman type and not italic (see [this](https://physics.nist.gov/cuu/Units/checklist.html)). This is sometimes taken into account in the package/documentation and sometimes not.

**Comment by moorepants** [comment]
> How specific should the community guidelines be?

One way to handle this is to add a `CONTRIBUTING` file to the repository. It does not need to be elaborate and just needs to address the items in the checklist, even if is says that contributions aren't accepted.

> Is it OK to suggest to use vector (instead of raster) graphics in the documentation? This would make easier to repurpose the lessons, and even let to automate the translation of them.

It is fine to suggest this. It will depend on the author's response as to whether it is possible.

**Comment by moorepants** [comment]
@alfredocarella Can you please cite the primary software dependencies in the paper? Additionally, there are examples of existing software with similar capabilities that are not mentioned in your paper. I'd like to see citations to at least some of these and some note of what your work offers that distinguishes it from them.

**Comment by moorepants** [comment]
@desgarcia and @nicoguaro I see pretty solid progress in the checklists above. This is a reminder that we'd like to complete the reviews by this Friday if possible. Let me know if you have any questions or need help in any way. Can each of you respond here with a check in letting me know if you think you'll be able to finish by the end of Friday? Thank you for your time and expertise.

**Comment by nicoguaro** [comment]
@moorepants, if my comments (above and Issue tracker) are addressed I would be able.

**Comment by desgarcia** [comment]
@moorepants I should be able to complete by the end of the week!

**Comment by alfredocarella** [comment]
@nicoguaro @desgarcia @moorepants Thanks for the feedback. I will start addressing all your suggestions as soon as possible.

**Comment by moorepants** [comment]
@nicoguaro and @desgarcia Thank you very much for the timely reviews. I think that everything looks reasonable and that minor revisions are needed for publication. @alfredocarella Please address any issues posted on your repository, issues in this thread (including missing checkboxes in the list above). These are the main things I'm seeing:

- Adding/improving community contribution guidelines
- Improving the explanation of units
- Citing prior art
- Improving installation and getting started aspects
- Student feedback (if available)

Feel free to discuss with the reviewers and me anything in as you make your revision. Will an August 23rd date be suitable to finish the revisions by?

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by alfredocarella** [comment]
@moorepants @nicoguaro @desgarcia 
> @nicoguaro and @desgarcia Thank you very much for the timely reviews. I think that everything looks reasonable and that minor revisions are needed for publication. @alfredocarella Please address any issues posted on your repository, issues in this thread (including missing checkboxes in the list above). These are the main things I'm seeing:
> 
>     * Adding/improving community contribution guidelines
> 
>     * Improving the explanation of units
> 
>     * Citing prior art
> 
>     * Improving installation and getting started aspects
> 
>     * Student feedback (if available)
> 

* The (short) file ```CONTRIBUTING.md``` was added to the repository, in order to explicitly state that contributions are welcome. A small project like this will probably not benefit from having long and complex guidelines.
* The units in both documentation and generated plots are now in roman type, and preceded by a space. A brief comment has been added to the main class documentation, explicitly stating the (non-SI) units used by the package.
* The "Statement of Need" section of the paper includes now a brief comparison with similar available software (summarized in a table), including the main points that distinguish "beambending" from the rest.
* A link has been added to a tutorial on how to install Python 3 on either Linux, Windows or MacOS. Installation of the package can even be skipped altogether by just using the provided Jupyter notebook hosted on mybinder.
* No proper student feedback is available. The comments I received were oral, informal and unspecific. Real concrete examples are all along the lines of:
"I found it easy to check my answers to the practice problems", or "Playing around with the load shapes helped me visualize how distributed loads, shear force and bending moment are correlated"
However, I have no objective reason to assume that this feedback is representative or complete, since:
a) I did not receive a lot of comments (about a dozen, which is roughly 10 percent of the class), and
b) the comments are likely to be biased in a positive directions (few students spontaneously approach a teacher to tell him that his pet-project is terrible).

Additionally:
* Vector (instead of raster) graphics sounds like a good suggestion. I actually hoped to be able to do this in the first version. However, I found it quite time consuming to generate the vector figures. As of today the documentation consists of 14 figures. Five (5) of these are generated automatically by the package. Converting these to vector format is just a matter of replacing ".png" by (for example) ".svg" in the file name passed to the ```savefig``` function. The remaining 9 figures have been manually edited and would require some extra effort, but this should be manageable for the next update.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by nicoguaro** [comment]
Given the new inclusions to the paper, I have the following comments:

- I suggest adding bullet points/numerals to the second and to the last paragraphs on "Statement of Need".

- Table 1 is currently a figure instead of text. Is there a way to include this as text in the document?

- The inclusion of Table 1 provides a comparison of features with "similar" software. Nevertheless, it might be useful to add "bibliographic" information to those packages.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by alfredocarella** [comment]
@nicoguaro 
* Bullet points are now correctly added
* I would really like to add that table as text, but I have not been able to either embed latex in the markdown (the source code for the table is in the repository), or make that kind of table using markdown (which really results illegible without rotating the first row since the text is too long). Pasting a figure was a workaround, but I am willing to correct it if any of you can provide indication.
* The packages are now included in the References section

Additionally:
* The size and position of the figures is not great, but I have unfortunately not been able to do much better than that.

**Comment by nicoguaro** [comment]
@alfredocarella 
> 
>     * I would really like to add that table as text, but I have not been able to either embed latex in the markdown (the source code for the table is in the repository), or make that kind of table using markdown (which really results illegible without rotating the first row since the text is too long). Pasting a figure was a workaround, but I am willing to correct it if any of you can provide indication.

Can you share the LaTeX code? Maybe I can provide some ideas.


>     * The size and position of the figures is not great, but I have unfortunately not been able to do much better than that.

If you use SVG instead of PNG, does whedon compile the paper properly?

**Comment by alfredocarella** [comment]
> Can you share the LaTeX code? Maybe I can provide some ideas.
Here is the link to the LaTeX code: https://github.com/alfredocarella/simplebendingpractice/raw/master/tool_comparison_table.tex

> If you use SVG instead of PNG, does whedon compile the paper properly?

I am about to try exactly that... in a minute

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 [WARNING] Could not convert image '/tmp/tex2pdf.132/c310e5117c4761665cc36920e23e503fbd78ff9b.vs': Cannot load file
  Jpeg Invalid marker used
  PNG Invalid PNG file, signature broken
  Bitmap Invalid Bitmap magic identifier
  GIF Invalid Gif signature : <?xml 
  HDR Invalid radiance file signature
  Tiff Invalid endian tag value
  TGA No data detected in TGA file
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.132/c310e5117c4
761665cc36920e23e503fbd78ff9b.vs (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.537 ...0e5117c4761665cc36920e23e503fbd78ff9b.vs}

Looks like we failed to compile the PDF

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by alfredocarella** [comment]
@moorepants @nicoguaro @desgarcia 
Sorry about polluting the main issue with all the paper formatting attempts.
I believe all the issues and comments have been addressed, and the paper is ready for a second review.

**Comment by moorepants** [comment]
> @moorepants, is there any workaround to include SVG in the paper?

I don't know specifically. It should support anything that pandoc markdown supports.

**Comment by moorepants** [comment]
>  I believe all the issues and comments have been addressed, and the paper is ready for a second review.

@alfredocarella Great! Thank you for addressing all of the comments.

@nicoguaro and @desgarcia Can you all comment on whether the changes are sufficient? If not, please make any final specific suggestions. If there are no major issues I will recommend for publishing.

**Comment by moorepants** [comment]
> Table 1 is currently a figure instead of text. Is there a way to include this as text in the document?

I'm fine with it as an image. IMHO, the markdown format is extremely limiting and it is painful to create many of the things that are relatively easiy with LaTeX.

**Comment by nicoguaro** [comment]
@moorepants, I consider that the paper is ready for publication.

**Comment by nicoguaro** [comment]
@moorepants

> I don't know specifically. It should support anything that pandoc markdown supports.

It does not support it when compiling to LaTeX. I asked because I couldn't find any issue related to this in whedon's repo.

> I'm fine with it as an image. IMHO, the markdown format is extremely limiting and it is painful to create many of the things that are relatively easiy with LaTeX.

I'm also fine with it. I prefer the other option and that's why I asked. I also agree on the comment about markdown.

**Comment by moorepants** [comment]
>It does not support it when compiling to LaTeX. I asked because I couldn't find any issue related to this in whedon's repo.

I'd avoid it then. Maybe open an issue on the Whedon repo with a feature request?

> I'm also fine with it. I prefer the other option and that's why I asked.

if you can help get it working, go for it, but we shouldn't let this hold things up too much.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by desgarcia** [comment]
@moorepants I also agree with @nicoguaro , I think the paper is ready for publication

**Comment by moorepants** [comment]
@alfredocarella I see one error in a phrase on page 2: "as long as sympy <can> parse them"

**Comment by moorepants** [comment]
After fixing that, can you tag a release, submit an archived version to zenodo, and then share the DOI here?

**Comment by labarba** [comment]
Please also check the citation syntax.

When the citation is part of the sentence, then use: Author (year). If the citation is not part of the sentence, then it should appear in parenthesis. E.g. “We take inspiration from Smith et al. (2006) to … “ / 	“The code implements Theory 1 (Jones 2012) and Theory 2 (Roberts 2014) to obtain … “

For the syntax to obtain brackets in the right places, see https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax

**Comment by labarba** [comment]
What is meant by "a little intuitive sign conventions"? Do you mean _not_ intuitive? Intuitive but just a little? Please reword.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by alfredocarella** [comment]
> 
> 
> After fixing that, can you tag a release, submit an archived version to zenodo, and then share the DOI here?

@moorepants Done! The DOI is `10.5281/zenodo.3383748`
@labarba The suggested corrections have been made.

**Comment by moorepants** [comment]
One more minor fix. There is no date on your first reference in the bibliography, just empty parentheses.

**Comment by moorepants** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by moorepants** [comment]
@whedon set 10.5281/zenodo.3383748 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3383748" target="_blank">10.5281/zenodo.3383748</a> is the archive.

**Comment by moorepants** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/MCSE.2007.55 is OK
- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by alfredocarella** [comment]
> theses.

Sorry about that! Done.

**Comment by alfredocarella** [comment]
> 
> 
> One more minor fix. There is no date on your first reference in the bibliography, just empty parentheses.

Sorry about that. Done.

**Comment by alfredocarella** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00065/jose.00065/10.21105.jose.00065.pdf)

**Comment by moorepants** [comment]
Ok, great!

@alfredocarella Congratulations, I recommend your paper for publication in JOSE!

@nicoguaro and @desgarcia Thank you both for your volunteered time and thoughtful reviews!

It was a pleasure working with everyone.

@labarba This one is ready for acceptance, if you could do the honors :smile:.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/40

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/40, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/41
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00065](https://doi.org/10.21105/jose.00065)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @alfredocarella, your JOSE paper is published! 🚀 

Big thanks to our editor: @moorepants, and the reviewers: @desgarcia, @nicoguaro — we couldn't do this without you! 🙏 

Tweet announcing the publication:
https://twitter.com/JOSE_TheOJ/status/1168597259191275520

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00065/status.svg)](https://doi.org/10.21105/jose.00065)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00065">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00065/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00065/status.svg
   :target: https://doi.org/10.21105/jose.00065
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00065/status.svg)](https://doi.org/10.21105/jose.00065)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future.
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jose

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
