### ISSUE TITLE
[PRE REVIEW]: A course on the implicit finite volume method for CFD using Python

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#66]
**Submitting author:** @ctdegroot (<a href="http://orcid.org/0000-0002-2069-8253">Christopher DeGroot</a>)
**Repository:** <a href="https://bitbucket.org/cdegroot/cfdcourse" target ="_blank">https://bitbucket.org/cdegroot/cfdcourse</a>
**Version:** v1.0
**Editor:** @IanHawke
**Reviewers:** @sconde, @zingale

**Author instructions**

Thanks for submitting your paper to JOSE @ctdegroot. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ctdegroot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
@arfon Why is `whedon` unable to find the paper file? It is there in the repo ... is it a Bitbucket thing?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
Looks like the file is named `Paper.md` rather than `paper.md`. Whedon is case sensitive I'm afraid.

**Comment by labarba** [comment]
Thanks, Arfon!

👋 @ctdegroot — Could you please rename the file of your paper to `paper.md`?

**Comment by labarba** [comment]
You'll also need to rename the `.bib` file.

**Comment by ctdegroot** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00066/jose.00066/10.21105.jose.00066.pdf)

**Comment by ctdegroot** [comment]
@labarba Got that naming issue sorted. The PDF looks good.

For reviewers, I could suggest @kyleniemeyer, @sconde, or @TJFord to start. Also noticed that it flagged a lack of license file; I'll get that fixed up before the review begins.

**Comment by labarba** [comment]
👋 @IanHawke — could you handle this new JOSE submission as editor?

**Comment by labarba** [comment]
@whedon assign @IanHawke as editor

**Comment by whedon** [comment]
OK, the editor is @IanHawke

**Comment by labarba** [comment]
Thanks for agreeing to edit this for JOSE, @IanHawke ! 
Since this is your first one, a few notes:
- We'll want to identify two reviewers… we have a [list](https://bit.ly/jose-reviewers) of people who have signed up to review, but you're free to look outside that.
- For the first reviewer, use the command `@whedon assign <user> as reviewer` and for the second, run `@whedon add <user> as reviewer` (if you use `assign` the second time around, it will remove the original assignment).
- Once both are assigned, run `@whedon start review` and close this issue. A **Review** issue will be automatically created, with a review checklist for each reviewer.

**Comment by IanHawke** [comment]
Right, thanks for starting me off with what looks like a great course!

In addition to the license file, I'd suggest a `requirements.txt` or similar to get the environment set up: not essential.

**Comment by IanHawke** [comment]
@zingale: Mike, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education) ? This submission is about implicit methods for CFD and uses Python and Jupyter: I think you would be an excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.

Title: A course on the implicit finite volume method for CFD using Python
Summary: .A course on Computational Fluid Dynamics using Jupyter Notebooks and Python
Article Proof: https://github.com/openjournals/jose-papers/blob/jose.00066/jose.00066/10.21105.jose.00066.pdf
Submitting author: @ctdegroot  (Chris DeGroot)
Repository: https://bitbucket.org/cdegroot/cfdcourse

**Comment by IanHawke** [comment]
@sconde: Sidafa Conde, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education) ? This submission is about implicit methods for CFD and uses Python and Jupyter: this overlaps some of the expertise JOSE has listed for you, and I think you would be an excellent reviewer. Please see the [JOSE reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines) for details about the JOSE review process.

Title: A course on the implicit finite volume method for CFD using Python
Summary: .A course on Computational Fluid Dynamics using Jupyter Notebooks and Python
Article Proof: https://github.com/openjournals/jose-papers/blob/jose.00066/jose.00066/10.21105.jose.00066.pdf
Submitting author: @ctdegroot  (Chris DeGroot)
Repository: https://bitbucket.org/cdegroot/cfdcourse

**Comment by sconde** [comment]
> Sidafa Conde, are you able to and interested in taking on this review for JOSE (the Journal of Open Source Education)

@IanHawke I accept

**Comment by IanHawke** [comment]
Thank you @sconde ! The review will take place in another issue thread that will launch as soon as we have a second reviewer, but if you want to start the review already then feel free to link any issues that you create to this thread for now.

@whedon assign @sconde as reviewer

**Comment by labarba** [comment]
@whedon assign @sconde as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @sconde

**Comment by labarba** [comment]
👋 @IanHawke — `@whedon` likes its commands to come alone in a comment :–)

**Comment by zingale** [comment]
I can do a review too.  I'll be a little slow this week, but can finish the following.

**Comment by IanHawke** [comment]
@zingale : Thanks! Very happy that you can contribute to this.

**Comment by IanHawke** [comment]
@whedon add @zingale as reviewer

**Comment by whedon** [comment]
OK, @zingale is now a reviewer

**Comment by IanHawke** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/67. Feel free to close this issue now!

**Comment by IanHawke** [comment]
@sconde , @zingale : the review issue is now started at https://github.com/openjournals/jose-reviews/issues/67 . There is a detailed checklist there. Thanks for your help with this review!
