### ISSUE TITLE
[PRE REVIEW]: SedEdu: a suite of sediment-related educational modules

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#69]
**Submitting author:** @amoodie (<a href="http://orcid.org/0000-0002-6745-036X">Andrew Moodie</a>)
**Repository:** <a href="https://github.com/sededu/sededu" target ="_blank">https://github.com/sededu/sededu</a>
**Version:** v1.1.6
**Editor:** @labarba
**Reviewers:** @Swanson-Hysell

**Author instructions**

Thanks for submitting your paper to JOSE @amoodie. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@amoodie if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00069/jose.00069/10.21105.jose.00069.pdf)

**Comment by labarba** [comment]
👋  @amoodie — After reading your paper, I have some concerns. SedEdu is described as a set of activities, mediated by a software library, for students in the geosciences. Students, however, interact with the content via a GUI, rather than computationally. The focus of JOSE is in using computing (programmatically) to illuminate the learning context/subject. We don't have that here.  

Did you want JOSE to review this as a software contribution? (If so, the description as a set of activities doesn't align.) It would not be eligible in the category of learning module, as the learners don't use code directly.

**Comment by amoodie** [comment]
Hi @labarba. Yes, this is a software submission (I thought I had checked that box on submission?). SedEdu is a software framework that organizes learning activities. That is to say, it is an independent program that could exist without the activities. The framework is lightweight: it is a PyQt GUI that puts submodules into folders. I feel confident that SedEdu is ["open-source software that serves as educational technology"](https://github.com/openjournals/jose/blob/master/README.md#what-do-you-mean-by-open-source-educational-software-tools). 

Further, [in a pre-submission inquiry submitted to JOSS](https://github.com/openjournals/joss/issues/537), it was suggested to me that SedEdu could probably fit into JOSS, but was a direct fit for JOSE (of course, I understand that you were not a commenter on that thread). I agree with the commenters that SedEdu fits the spirit of JOSE: I think SedEdu is a really cool project (I am biased of course), and should be highlighted in a journal like JOSE.

I can appreciate your perspective that "the description as a set of activities doesn't align" with this being a software submission, but I think that to describe the software another way would be a disservice to the reader. To elaborate, I am not sure how to tell ["readers...how the content/software has been used, and how they would adopt it,"](https://github.com/openjournals/jose/blob/master/app/views/content/about/_paper_contents.html.erb#L29) ["the "story" of the project,"](https://github.com/openjournals/jose/blob/master/app/views/content/about/_paper_contents.html.erb#L16) or ["the functionality of the software, usage and recent experience of use in teaching and learning situations."](https://github.com/openjournals/jose/blob/master/app/views/content/about/_paper_contents.html.erb#L11) without describing that SedEdu comprises learning activities. I could definitely strip the discussion way down and just describe the core functionality of the software, but this would deprive the reader of understanding the application of the software.

Please advise on how to proceed, cheers.

**Comment by labarba** [comment]
Hi @amoodie — I'm sorry it's taken so long to get back to you. The beginning of the teaching semester has kept me playing catch-up.

It sounds like you want this submission to be reviewed as a software framework for organizing learning activities. That is, your intended users would be other instructors who want to develop such learning activities (and not the learners themselves). Is that correct? 

And in this scenario, the particular set of learning activities that you have developed showcase how the software framework might be used. But you are not submitting the learning activities themselves for review. Correct?

To be clear, as learning activities, my assessment is that they do not quite fit in the JOSE scope (learners do not use coding to learn, they interact with a GUI).

As a software framework to develop learning activities, it would fit the JOSE scope (as educational technology). But in that case, the title of the submission, and the paper itself needs to target the software (not the activities instantiated with the software).

HTH.

**Comment by amoodie** [comment]
@labarba thanks for getting back to me. You are correct, I want this to be a software submission. I will revise the paper and reply here when I have done so. Thanks.

**Comment by amoodie** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00069/jose.00069/10.21105.jose.00069.pdf)

**Comment by amoodie** [comment]
Hi @labarba, I have made revisions to the manuscript, to address your concerns. I believe this software is in line with the JOSE scope as educational infrastructure, and that the paper discusses the contribution in this context. Please let me know whether there is anything else I do, and I look forward to the review and improvement of the software and manuscript. Cheers, AM

**Comment by amoodie** [comment]
Hi @labarba, I just wanted to ping the thread and see if you had any update on the status of this review? Thanks, AM

**Comment by amoodie** [comment]
Hi @labarba, I think that @sharondenisse, @lheagy and/or @leouieda will be good reviewers for this paper, because they have listed geoscience as their background. The SedEdu software is written in PyQt; I didn't see anyone who listed this as experience.

Is it possible to have these folks review the submission? Thanks, and please let me know if there is anything I need to do to facilitate this review. Best, AM

**Comment by sharondenisse** [comment]
@amoodie, When is your due date for the review?

**Comment by lheagy** [comment]
Hi @amoodie, this looks like a really interesting project! Unfortunately I am swamped at the moment, so I can't take on the task of reviewing. You might consider reaching out so some of the folks in the CSDMS group: https://csdms.colorado.edu/wiki/Main_Page, as there seems like a fair bit of overlap in interests. Best of luck with your project!

**Comment by amoodie** [comment]
@sharondenisse, thanks for your interest in the paper! I am not an editor for JOSE, so I don't have the privilege of initiating the review, or setting a due date. I'm hoping that if some folks are interested in reviewing the paper, the review may be able to begin. 

@lheagy, thanks for considering, and for the link!

AM

**Comment by labarba** [comment]
@amoodie : Did you select the "software" category when you submitted? (if you selected the learning-module category, the review will get formed with the wrong checklist)

**Comment by amoodie** [comment]
@labarba I'm reasonably certain I checked that box.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@sharondenisse — Would you be interested in reviewing this submission? We like to ask for a 3-week review turnaround, but we realize that everyone is a volunteer here and we don't want to hurry you.

**Comment by amoodie** [comment]
Hi @labarba, is there anything I can do to help facilitate this review?

**Comment by labarba** [comment]
Thanks for the bump, @amoodie — I have sent two more reviewer enquiries via direct message.

**Comment by amoodie** [comment]
Hi @labarba, any luck identifying reviewers for this submission? Thanks!

**Comment by labarba** [comment]
Unfortunately, the people I have reached out to have declined to review. We're not having any luck yet identifying reviewers. I will keep trying!

**Comment by amoodie** [comment]
Hi @labarba, okay, thanks! Here is a short list I scraped together of folks you could try, if you haven't already contacted some of them. Thanks! 

@kbarnhart @mcflugen @nicgaspar @saisiddu @nathanlyons @cmshobe @amir-allam @mycarta @jessepisel @mdpiper

**Comment by amoodie** [comment]
Hi @labarba, I'm checking in to see if there is any movement on this review. Please let me know if you'd like me to suggest more potential reviewers. Thanks!

**Comment by labarba** [comment]
👋  To all who were mentioned in this JOSE Pre-Review thread — if you are not interested in contributing a review of this submission, please go ahead and Unsubscribe from the thread, to mute any further notifications to you. Cheers!

**Comment by labarba** [comment]
Nick @Swanson-Hysell — Would you be interested in contributing a review for The Journal of Open Source Education? https://jose.theoj.org

The submission is titled "SedEdu: a suite of sediment-related educational modules," and it presents a software framework for organizing learning activities, written in PyQt.
[Check out the article proof](https://github.com/openjournals/jose-papers/blob/jose.00069/jose.00069/10.21105.jose.00069.pdf), and the [software repository](https://github.com/sededu/sededu). If you're uninterested or unable to contribute a review, let us know, and then Unsubscribe from this thread to mute any further notifications.

For more information about the journal, see our [documentation](https://openjournals.readthedocs.io/en/jose/) pages.

Thanks! 🙏

**Comment by labarba** [comment]
👋 @grsharman — Might you be interested in contributing a review for The Journal of Open Source Education? The submission is titled "SedEdu: a suite of sediment-related educational modules," and it presents a software framework for organizing learning activities, written in PyQt.
Check out the [article proof](https://github.com/openjournals/jose-papers/blob/jose.00069/jose.00069/10.21105.jose.00069.pdf), and the [software repository](https://github.com/sededu/sededu). 

Read more about the journal in our documentation page: https://openjournals.readthedocs.io/en/jose/

**Comment by Swanson-Hysell** [comment]
Hi @labarba, I would be happy to serve as a reviewer for this manuscript/project. However, having read through the thread above I saw you make this point:

> It sounds like you want this submission to be reviewed as a software framework for organizing learning activities. That is, your intended users would be other instructors who want to develop such learning activities (and not the learners themselves). Is that correct?

> And in this scenario, the particular set of learning activities that you have developed showcase how the software framework might be used. But you are not submitting the learning activities themselves for review. Correct?

> To be clear, as learning activities, my assessment is that they do not quite fit in the JOSE scope (learners do not use coding to learn, they interact with a GUI).

The way that I would be interested in providing input is in the context of the learning activities. Reviewing it as a "software framework" alone without that disciplinary context effectively means that I would be reviewing the concept of having GUIs that can be accessed from a dialog box for which I wouldn't have much to say. I can see the value in having GUIs wherein the student can vary parameters to run a model under the hood in the context of sedimentology. However, if that type of learning activity doesn't fit with the scope of the journal and isn't what I would be assessing, I am not sure what I would actually be assessing.

**Comment by amoodie** [comment]
Hi @labarba, I was hoping to get an update on the status of this manuscript submission and see if we could identify reviewers. I realize everyone is working double time now with end-of-semester duties and an extra burden from life, but just wanted to provide another gentle nudge! Thanks, AM.

**Comment by jessepisel** [comment]
Howdy @amoodie and @labarba I have time to review this submission now that the semester has ended. Would I be reviewing it as a software module, or as a learning module as discussed above?

**Comment by amoodie** [comment]
Thanks @jessepisel, I appreciate your willingness to review! When I submitted, I intended this to be a software submission, but perhaps JOSE's policy has changed since then. 

Excited to see what @labarba says, seems like we have two reviewers now?

**Comment by amoodie** [comment]
Hi @labarba,

I wanted to provide a gentle nudge and see if I could do anything to help facilitate this review. It seems like we may have found two people willing to review, but the window may be closing there, as the summer winds to a close. 

Some exciting news is that additional work on SedEdu (including software development and new modules) was recently funded as past of an NSF Postdoc Fellowship that I received. I will begin this work next month, and it would be really great to see v1.x published in JOSE, so that we can use the paper to help advertise to potential collaborators before we begin to work aggressively on the platform.

Thanks very much, hope to not be too much of a nudge here.

**Comment by amoodie** [comment]
Hi @labarba, is it possible to request an update on the status of this review? With more than 13 months in pre-review, would it be possible to have the submission passed to another editor focused on JOSE reviews at the moment?

Thanks for your time and support in getting our project published in JOSE!

**Comment by Swanson-Hysell** [comment]
> @Swanson-Hysell — you considered last year contributing a review for the Journal of Open Source Education. Upon our agonizing over the journal scope, I dropped the ball on this one. We now decided to move ahead with the submission as it is intended to be used: learning activities in sediment transport. Might you be able to help us out?

Hi @labarba, yes. I can provide a review associated with the submission. @amoodie has there been progress on the project since your July 29, 2020 message where you indicated that more development was planned? It looks like the last commit was Feb 27, 2020.

**Comment by labarba** [comment]
Thank you so much, Nick! I will assign you and start the review, and maybe @amoodie can reply to your queries there.

**Comment by labarba** [comment]
@whedon assign @Swanson-Hysell as reviewer

**Comment by whedon** [comment]
OK, @Swanson-Hysell is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/129.

**Comment by amoodie** [comment]
@Swanson-Hysell unfortunately no, progress on this has slipped in the chaos of the last year. Eventually we will, though, because SedEdu modules are part of broader impacts on two current NSF Postdoc projects (mine included). Thanks for agreeing to review!

**Comment by jessepisel** [comment]
Howdy @labarba  I apologize unfortunately I do not have the bandwidth right now to assist with a review on this project.
