### ISSUE TITLE
[REVIEW]: DraggleSimulator: An Open Source Web Application for Teaching Genetic Drift

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#70]
**Submitting author:** @Atticus29 (<a href="http://orcid.org/0000-0002-7138-7025">M.A. Fisher</a>)
**Repository:** <a href="https://github.com/Atticus29/population-fragmentation" target ="_blank">https://github.com/Atticus29/population-fragmentation</a>
**Version:** v1.0.1
**Editor:** @magsol
**Reviewers:** @AstrobioMike, @wallacelab
**Archive:** <a href="https://doi.org/10.5281/zenodo.3523488" target="_blank">10.5281/zenodo.3523488</a>

## Status

[![status](http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba/status.svg)](http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba"><img src="http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba/status.svg)](http://jose.theoj.org/papers/2b64c5d5657f506b0d0e8418b02642ba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Atticus29/population-fragmentation" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@AstrobioMike, @luizirber, and @wallacelab, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @magsol know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Atticus29/population-fragmentation">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@Atticus29) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Atticus29/population-fragmentation">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** v1.0.1
- [ ] **Authorship:** Has the submitting author (@Atticus29) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [ ] **Example usage:** Do the authors include examples of how to use the software?
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Atticus29/population-fragmentation">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v1.0.1
- [x] **Authorship:** Has the submitting author (@Atticus29) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @AstrobioMike, @luizirber it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00070/jose.00070/10.21105.jose.00070.pdf)

**Comment by magsol** [comment]
@whedon add @wallacelab as reviewer

**Comment by whedon** [comment]
OK, @wallacelab is now a reviewer

**Comment by AstrobioMike** [comment]
Hi all,

In my opinion, this is all set to go. Things can be used on the hosted site perfectly as explained in the readme and nicely demonstrated in the [youtube video](https://www.youtube.com/watch?v=izER-V9PTxs&feature=youtu.be). 

At the end of the readme there is a section on [how to host your own](https://github.com/Atticus29/population-fragmentation#how-to-set-up-your-own-instance-of-dragglesimulator-in-amazon-web-services) through amazon web services (AWS), which I had some trouble with. But that seems to me to be a completely extra, optional avenue, and not part of the core material or site that most people would use, so I don't think that should be an impediment to publication in JOSE. There are a lot of AWS-specific hurdles in the mix there like setting up the S3 bucket and setting up your IAM credentials – which the [readme notes](https://github.com/Atticus29/population-fragmentation#how-to-set-up-your-own-instance-of-dragglesimulator-in-amazon-web-services) in point #5 is demonstrated in the above linked video for setting up an S3 bucket, but is not. I needed to create an IAM user, which involved making a group and setting permissions and such which was not straightforward. After getting that, I also ran into issues with `ng build`, which led to a web of dependency and version problems related to angular that I eventually gave up on. 

Again, everything works fine on the already-hosted site, and this section just seems to be completely optional information out of kindness, there for those who might want to set up their own. I don't see this as a core part of the educational program being offered here, and therefore don't think it should affect its publication in JOSE. 

Regarding specific boxes left unchecked above by me as of this comment:

I left Version unchecked because the repo doesn't list any releases yet, maybe @Atticus29 is waiting for the review process to be done.

I left Installation and Installation Instructions left unchecked because there really is no installation to use the main platform that is already hosted. So i don't think these boxes are relevant, let me know if i should just check them if that's the case. 

Minor notes for @Atticus29:

- Maybe add definition of “Population fragmentation” to the nice definitions page you have. And in there define “fragments” as used here, and its relation to subpopulations. For instance on the Create a Population page, it says to specify the number of fragments, but I wasn’t sure what was meant by that at first. 

- In line with that, maybe there is room for more continuity in usage of “fragments” vs “subpopulations”. For instance on the Answer a Few Questions page, it has “Fragment Number” in the table as a column, but asks questions about “subpopulation”. There may be more nuanced reasons you’re using these the way you are that I’m just naive to, in which case of course ignore the suggestion :) 

Cool site, @Atticus29!

**Comment by wallacelab** [comment]
I agree that this seems pretty much ready to go. End-user use is pretty straightforward and well documented. I didn't attempt the AWS installation because of the issues pointed out by @AstrobioMike, but the other aspects seem solid. (I was able to use custom Google sheets & forms, as advertised.)

Specific boxes I left unchecked:

- Version number: Not included for the reasons @AstrobioMike mentions
- Automatic tests: No automatic tests have been implemented according to the README
- References: The paper.md file seems to be lacking the reference to Hardy-Weinberg 1908. (It has an in-line citation but nothing under "references")

Other minor notes for potential improvement:
- On the definitions page, the last two terms ("sampling error" and "expected heterozygosity") have much longer, more involved definitions that don't seem to fit with the pattern of the others. ("Sampling error" especially was jarring since it takes most of the paragraph to get to the definition.) I'd recommend giving each of them a simple, succinct definition like the others, and put the longer explanation as a sub-bullet underneath.
- On the Draggle images, the spots seem a bit small and hard to see; I'd recommend making them much larger (see example image), using brighter shades of blue (cyan?) and green, and/or maybe making them thick stripes instead of spots. (Basically, just making them glaringly obvious.)
![draggle](https://user-images.githubusercontent.com/14350494/65637198-c80cd380-dfb1-11e9-816c-1210b531469c.png)
(The stripes may be overkill, but you get the idea.)

**Comment by Atticus29** [comment]
Thanks so much for the feedback so far, @wallacelab and @AstrobioMike! Useful and much appreciated!
Today, I changed some of the wording re: fragement vs. subpopulation, shortened some of the definitions, and increased the radius of the spots by >=2x. It does look better that way, I think.
I also released v.1.0.0 in the repo.

**Comment by Atticus29** [comment]
Attempting to see whether my syntax change in the paper.bib file fixes the citation issue?...

@whedon generate pdf

**Comment by Atticus29** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by Atticus29** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00070/jose.00070/10.21105.jose.00070.pdf)

**Comment by labarba** [comment]
@magsol — what is the status of this review? I see all reviewers have some items missing from their checklist. Could you check with them?

**Comment by Atticus29** [comment]
> @magsol — what is the status of this review? I see all reviewers have some items missing from their checklist. Could you check with them?

Thanks for the follow up, @labarba! Should I wait for @luizirber to weigh in as the final reviewer, or continue responding to the reviews I have?

**Comment by luizirber** [comment]
I agree with @magsol. I can't review this before next week, and since the other reviewers already gave feedback I think I should be removed as a reviewer.

**Comment by magsol** [comment]
@whedon remove @luizirber as reviewer

**Comment by magsol** [comment]
Ok, it's definitely time to move forward on this.

First, can @AstrobioMike and @wallacelab please **confirm** your recommendations in favor of acceptance?

@whedon generate pdf

**Comment by magsol** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by magsol** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by magsol** [comment]
The article proof looks good and reads well to me. References and DOIs are in place.

**Comment by wallacelab** [comment]
Also confirmed.

**Comment by magsol** [comment]
Awesome, thank you @AstrobioMike and @wallacelab!

@Atticus29: would you please make a tagged release and archive, and post both in this thread? Keeping it at 1.0 is fine, just let me know if that's what you decide.

**Comment by Atticus29** [comment]
@magsol awesome! Thanks! I just released a new version (1.0.1): https://github.com/Atticus29/population-fragmentation/releases/tag/v1.0.1
Created an archive in zenodo:
http://doi.org/10.5281/zenodo.3523488

Hopefully it's ok that I'm the one doing this?:

@whedon set v1.0.1 as version
@whedon set 10.5281/zenodo.3523488 as archive

**Comment by Atticus29** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
I'm sorry @Atticus29, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by Atticus29** [comment]
Whoops. Good to know haha!

**Comment by magsol** [comment]
@whedon set 10.5281/zenodo.3523488 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3523488" target="_blank">10.5281/zenodo.3523488</a> is the archive.

**Comment by magsol** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by labarba** [comment]
@AstrobioMike, @wallacelab — I see you recommended publication, but your checklists have a couple of unchecked items. Are you OK checking those off?

**Comment by AstrobioMike** [comment]
I don’t think the installation boxes are relevant here (detailed in response [here](https://github.com/openjournals/jose-reviews/issues/70#issuecomment-533836711). Should I just check them anyway?

**Comment by wallacelab** [comment]
Okay

**Comment by magsol** [comment]
@labarba Looks like we're all checked off.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1126/science.28.706.49 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/45

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/45, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/46
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00070](https://doi.org/10.21105/jose.00070)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @Atticus29, your paper is published! 🚀 

Heartfelt thanks to our editor: @magsol, and reviewers: @AstrobioMike, @wallacelab — your contribution to JOSE is greatly appreciated 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00070/status.svg)](https://doi.org/10.21105/jose.00070)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00070">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00070/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00070/status.svg
   :target: https://doi.org/10.21105/jose.00070
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00070/status.svg)](https://doi.org/10.21105/jose.00070)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future.
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-jose

**Comment by labarba** [comment]
https://twitter.com/JOSE_TheOJ/status/1192514412747341825

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
