### ISSUE TITLE
[PRE REVIEW]: General relativity in R: visual representation of Schwarzschild space using different coordinate systems

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#71]
**Submitting author:** @RobinHankin (<a href="http://orcid.org/0000-0001-5982-0415">Robin Hankin</a>)
**Repository:** <a href="https://github.com/RobinHankin/schwarzschild" target ="_blank">https://github.com/RobinHankin/schwarzschild</a>
**Version:** 1.0-1
**Editor:** @IanHawke
**Reviewers:** @atrisovic, @afolkest

**Author instructions**

Thanks for submitting your paper to JOSE @RobinHankin. **Currently, there isn't an JOSE editor assigned** to your paper.

@RobinHankin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00071/jose.00071/10.21105.jose.00071.pdf)

**Comment by labarba** [comment]
👋  @RobinHankin — the paper mentions that the software is under GPL, but there's no LICENSE file in the repository. Could you add that?

**Comment by RobinHankin** [comment]
now added, sorry about that. I thought it was understood to be under GPL.

<hankin.robin@gmail.com>
hankin.robin@gmail.com

<hankin.robin@gmail.com>

<hankin.robin@gmail.com>

**Comment by labarba** [comment]
@IanHawke — The submitting author suggested you as handling editor. Could you have a look and let me know if you can take it?

**Comment by IanHawke** [comment]
I'm on it. I will start contacting potential referees, which will initially be by email (for the first couple I try).

**Comment by labarba** [comment]
@whedon assign @IanHawke as editor

**Comment by whedon** [comment]
OK, the editor is @IanHawke

**Comment by IanHawke** [comment]
I am closing in on reviewers (most GR people are claiming no knowledge of R), and hope to twist some arms in person at a conference next week.

**Comment by IanHawke** [comment]
I have one referee agreed in principle but needs to check time availability for the New Year, and two thinking about it. Will come back to this in the New Year.

**Comment by RobinHankin** [comment]
thanks for this Ian.  I appreciate the difficulty of finding an
intersection between R and GR (!) but this is one reason why I wrote the
package.

Best wishes for 2020

Robin
<hankin.robin@gmail.com>
hankin.robin@gmail.com

<hankin.robin@gmail.com>

<hankin.robin@gmail.com>

**Comment by RobinHankin** [comment]
Ian, sorry to bother you but can I check on the progress of my submission please?

**Comment by atrisovic** [comment]
Hi Robin - I guess this is the beauty of open review - I was checking out this repository and I think it would be great if you had some examples of diagrams (visual representations) in your paper! :-))

**Comment by RobinHankin** [comment]
hello atrisovic, are you asking for illustrations of Minkowski diagrams, as used in special relativity?

**Comment by atrisovic** [comment]
Hi Robin,

Here are my initial thoughts: 

- I don't mean specifically Minkowski diagram, but this is a paper on visual representation, so it would be helpful to see figures and diagrams that the package can produce in a few examples
- The paper doesn't say what R version the package is compatible with. This is important because R is not normally backward compatible. For example, can I run it with R 4.0?
- The paper mentions rich documentation for the code, but there is no link to the documentation

**Comment by RobinHankin** [comment]
* have you seen the vignette? this has 19 figures in it.   Just type `vignette("schwarzschild")` at the commandline 
* The version of R is not crucial, it will work with any verson of R >=3.0
* The documentation is in standard Rd format, accessible through the usual R help mechanism

HTH

Robin

**Comment by kyleniemeyer** [comment]
Hi @IanHawke, @atrisovic has volunteered to serve as a reviewer for this submission (in an email discussion), and I think we should absolutely take her up on this, particularly considering she's already participating!

**Comment by kyleniemeyer** [comment]
@afolkest would you be willing to help out with a review for this as well?

**Comment by afolkest** [comment]
Sure, I can do that!

**Comment by atrisovic** [comment]
Awesome! Thank you, Kyle! I think this is an interesting topic, and it would certainly warrant more text in the paper (this [previously published paper](https://jose.theoj.org/papers/10.21105/jose.00065) could be a good example).

No time to waste, so here are a few more thoughts: 
- Mathematica is typically used for creating these diagrams. Are there any advantages to using this R package instead, and what are those?
- There is a note on how the package was used, but it would also be helpful to see who the intended user group is? Is it the teachers and the undergrads? Students of astrophysics and HEP? Can the tool be used for some more advanced research?

**Comment by IanHawke** [comment]
Thanks all for picking this up where I'd dropped the ball on it. I will check the next steps asap.

**Comment by IanHawke** [comment]
@whedon assign @atrisovic as reviewer

**Comment by whedon** [comment]
OK, @atrisovic is now a reviewer

**Comment by IanHawke** [comment]
@whedon add @afolkest as reviewer

**Comment by whedon** [comment]
OK, @afolkest is now a reviewer

**Comment by IanHawke** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/91.

**Comment by IanHawke** [comment]
Once again, many thanks to @atrisovic and @afolkest for agreeing to review. The actual review issue will be at #91 .
