### ISSUE TITLE
[PRE REVIEW]: EduCortex: browser-based 3D brain visualization of fMRI meta-analysis maps

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#72]
**Submitting author:** @PaulScotti (<a href="http://orcid.org/0000-0003-4912-8809">Paul Scotti</a>)
**Repository:** <a href="https://github.com/PaulScotti/EduCortex" target ="_blank">https://github.com/PaulScotti/EduCortex</a>
**Version:** v1.0.0
**Editor:** @magsol
**Reviewers:** @tliu23, @TomDonoghue, @arokem

**Author instructions**

Thanks for submitting your paper to JOSE @PaulScotti. **Currently, there isn't an JOSE editor assigned** to your paper.

@PaulScotti if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #72 with the following error: 

 Can't find any papers to compile :-(

**Comment by PaulScotti** [comment]
Could someone let me know why whedon is unable to find any papers to compile? Is it because the repository listed is [github.com/PaulScotti/EduCortex](url) and not [](https://github.com/PaulScotti/EduCortex) ?

**Comment by kyleniemeyer** [comment]
I think the repo URL is configured with JOSE/whedon incorrectly, since the link above directs to https://github.com/openjournals/jose-reviews/issues/github.com/PaulScotti/EduCortex (rather than https://github.com/PaulScotti/EduCortex)

**Comment by kyleniemeyer** [comment]
@openjournals/dev is it possible to change the repo URL? I don't see an option in the editors dashboard

**Comment by PaulScotti** [comment]
@kyleniemeyer Thanks Kyle -- can I just reupload the paper with a correct repo URL and have this one get canceled? It might be quicker that way.

**Comment by arfon** [comment]
You can just edit the top of the issue here (I will go ahead and do this).

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00072/jose.00072/10.21105.jose.00072.pdf)

**Comment by PaulScotti** [comment]
Thanks @arfon very much for fixing the issue!

In the meantime, since an editor has yet to be assigned to this paper, I realized that the paper could benefit from an explicit "Statement of Need" section in line with the submission instructions. I just now added this section to the paper, if the future editor could please regenerate the pdf.

Thanks,
Paul

**Comment by arfon** [comment]
@PaulScotti - you can ask Whedon to generate a new PDF preview by typing:

```
@whedon generate pdf 
```

**Comment by PaulScotti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00072/jose.00072/10.21105.jose.00072.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.3389/fninf.2015.00023 may be missing for title: Pycortex: an interactive surface visualizer for fMRI
- https://doi.org/10.1016/s1364-6613(03)00134-7 may be missing for title: The visual word form area: expertise for reading in the fusiform gyrus

INVALID DOIs

- None
```

**Comment by PaulScotti** [comment]
Anything I can do to help assign an editor to this review process? Here are some possible suggested reviewers, if that helps? @arokem @TomDonoghue @eglerean @mnarayan @djmannion

**Comment by magsol** [comment]
@whedon assign @magsol as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by magsol** [comment]
Yes, @PaulScotti, very sorry about the delay. I'm still getting my semester up and running but given a reviewer or two I have in mind who specialize in computational neuroscience, plus the very helpful list you provided me, I'm hoping we can have things going in the next couple days.

**Comment by magsol** [comment]
@whedon assign @tliu23 as reviewer

**Comment by whedon** [comment]
OK, @tliu23 is now a reviewer

**Comment by magsol** [comment]
@whedon add @TomDonoghue as reviewer

**Comment by whedon** [comment]
OK, @TomDonoghue is now a reviewer

**Comment by magsol** [comment]
@whedon add @arokem as reviewer

**Comment by whedon** [comment]
OK, @arokem is now a reviewer

**Comment by magsol** [comment]
@whedon start review

**Comment by magsol** [comment]
@whedon start review

**Comment by labarba** [comment]
@openjournals/dev — Something is going awry here: `whedon` is not responding to the `start review` common. Can you help?

**Comment by arfon** [comment]
@labarba @magsol - could you try again now?

**Comment by magsol** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/75.

**Comment by magsol** [comment]
Hooray! Thanks @arfon
