### ISSUE TITLE
[PRE REVIEW]: Game Theory and Python: An educational tutorial to game theory and repeated games using Python

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#73]
**Submitting author:** @Nikoleta-v3 (<a href="http://orcid.org/0000-0002-2943-3622">Nikoleta E. Glynatsi</a>)
**Repository:** <a href="https://github.com/Nikoleta-v3/Game-Theory-and-Python" target ="_blank">https://github.com/Nikoleta-v3/Game-Theory-and-Python</a>
**Version:** v.0.0.1
**Editor:** @racheltho
**Reviewers:** @sconde , @gvdr

**Author instructions**

Thanks for submitting your paper to JOSE @Nikoleta-v3. **Currently, there isn't an JOSE editor assigned** to your paper.

@Nikoleta-v3 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/jose-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00073/jose.00073/10.21105.jose.00073.pdf)

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.5281/zenodo.1405868 is OK

MISSING DOIs

- https://doi.org/10.3200/jece.35.3.259-268 may be missing for title: Active learning with Monty Hall in a game theory class
- https://doi.org/10.21100/msor.v14i1.254 may be missing for title: Playing Games: A Case Study in Active Learning Applied to Game Theory

INVALID DOIs

- None
```

**Comment by Nikoleta-v3** [comment]
Potential reviewers include: 

- `marcharper` 
- `eric-s-s`
- `gaffney2010`

These individuals are collaborators of `Axelrod-Python` which is the main software used in the tutorials. Please note that `marcharper` is also a mentor and a collaborator of mine and there is possible a conflict of interest.

**Comment by Nikoleta-v3** [comment]
Hello @labarba and @kyleniemeyer ,

I understand that you must be extremely busy, but I was wondering when an editor will be assigned to our paper?

**Comment by labarba** [comment]
hey, @Nikoleta-v3 — I do apologize for letting this submission linger in the queue for so long. It's all my fault, for taking on some big service commitments and giving lower priority to my own initiatives. Here's one big reason: I'm JupyterCon 2020 General Chair! We [just announced](https://twitter.com/JupyterCon/status/1225901511437410304?s=20). Anyway, no excuse.

👋 @racheltho — I wonder if you could take this as your first JOSE assignment as editor? I would be of course ready to help at every step of the way
Submission title: **"Game Theory and Python: An educational tutorial to game theory and repeated games using Python"**

**Comment by Nikoleta-v3** [comment]
That's okay @labarba! Congratulations for JupyterCon 2020!! 👏 🎉

**Comment by racheltho** [comment]
I apologize that I didn't see the notification for this at the time.  I will take a look in the next few days!

**Comment by racheltho** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by racheltho** [comment]
@whedon start review

**Comment by racheltho** [comment]
@whedon generate pdf

**Comment by labarba** [comment]
Hi @racheltho — first, let me assign you as editor.

Then, the next step is to find reviewers, and assign them here.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00073/jose.00073/10.21105.jose.00073.pdf)

**Comment by labarba** [comment]
After assigning the reviewers, you will do `@whedon start review`, which will create a new REVIEW issue, with the reviewer checklists, and will give the reviewers the necessary permissions to check off items in their list.

**Comment by labarba** [comment]
@whedon assign @racheltho as editor

**Comment by whedon** [comment]
OK, the editor is @racheltho

**Comment by labarba** [comment]
Now that you are editor, you have the "powers" to assign/add reviewers, and start the review.

**Comment by labarba** [comment]
You can contact potential reviewers via email, Twitter, or mention them in this issue to invite them. Once they agree, you will run `@whedon assign <user> as reviewer` for the first one, and `@whedon add <user> as reviewer` for the second one (we usually want two reviewers).

More help in our Documentation's [Editorial Guide](https://openjournals.readthedocs.io/en/jose/editing.html)

**Comment by racheltho** [comment]
Hi @sconde, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is: Game Theory and Python: An educational tutorial to game theory and repeated games using Python. Let me know if you're available and willing. Thanks!

**Comment by sconde** [comment]
> Hi @sconde, you signed up to review for JOSE. Would you like to contribute a review for this submission?

yes!

**Comment by racheltho** [comment]
@whedon assign @sconde  as reviewer

**Comment by whedon** [comment]
OK, @sconde  is now a reviewer

**Comment by labarba** [comment]
Great going with your first editing for JOSE, @racheltho 🚀

A pro tip: you should find a second reviewer and run `@whedon add <user> as reviewer` here, _before_ running `@whedon start review`. That way, the review issue will be started with an individual checklist for each reviewer. Godspeed!

**Comment by racheltho** [comment]
Hi @gvdr, you signed up to review for JOSE. Would you be able to be a reviewer for this submission? The title is: Game Theory and Python: An educational tutorial to game theory and repeated games using Python. Let me know if you're available and willing. Thanks!

**Comment by gvdr** [comment]
Yes, will do!
----
Giulio Valentino Dalla Riva
Lecturer in Data Science
School of Mathematics and Statistics
University of Canterbury
Ōtautahi, Aotearoa -- Christchurch, New Zealand

----
Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
https://tutanota.com



25 Feb 2020, 11:44 by notifications@github.com:

**Comment by racheltho** [comment]
@whedon add @gvdr as reviewer

**Comment by whedon** [comment]
OK, @gvdr is now a reviewer

**Comment by racheltho** [comment]
@whedon start review

**Comment by labarba** [comment]
@openjournals/dev We have a delay here in `@whedon` starting the review. Can you check for us what could be the snag?

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/78.

**Comment by arfon** [comment]
> @openjournals/dev We have a delay here in `@whedon` starting the review. Can you check for us what could be the snag?

Apologies for the minor hiccup. Things should be working normally now.
