### ISSUE TITLE
[PRE REVIEW]: The Gene School: Metagenomics

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#77]
**Submitting author:** @koadman (<a href="http://orcid.org/0000-0003-2397-7925">Aaron Darling</a>)
**Repository:** <a href="https://github.com/thegeneschool/metagenomics" target ="_blank">https://github.com/thegeneschool/metagenomics</a>
**Version:** v0.0.1
**Editor:** @emckiernan
**Reviewers:** @hughshanahan, @pschloss

**Author instructions**

Thanks for submitting your paper to JOSE @koadman. **Currently, there isn't an JOSE editor assigned** to your paper.

The author's suggestion for the handling editor is @tracykteal.

@koadman if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (468.9 files/s, 54044.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                        11            403              0           1040
TeX                              1              9              0            139
YAML                             1              5              1             66
Bourne Shell                     1              8              0             55
CSS                              1              0              0              3
-------------------------------------------------------------------------------
SUM:                            15            425              1           1303
-------------------------------------------------------------------------------


Statistical information for the repository '77' was gathered on 2020/02/09.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1186/s13059-019-1643-1 is OK
- 10.1093/bioinformatics/btw354 is OK
- 10.1186/s13059-019-1891-0 is OK
- 10.1038/nmeth.2066 is OK
- 10.1093/bioinformatics/btv033 is OK
- 10.7717/peerj.7359 is OK
- 10.7717/peerj.1319 is OK
- 10.1093/bioinformatics/bty560 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00077/jose.00077/10.21105.jose.00077.pdf)

**Comment by labarba** [comment]
@whedon assign @emckiernan as editor

**Comment by whedon** [comment]
OK, the editor is @emckiernan

**Comment by emckiernan** [comment]
Hi, @AstrobioMike, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is "The Gene School: Metagenomics". Let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
Hi, @HadrienG, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is "The Gene School: Metagenomics". Let me know if you're available and willing. Thanks!

**Comment by HadrienG** [comment]
Hi! I'm writing my thesis and getting close to defending, I'll unfortunately not have time for reviewing this.

**Comment by emckiernan** [comment]
> Hi! I'm writing my thesis and getting close to defending, I'll unfortunately not have time for reviewing this.

Thanks for letting us know. Good luck with the thesis and defense!

**Comment by emckiernan** [comment]
Hi, @Hughshanahan, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is "The Gene School: Metagenomics". Let me know if you're available and willing. Thanks!

**Comment by hughshanahan** [comment]
Hi Erin
            yes please. To note I won’t be able to get to this until next week.

Hugh
__________________________
Hugh Shanahan
Professor of Open Science
( he | his )
Hugh.Shanahan@rhul.ac.uk<mailto:Hugh.Shanahan@rhul.ac.uk>
http://www.shanahanlab.org
@hughshanahan
Skype hugh_shanahan
Tel +44 (0)1784 443433
orcid.org/0000-0003-1374-6015<http://orcid.org/0000-0003-1374-6015>

Emails sent outside of office hours are not an expectation that you should process this outside of office hours.





On 26 Feb 2020, at 13:29, Erin C. McKiernan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, @hughshanahan<https://github.com/hughshanahan>, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is "The Gene School: Metagenomics". Let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
@whedon assign @hughshanahan as reviewer

**Comment by whedon** [comment]
OK, @hughshanahan is now a reviewer

**Comment by AstrobioMike** [comment]
Hi there, @emckiernan! I'm sorry to say i'm not able to help out on this one unfortunately :/

**Comment by emckiernan** [comment]
> Hi there, @emckiernan! I'm sorry to say i'm not able to help out on this one unfortunately :/

No worries, thanks for letting us know.

**Comment by emckiernan** [comment]
Hi, @pschloss, you signed up to review for JOSE. Would you like to contribute a review for this submission? The title is "The Gene School: Metagenomics". Let me know if you're available and willing. Thanks!

**Comment by emckiernan** [comment]
@whedon add @pschloss as reviewer

**Comment by whedon** [comment]
OK, @pschloss is now a reviewer

**Comment by emckiernan** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/79.
