### ISSUE TITLE
[PRE REVIEW]: ClimateEstimate.net: A tutorial on climate econometrics

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#81]
**Submitting author:** @jrising (<a href="http://orcid.org/0000-0001-8514-4748">James Rising</a>)
**Repository:** <a href="https://github.com/atrisovic/weather-panel.github.io" target ="_blank">https://github.com/atrisovic/weather-panel.github.io</a>
**Version:** v1.2
**Editor:** @kyleniemeyer
**Reviewers:** @howardjp, @jwagemann

**Author instructions**

Thanks for submitting your paper to JOSE @jrising. **Currently, there isn't an JOSE editor assigned** to your paper.

@jrising if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (1019.2 files/s, 67469.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Sass                            62           1009            465           3348
Markdown                        13            430              0           1008
HTML                            22             96             34            659
JavaScript                      10             69             96            370
SVG                              7              0              5            157
YAML                             3             47             92            136
TeX                              2              5              0             99
Jupyter Notebook                 1              0            296             55
XML                              6              0              0             44
JSON                             1              0              0             29
make                             1              9              1             28
Python                           1              3              1              9
CSS                              1              0              1              5
-------------------------------------------------------------------------------
SUM:                           130           1668            991           5947
-------------------------------------------------------------------------------


Statistical information for the repository '81' was gathered on 2020/04/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Ana Trisovic                     2           961           1155           74.04
atrisovic                        1           742              0           25.96

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Ana Trisovic                548           57.0          3.8               17.70
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.3386/w25189 may be missing for title: An economist’s guide to climate change science
- https://doi.org/10.3386/w22181 may be missing for title: Climate econometrics
- https://doi.org/10.1088/1748-9326/ab281e may be missing for title: Assessing future climate change impacts in the EU and the USA: insights and lessons from two continental-scale projects
- https://doi.org/10.1002/wcc.579 may be missing for title: On the use and misuse of climate change projections in international development

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00081/jose.00081/10.21105.jose.00081.pdf)

**Comment by jrising** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by jrising** [comment]
Possible editors:
Julia Wagemann
Angela Li
James P. Howard, II

**Comment by jrising** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00081/jose.00081/10.21105.jose.00081.pdf)

**Comment by atrisovic** [comment]
Hi @labarba! It is exciting to see more activity in this repository! 🙌  We are eager to see if our submission is a good fit for the journal and if it is, interact with editors to make it better. 😄

**Comment by labarba** [comment]
👋  @atrisovic — I am the single-point-of-failure here, as I'm heavily overcommitted. I am trying to start chipping away at neglected tasks, like JOSE editing. 

I read your paper and I'm going to send it back to you for some more work, because it does not quite meet our expectations. In particular, see the section of our Documentation about the [What should my paper contain?](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain). We ask that you

> Include a “Statement of Need” section, explaining how the submitted artifacts contribute to computationally enabled teaching and learning, and describing how they might be adopted by others.
> For learning modules, describe the learning objectives, content, instructional design, and experience of use in teaching and learning situations.

The text does address the gap this fills, but we ask for a section heading for the Statement of Need. The second item is missing, and is important for another instructor to imagine how they might re-use your tutorial for their teaching needs.

Thank you for your patience! Tough times.

**Comment by jrising** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00081/jose.00081/10.21105.jose.00081.pdf)

**Comment by jrising** [comment]
@labarba Thank you again. We have now extensively revised (if I can use that phrase with such a short paper) our `paper.md`. There is now a statement of need, and adding more text on the structure of the tutorial, its objectives, and our experience using it. If you are available, we would very much appreciate it if you took a look again.

In the meantime, the tutorial has also been improved. Thanks!

**Comment by kyleniemeyer** [comment]
Hi @labarba @jrising @atrisovic I can take over editing this submission. It does look like the authors have revised the paper to include the material that was missing originally, and I think we can now identify reviewers and move forward.

**Comment by kyleniemeyer** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Hello @jwagemann  @angela-li and @howardjp , this authors of this submission to JOSE (Journal of Open Source Education, https://jose.theoj.org) suggested you as potential reviewers for their submission "ClimateEstimate.net: A tutorial on climate econometrics".

Are you interested and available to review this for us? Thanks!

**Comment by howardjp** [comment]
I can do that.

**Comment by jwagemann** [comment]
Hi, by when would you need the review?

**Comment by kyleniemeyer** [comment]
Thanks @howardjp!

Hi @jwagemann, ideally we would like reviews within the next three weeks or so, but I recognize that many people have lots of other pressing obligations particularly now. So, if you are willing to review this but need more time, that is totally fine.

**Comment by kyleniemeyer** [comment]
@whedon add @howardjp as reviewer

**Comment by whedon** [comment]
OK, @howardjp is now a reviewer

**Comment by jwagemann** [comment]
@kyleniemeyer Happy to review it by end of October (if this is not too late).

**Comment by kyleniemeyer** [comment]
@jwagemann sure, that would be fine. Thanks!

**Comment by kyleniemeyer** [comment]
@whedon add @jwagemann as reviewer

**Comment by whedon** [comment]
OK, @jwagemann is now a reviewer

**Comment by kyleniemeyer** [comment]
OK, with two reviewers assigned we can move into the actual review issue!

**Comment by kyleniemeyer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/90.
