### ISSUE TITLE
[PRE REVIEW]: An open source crash course on parameter estimation of computational models using a Bayesian optimization approach

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#82]
**Submitting author:** @mbarzegary (<a href="http://orcid.org/0000-0002-1456-0610">Mojtaba Barzegari</a>)
**Repository:** <a href="https://github.com/mbarzegary/educational-bayesian" target ="_blank">https://github.com/mbarzegary/educational-bayesian</a>
**Version:** v1.0.0
**Editor:** @magsol
**Reviewers:** @e-dub, @jcapriot

**Author instructions**

Thanks for submitting your paper to JOSE @mbarzegary. **Currently, there isn't an JOSE editor assigned** to your paper.

@mbarzegary if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (202.2 files/s, 39191.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                 1              0            809            233
Markdown                         3             22              0             47
TeX                              1              2              0             21
Python                           1              7              6             16
-------------------------------------------------------------------------------
SUM:                             6             31            815            317
-------------------------------------------------------------------------------


Statistical information for the repository '82' was gathered on 2020/04/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mbarzegary                       1            29              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mbarzegary                   29          100.0          0.0               20.69
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1007/978-94-009-0909-0 is OK

MISSING DOIs

- https://doi.org/10.1016/0031-9201(89)90124-6 may be missing for title: Inverse Problem Theory: Methods for Data Fitting and Model Parameter Estimation

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #82 with the following error: 

 Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.342 \$ A + 2B \rightleftharpoons

Looks like we failed to compile the PDF

**Comment by mbarzegary** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00082/jose.00082/10.21105.jose.00082.pdf)

**Comment by mbarzegary** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00082/jose.00082/10.21105.jose.00082.pdf)

**Comment by mbarzegary** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by mbarzegary** [comment]
@whedon list editors

**Comment by whedon** [comment]
Current editors:

```
@IanHawke
@RobertTalbert
@csev
@emckiernan
@juanklopper
@katyhuff
@kyleniemeyer
@labarba
@magsol
@moorepants
@racheltho
@tracykteal
@willingc
```

**Comment by mbarzegary** [comment]
suggested editor:  magsol
suggested reviewer: matbesancon

**Comment by ThomasA** [comment]
Just a suggestion: maybe @magsol and @matbesancon did not notice they were mentioned?

**Comment by mbarzegary** [comment]
Thanks @ThomasA 
I did this because the bot instruction was writing the names without tagging them.

**Comment by matbesancon** [comment]
Hi, thanks for pinging me but I'm not sure I am the right  person for this review, I don't focus on Bayesian models

**Comment by magsol** [comment]
Likewise, thank you for pinging me on this--was not getting the notifications otherwise!

This is also outside my area of immediate expertise but I have enough experience to be dangerous... or, at the very least, to take a stab at recruiting some reviewers, especially since you've been waiting so patiently for far too long. Let me see what I can do over the next couple days.

**Comment by magsol** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by magsol** [comment]
@whedon assign @e-dub as reviewer

**Comment by whedon** [comment]
OK, @e-dub is now a reviewer

**Comment by magsol** [comment]
Checking in--sorry for the delay, still trying to find a second reviewer.

**Comment by mbarzegary** [comment]
Thanks @magsol.

**Comment by magsol** [comment]
@whedon add @jcapriot as reviewer

**Comment by whedon** [comment]
OK, @jcapriot is now a reviewer

**Comment by magsol** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/89.

**Comment by magsol** [comment]
Sorry it took me awhile to find the reviewers, but we're ready to go--thanks to @e-dub and @jcapriot!
