### ISSUE TITLE
[PRE REVIEW]: 1build: Frictionless way of managing project-specific commands

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#84]
**Submitting author:** @gopinath-langote (<a href="http://orcid.org/0000-0002-2583-6459">Gopinath Langote</a>)
**Repository:** <a href="https://github.com/gopinath-langote/1build" target ="_blank">https://github.com/gopinath-langote/1build</a>
**Version:** v1.5.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @gopinath-langote. **Currently, there isn't an JOSE editor assigned** to your paper.

@gopinath-langote if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (922.3 files/s, 63010.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Go                              26            345             50           2031
Markdown                         5             87              0            236
YAML                            12             29             20            162
TeX                              1              3              0             43
-------------------------------------------------------------------------------
SUM:                            44            464             70           2472
-------------------------------------------------------------------------------


Statistical information for the repository '84' was gathered on 2020/07/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Gopinath Langote                39          1107           1335           85.68
Manish Jain                      1            63             28            3.19
Mayur Kumbhar                    1            69             11            2.81
Ritabrata Moitra                 2           186             51            8.32

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00084/jose.00084/10.21105.jose.00084.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.12688/f1000research.11407.1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
👋 @gopinath-langote — First of all, I apologize for the long delay in processing your submission. This is entirely due to me dropping JOSE altogether since the pandemic struck. It has just been too difficult to concentrate and keep productive, which means volunteer efforts fall to the bottom of the priority list.

Now, I'm afraid that your submission is not in-scope for The Journal of Open Source Education. Please read about our [scope and submission requirements](https://jose.theoj.org/about). JOSE publishes two types of articles that describe: 
(1) open-source educational materials;
(2) open-source educational software tools.
Your submission is neither of these.

Therefore, your submission is administratively rejected as out-of-scope.

**Comment by adeepak7** [comment]
@labarba , I respect your point of view. But the fact is, 1Build lies inside the scope of the journal.

According to the definition of the "educational software tools" as defined on JOSE official website:

What do you mean by "educational software tools"?
Open-source software that serves as educational technology; examples include (but are not limited to) alternatives to learning management systems, autograders, cloud systems for lesson delivery, student collaboration tools. For these tools, peer review will follow a similar process as JOSS.

The 1Build tool is a learning management tool. 

Now, what are learning management tools?

According to Wikipedia:

A learning management system is a software application for the administration, documentation, tracking, reporting, automation and delivery of educational courses, training programs, or learning and development programs.

1build is an automation tool used for research and development projects that arms you with the convenience to configure project-local command line aliases – and then run the commands quickly and easily. It is particularly helpful when you deal with multiple projects and switch between them all the time. It is often the fact that different projects use different build tools and have different environment requirements – and then switching from one project to another is becoming increasingly cumbersome. That is where 1build comes into play.

What do users of 1Build learn?
1)  Need of how to manage projects. 
2) Indirectly learn the need for CI/CD.
3) Learns to write commands and hence to code.

Which I believe completely lies in scope of JOSE.

Therefore, I request you to give it a second  opportunity and reconsider the submission.

Thanks,
Deepak Ahire

**Comment by labarba** [comment]
>1build is an automation tool used for research and development projects that arms you with the convenience to configure project-local command line aliases 

JOSE does not publish this sort of tool. The scope of JOSE is _education_.

**Comment by adeepak7** [comment]
@labarba Kindly let me know what according to you is against education in this project. Users of 1Build learn to manage their project by use of automation.

By gradually using and learning to use 1Build, users are educated importance of automation and how to save time.

Appreciate your thoughts on this.

**Comment by labarba** [comment]
Perhaps I wasn't clear: The Journal of Open Source Education publishes material or software _specifically targeting its use within the context of teaching_.
