### ISSUE TITLE
[PRE REVIEW]: Interactive Bin Packing: A Java Application for Learning Constructive Heuristics for Combinatorial Optimization

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#87]
**Submitting author:** @cicirello (<a href="http://orcid.org/0000-0003-1072-8559">Vincent A Cicirello</a>)
**Repository:** <a href="https://github.com/cicirello/InteractiveBinPacking" target ="_blank">https://github.com/cicirello/InteractiveBinPacking</a>
**Version:** v3.0
**Editor:** @labarba
**Reviewers:** @adeepak7, @turketwh

**Author instructions**

Thanks for submitting your paper to JOSE @cicirello. **Currently, there isn't an JOSE editor assigned** to your paper.

@cicirello if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/ICPP.1999.797428 is OK
- 10.1007/s11276-005-5266-y is OK
- 10.1145/1508865.1508951 is OK
- 10.1145/1047344.1047409 is OK

MISSING DOIs

- https://doi.org/10.1007/springerreference_5277 may be missing for title: Bin packing

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00087/jose.00087/10.21105.jose.00087.pdf)

**Comment by labarba** [comment]
Hi @cicirello 👋  — I apologize for not delivering on expectations here, but JoSE became abandoned when I got crushed with other commitments, plus online teaching, and many changes and stresses due to the world chaos of the past year. I'm just getting back to audit all the dropped balls and try to pick them up one by one.

I have read your paper, and understand that your submission is about a tutorial on the bin-packing optimization problem. However, I am not able to figure out how your tutorial works, without presumably installing the Java application? Can you help me understand how it works?

**Comment by labarba** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.33 s (85.0 files/s, 12249.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            18            221            808           2072
HTML                             3             83              0            454
Markdown                         3             56              0            105
TeX                              1             16              0             90
Ant                              1             11             10             74
YAML                             2              6              6             24
-------------------------------------------------------------------------------
SUM:                            28            393            824           2819
-------------------------------------------------------------------------------


Statistical information for the repository 'ddfc039c1d7e9a2adee9baa4' was
gathered on 2021/02/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vincent Cicirello                3          3102              1          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent A. Cicirello       3101          100.0          0.0               26.06
```

**Comment by cicirello** [comment]
@labarba I totally understand about the delay. The application itself explains how it functions, etc. There is a prebuilt executable jar file in the dist directory. Assuming you have Java 8 or higher on your system, you can run it by either double clicking the jar file or executing the following on the command line: `java -jar interactive-bin-packing-3.0.jar`

Once the application is open, there is a Tutorial option in the Info menu. That will walk you through usage of all application functions as well as the tutorial itself.

**Comment by labarba** [comment]
Thanks! 

I, personally, am not a computer scientist, have never touched Java, and cannot install the application. Before I can determine who might be an editor to handle this submission, I need to understand what it does. Could you briefly explain it to me, understanding that I cannot install it?

**Comment by cicirello** [comment]
@labarba I think I may have edited my original response while you were replying. Is the new last paragraph of my previous reply what you are looking for?

**Comment by csev** [comment]
At the request of the EiC, I have downloaded and installed this software.   Following the documentation it starts and runs and makes sense given the problem that it solves.   It feels somewhat narrow in its application - it would be a great interactive part of a week of an advanced algorithms course towards the end of undergraduate program or at the beginning of a masters program in Computer Science.    The source code is readable - I assume students looking at the source code would be part of any exercise.  It is pretty clear what it is and how it works - I am curious as to how this is used in a course.

**Comment by cicirello** [comment]
@csev I've used it in a couple different courses in a couple different ways. Here are a couple examples:

1) In an upper level undergrad AI course, just before covering randomized heuristics, I have the students work through the tutorial as part of a homework assignment (I usually give them a specific instance number so they can submit the various heuristic solutions as proof they worked through the tutorial). They usually then must work through the heuristic solutions to a problem instance not in the app.

A followup assignment involves implementing the heuristics.

I then cover in class some algorithms that rely on randomizing constructive heuristics such as ant colony optimization. 

2) In that same course, I have also had students design and implement their own heuristic for the problem, and they seem to find it useful using the application to try out ideas by hand while they are designing their heuristic but befire implementing it.

3) In a non-majors intro course where students have very little, if any, prior cs background (a course with no prereqs), I have also used it in a similar way to #1 above, but without the followup implementation assignment. But for non-majors I usually provide an in class overview, whereas in #1 above the assignment to use the tutorial serves as the intro where I then cover the more advanced content in class.

4) A much earlier version lacked the functionality to verify the users' understanding of heuristic. I used that prior version in a classroom as a visualization tool while explaining the concepts. It can still be used in that way.

**Comment by labarba** [comment]
Hi @cicirello 👋  — we discussed your submission a bit more and find it to be too small / too narrow to merit a journal publication. Bear in mind that JOSE is evaluating the educational resources submitted with the goal of giving scholarly credit to this often unrecognized work. We want readers, authors (and their employers) to recognize JOSE papers similarly to research publications, and thus it should represent substantial scholarly effort.

**Comment by cicirello** [comment]
@labarba can you please define what is meant by a course "module" in this statement in the journal's scope: "The ideal submission size is a course module"?

**Comment by labarba** [comment]
Sure. We understand that to mean a section of a course, with its own learning objectives, content, and activities. More than a single lesson, but less than a semester course (although some submissions are a full course). The ideal module length might be around 3 to 5 weeks of a semester, or something that can be taught in an intense two-day Summer school.

**Comment by cicirello** [comment]
@labarba thanks. It might be helpful to potential authors if the 3 to 5 weeks of a course is mentioned in the scope, perhaps in parentheses after the word module. My submission otherwise has "its own learning objectives, content, and activities" but is more around 1 week to maybe 2 weeks (if students are more introductory level). It would also be helpful if determinations like this are made sooner than 10 months in "pre-review."

**Comment by labarba** [comment]
What I quote is the ideal length from my perspective, given that JOSE will give "one publication credit" for the work. We want to be mindful that JOSE papers are taken seriously by the community. One to 2 weeks of a course is 2.5 to 5 hours of instruction. That is borderline, in my assessment. We _have_ reviewed submissions that are like a tech-conference tutorial (which tend to vary between 4 and 8 hours of live instruction). It sounds like it might be possible to consider this submission, maybe if you were willing to put in a bit of work on making it more clear that this is not for a single in-class activity (that would be below the bar). Maybe combining the _application_ with a written tutorial. Did you submit to the software, or to the learning module article type?

---

Our documentation is not perfect, but like for any journal, looking at past published papers should help gage the scoping question. As for the 10 months in pre-review, JOSE is an initiative led by the volunteer editors, who have faced immeasurable challenges the past 14 months, for obvious reasons. One in five of our editors have completely stopped responding, and we don't know about their wellbeing. I personally have a work backlog measured in months not weeks, but I'm here on a Sunday to give just a bit more of me.

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by cicirello** [comment]
@labarba I submitted it to the software article type. There is a written tutorial within the application itself.

**Comment by labarba** [comment]
hi @cicirello — could you add in the paper a description of the expected instruction time with this tutorial? Include an idea of any direct instruction (lecture) needed to get the lesson started, and expected student self-directed-learning time. (I've made a note to add this to the documentation as something we want in the paper.) Also useful would be a few sentences of advice to any instructor who wished to adopt this in their own teaching.

From our [docs](https://openjournals.readthedocs.io/en/jose/submitting.html#submission-requirements):

> Computational learning modules should be complete and immediately usable for self-learning or adoption by other instructors.

We need a bit o help understanding how your submission satisfies this criterion.

**Comment by cicirello** [comment]
@labarba I can do that. I think I can find time this week actually.

**Comment by cicirello** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/ICPP.1999.797428 is OK
- 10.1007/s11276-005-5266-y is OK
- 10.1145/1508865.1508951 is OK
- 10.1145/1047344.1047409 is OK

MISSING DOIs

- 10.1007/springerreference_5277 may be a valid DOI for title: Bin packing

INVALID DOIs

- None
```

**Comment by cicirello** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (369.2 files/s, 60064.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Java                            18            298            836           2623
HTML                             3             83              0            454
Maven                            1             17              0            313
TeX                              2             84             62            302
Markdown                         3             61              0            294
YAML                             5             43             30            182
SVG                              2              0              0              2
TOML                             1              2              6              2
-------------------------------------------------------------------------------
SUM:                            35            588            934           4172
-------------------------------------------------------------------------------


Statistical information for the repository '17b6daf1f5a0eebcb04a0699' was
gathered on 2021/06/09.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Vincent A. Cicirello            18           766            110           22.02
Vincent Cicirello                3          3102              1           77.98

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Vincent A. Cicirello       3757          490.5          0.1               22.25
```

**Comment by cicirello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00087/jose.00087/10.21105.jose.00087.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00087/jose.00087/10.21105.jose.00087.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
@campbe13 – hi! 👋 
A while back you signed up to be a reviewer for JOSE, the Journal of Open Source Education. I wonder if you could help us out with this submission here: 
**Interactive Bin Packing: A Java Application for Learning Constructive Heuristics for Combinatorial Optimization**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00087/jose.00087/10.21105.jose.00087.pdf)
It's a Java application that generates random instances of the bin packing problem, to be used as a tutorial and an activity for students.

**Comment by labarba** [comment]
@adeepak7  – hi! 👋 
A while back you signed up to be a reviewer for JOSE, the Journal of Open Source Education. I wonder if you could help us out with this submission here: 
**Interactive Bin Packing: A Java Application for Learning Constructive Heuristics for Combinatorial Optimization**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00087/jose.00087/10.21105.jose.00087.pdf)
It's a Java application that generates random instances of the bin packing problem, to be used as a tutorial and an activity for students.

**Comment by adeepak7** [comment]
@labarba Thank you for giving me this opportunity. Having worked on standalone JAVA applications and their respective deployments, I promise to provide constructive feedback and raise relevant issues.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @adeepak7 as reviewer

**Comment by whedon** [comment]
OK, @adeepak7 is now a reviewer

**Comment by labarba** [comment]
Thank you for agreeing to review this for us, @adeepak7! I'm looking for a second reviewer, after which we will start the review on a new GitHub issue that will contain a checklist for each reviewer. You can start looking at the submission, but hold off on comments until we open the Review issue. 🙏

**Comment by labarba** [comment]
Looks like we're short of a reviewer for this submission. Sorry for the delay, @cicirello !

@mattforshaw — You signed to review for JOSE (The Journal of Open Source Education) a while back. Would you be interested in contributing a review for this one?
**Interactive Bin Packing: A Java Application for Learning Constructive Heuristics for Combinatorial Optimization**
[View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00087/jose.00087/10.21105.jose.00087.pdf)
It's a Java application that generates random instances of the bin packing problem, to be used as a tutorial and an activity for students.

**Comment by cicirello** [comment]
@labarba Delay is understandable, between covid, start of semester for many potential reviewers, etc....

**Comment by adeepak7** [comment]
@cicirello @labarba Apologies for the delay from my side as well. After a lot of hurdles, I moved to the U.S. for the first time.

**Comment by labarba** [comment]
@whedon add @turketwh as reviewer

**Comment by whedon** [comment]
OK, @turketwh is now a reviewer

**Comment by labarba** [comment]
Thank you @adeepak7 and @turketwh for agreeing to review this JOSE submission! I will now start the review, which will happen in a new GitHub issue. You will have a review checklist there. Be sure to accept the invitation you will receive from GitHub, which will open your permissions to edit on the checklist. 🙏

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/140.
