### ISSUE TITLE
[REVIEW]: General relativity in R: visual representation of Schwarzschild space using different coordinate systems

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#91]
**Submitting author:** @RobinHankin (<a href="http://orcid.org/0000-0001-5982-0415">Robin Hankin</a>)
**Repository:** <a href="https://github.com/RobinHankin/schwarzschild" target ="_blank">https://github.com/RobinHankin/schwarzschild</a>
**Version:** 1.0-5
**Editor:** @IanHawke
**Reviewer:** @atrisovic, @afolkest
**Archive:** <a href="https://doi.org/10.5281/zenodo.4784248" target="_blank">10.5281/zenodo.4784248</a>

## Status

[![status](https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465/status.svg)](https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465"><img src="https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465/status.svg)](https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/RobinHankin/schwarzschild" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@atrisovic & @afolkest, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @IanHawke know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/RobinHankin/schwarzschild">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0-5
- [x] **Authorship:** Has the submitting author (@RobinHankin) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/RobinHankin/schwarzschild">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 1.0-5
- [x] **Authorship:** Has the submitting author (@RobinHankin) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @atrisovic, @afolkest it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/978-3-642-58084-0_21 may be a valid DOI for title: Über das Gravitationsfeld eines Massenpunktes nach der Einsteinschen Theorie
- 10.1093/oso/9780198816461.003.0008 may be a valid DOI for title: The expanding universe
- 10.1103/physrev.110.965 may be a valid DOI for title: Past-Future asymmetry of the gravitational field of a point particle

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by IanHawke** [comment]
To keep all comments in one issue, the initial points that have been made are:

@atrisovic says:

[x] I don't mean specifically Minkowski diagram, but this is a paper on visual representation, so it would be helpful to see figures and diagrams that the package can produce in a few examples (*answered*: Just type `vignette("schwarzschild")` at the commandline)
[x] The paper doesn't say what R version the package is compatible with. This is important because R is not normally backward compatible. For example, can I run it with R 4.0? (*answered*: it will work with any verson of R >=3.0)
[x] The paper mentions rich documentation for the code, but there is no link to the documentation (*answered*: The documentation is in standard Rd format, accessible through the usual R help mechanism)
[ ] Mathematica is typically used for creating these diagrams. Are there any advantages to using this R package instead, and what are those?
[ ] There is a note on how the package was used, but it would also be helpful to see who the intended user group is? Is it the teachers and the undergrads? Students of astrophysics and HEP? Can the tool be used for some more advanced research?

**Comment by atrisovic** [comment]
Hi @RobinHankin,

I still stand behind my previous comments, but here is also a more official review based on the checklist above. 
On the package:

- There is no tagged version of the package on GitHub.
- There are no instructions for contributing to the package. Consider adding a `contributing.md` file. 
- There doesn't seem to be any tests in the package.
- I was initially unable to see the vignette, so I suggest changing the instructions command to: `devtools::install_github("RobinHankin/schwarzschild", build_vignettes = TRUE)`.

On the paper:

- The introduction does not introduce the paper's main contribution, which is an educational package for R
- The paper does not clearly state the need for this software and who the target audience is.
- The functionality and usage section could also be improved. Some of the sentences seem incomplete, like "heavy documentation" but no note that it's internal to R; "twenty functions" but no examples of any of them; "code is maintainable and extensible" but no comment on how or what would be potential further work.
- Consider adding a few diagrams in the paper. These would be helpful for the users who don't want to install the library to see the diagrams. Alternatively, if the vignette is available outside R, consider adding a link to it.
- A note on primary R version compatibility would be useful.
- Stylistic: some of the sentences might be too informal or exaggerated for an academic paper.

I am happy to have another look when the paper and the repository are updated.

Also, @IanHawke, thanks for kicking off the review. I'm not sure how to evaluate documentation and examples, as both are internal to R. It would be useful to have external examples to give the user a head start, but there are internal instructions for those who already installed the library.

**Comment by RobinHankin** [comment]
Hello @IanHawke   @atrisovic  @whedon 

thank you all for your comments, I have taken your suggestions on board and addressed them under https://github.com/RobinHankin/schwarzschild/issues/14 which is an umbrella issue that points to each of your observations as a separate repository issue.   The only comment I found confusing was "some of the sentences might be too informal or exaggerated for an academic paper", which left me feeling somewhat bewildered.  I have made changes here and there to the wording  but worry that I have misunderstood something.

@IanHawke  could please advise on my next action, and thanks again for your advice.  Best wishes, Robin

**Comment by atrisovic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by atrisovic** [comment]
> thank you all for your comments, I have taken your suggestions on board and addressed them under [RobinHankin/schwarzschild#14](https://github.com/RobinHankin/schwarzschild/issues/14) which is an umbrella issue that points to each of your observations as a separate repository issue. The only comment I found confusing was "some of the sentences might be too informal or exaggerated for an academic paper", which left me feeling somewhat bewildered. I have made changes here and there to the wording but worry that I have misunderstood something.

Ok, nice! I will review these changes to check off the remaining points in the checklist above. 

Sorry the comment was confusing - it was related to the sentence where you use personal pronouns which are not common in formal writing (ie, "as resources for **my own** astrophysics lectures at AUT, and secondly to support **my** Trin Tragula YouTube channel"). Also "heavily documented" seemed as an overstatement at the time. Would you like to change this before I review the text again?

**Comment by RobinHankin** [comment]
Hello @atrisovic  thanks for this clarification, I have now changed the wording as suggested in  commit  

https://github.com/RobinHankin/schwarzschild/commit/51386ba9901648af16d2c6e207e1444d6222938e

Best wishes,  Robin

**Comment by atrisovic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by afolkest** [comment]
Hi @RobinHankin 

I tested the functionality and it looks good to me. It would perhaps be good to add one sentence in the introduction of the paper stating what the paper describes -- namely a visualization package for all the coordinate systems you do mention there. A brief comment on what method you use to solve the geodesic equation would be informative as well.

Also, I was wondering where I could see a list of dependencies, if any? Also, there is no release version. 

Best,
Aasmund

**Comment by RobinHankin** [comment]
OK @afolkest, @atrisovic, @IanHawke @whedon, I have addressed all your comments at https://github.com/RobinHankin/schwarzschild/issues/14 and created 
  tag 1.0-3  at https://github.com/RobinHankin/schwarzschild/releases/tag/1.0-3.  I hope this is satisfactory!  If not, let me know.  Best wishes, Robin

**Comment by atrisovic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by atrisovic** [comment]
Hi again @RobinHankin,

I've now reviewed the package again and read the new version of the paper. The editor will probably better comment on these, but here are a few stylistic suggestions for the paper:

- The second sentence in the Statement of Need is a bit unclear. In particular, the part "not an object in its own right" is unclear.
- "GPL" -> General Public License
- Adding commas in a few places would help the reader:
    - "In computer terminology, one would need both the source code and the final image, but..."
    - "...which, as of October 2020, has..."
    - "...coordinate systems are available, including..."
- Why is plotting referred to as "side-effect", when that's the main functionality of the package?
    - "The package defines over twenty functions that are called for their side-effect of plotting a diagram of spacetime in the vicinity of a black hole." -> "The package defines over twenty functions that plot diagrams of spacetime in the vicinity of a black hole."
    - "Physical processes such as null geodesics and freely falling objects are simulated near a Schwarzschild black hole by the R functionality of the package; one side-effect is the the creation of usable and accurate PDF images." -> "Physical processes such as null geodesics and freely falling objects near a Schwarzschild black hole are simulated in R and plotted as usable and accurate PDF images."
- The Downloads section has only one sentence and an URL beyond the page width. I suggest moving the sentence in the previous section and hiding the URL.
    - For example: "Two example images ~~from the 19 in the package vignette~~ are shown below in low-resolution jpg format. ~~For vectorized PDF, see the package vignette.~~ All nineteen vectorized PDF images can be seen in the package vignette or online through [Microsoft Sharepoint](https://autuni-my.sharepoint.com/:f:/g/personal/rhankin_aut_ac_nz/EgX_IANsoOJDmTiH2i9_P20B6ksn9CMHf_TM31w5K3aITg?e=dPxAcp)."
    - Then remove the sentences: "For vectorized PDF version, see the package vignette or click the link below." **x2**
- jpg -> JPG format

Other than that, everything looks good to me, and all the boxes from the reviewers' list are now checked.

**Comment by RobinHankin** [comment]
Hello  @atrisovic, thank you for your suggestions.  I have addressed all of them 
under https://github.com/RobinHankin/schwarzschild/issues/14 and I think the paper reads much better as a result.  Tag 1.0-4  at https://github.com/RobinHankin/schwarzschild/releases/tag/1.0-4 refers.   What is the next step?  Best wishes, Robin

**Comment by atrisovic** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by atrisovic** [comment]
Ok, fantastic, you incorporated everything. Well, I'd still call the section "Examples" instead of "Downloads". And the last sentence in both of the figure captions could be now removed. (sorry for nitpicking!) :smile:

But yeah, we now wait for further instructions from @IanHawke.

**Comment by RobinHankin** [comment]
OK @atrisovic, thanks for these, no worries.  Happy to adjust the paper as suggested, see https://github.com/RobinHankin/schwarzschild/issues/14 and tagged at https://github.com/RobinHankin/schwarzschild/releases/tag/1.0-5  

@IanHawke  I have changed the paper (and the vignette) in response to the comments by the referees and I await your instructions.  Best wishes,  Robin

**Comment by RobinHankin** [comment]
hello JOSE, can I ask what the status of this submission is please?

**Comment by kyleniemeyer** [comment]
@IanHawke it looks like this submission may be ready for some action/review by you?

**Comment by RobinHankin** [comment]
Sorry to ask again, but could I check if there are any actions on me?

**Comment by RobinHankin** [comment]
hello JOSE, can I ask what the status of this submission is please?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00091/jose.00091/10.21105.jose.00091.pdf) :page_facing_up: :point_left:

**Comment by RobinHankin** [comment]
thanks for this, the proof looks good

**Comment by RobinHankin** [comment]
Hello, I see from

https://jose.theoj.org/papers/ab50474b49636cdac6ba2687f051b465

that the paper is still under review, can I ask what the status of the submission is please?

**Comment by RobinHankin** [comment]
@kyleniemeyer 
@IanHawke 
@labarba 

hello, can I ask what the status of the submission is please?

**Comment by labarba** [comment]
Hi @RobinHankin — Apologies for the ball dropped here, and thank you for your enormous patience. I see from the review thread that thorough reviews were contributed, and you made changes to accommodate the reviewer requests. All checklist items are marked out. Let's get this past the finish line! 

Could you now up the version, issue a tagged release in your repo, and make a Zenodo deposit? Report the version number here, as well as the Zenodo DOI, so we can run the commands to update that metadata for the submission. Then we can proceed to publication.

**Comment by labarba** [comment]
@whedon set 1.0-5 as version

**Comment by whedon** [comment]
OK. 1.0-5 is the version.

**Comment by labarba** [comment]
I see that there are no further commits on the repo after version 1.0-5, so I've set this as the version number.

We just need the Zenodo archive DOI now.

**Comment by labarba** [comment]
@RobinHankin — on checking your paper, I see that we will need you to add the DOIs for references that have them.

**Comment by RobinHankin** [comment]
hello Lorena, thank you for this!  Looking at the references, they are all
quite old and do not have DOIs.  I have uploaded to zenodo as you suggested
and it gave me 10.5281/zenodo.4782758

as the (provisional?) DOI.

Many thanks

Robin


***@***.***>

**Comment by labarba** [comment]
Hi @RobinHankin — I checked the Zenodo archive at https://doi.org/10.5281/zenodo.4782757 and you deposited the PDF of the JOSE paper. What we request is an archive of the submission _repository_ at https://github.com/RobinHankin/schwarzschild

This guide may be useful: https://guides.github.com/activities/citable-code/

**Comment by RobinHankin** [comment]
thank you for this Lorena, sorry for the confusion, I have now pointed to
release 1.0-5 on zenodo as you requested.

With best wishes

Robin


***@***.***>

**Comment by labarba** [comment]
I checked the Zenodo archive at https://doi.org/10.5281/zenodo.4782757 and still see only the PDF of the paper there. The complete file set in the repository needs to be archived for persistence in the scholarly record. If you made a new Zenodo deposit, please post the link here.

**Comment by RobinHankin** [comment]
OK Lorena, thank you for your help here, the schwarzschild repo is now
visible on the zenodo page:

https://zenodo.org/record/4784248#.YKy61nUzZNg

Best wishes

Robin



***@***.***>

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.4784248 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4784248" target="_blank">10.5281/zenodo.4784248</a> is the archive.

**Comment by labarba** [comment]
@RobinHankin – Almost there! We'd like to ask that you edit the metadata of the Zenodo deposit so the title and author list match the JOSE paper. (Zenodo grabs authors automatically from committers to your repo: it needs to be manually fixed.)

**Comment by RobinHankin** [comment]
OK Lorena, done!

https://zenodo.org/record/4784248


***@***.***>

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
:wave: @openjournals/jose-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/53

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/53, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1007/978-3-642-58084-0_21 may be a valid DOI for title: Über das Gravitationsfeld eines Massenpunktes nach der Einsteinschen Theorie
- 10.1093/oso/9780198816461.003.0008 may be a valid DOI for title: The expanding universe
- 10.1103/physrev.110.965 may be a valid DOI for title: Past-Future asymmetry of the gravitational field of a point particle

INVALID DOIs

- None
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/54
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/jose.00091](https://doi.org/10.21105/jose.00091)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @RobinHankin, your JOSE paper is now published! 🚀 

Huge thanks to the Reviewers: @atrisovic, @afolkest — we are grateful for your contribution 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00091/status.svg)](https://doi.org/10.21105/jose.00091)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00091">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00091/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00091/status.svg
   :target: https://doi.org/10.21105/jose.00091
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00091/status.svg)](https://doi.org/10.21105/jose.00091)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future.
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-jose

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
