### ISSUE TITLE
[PRE REVIEW]: A narrative approach to building computational capacity for climate change impact assessment in professional masters students

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#93]
**Submitting author:** @ConorIA (<a href="http://orcid.org/0000-0003-2619-1207">Conor I. Anderson</a>)
**Repository:** <a href="https://gitlab.com/claut/man_ccia" target ="_blank">https://gitlab.com/claut/man_ccia</a>
**Version:** 2020-07-26
**Editor:** @labarba
**Reviewers:** @ali-ramadhan, @jwagemann

**Author instructions**

Thanks for submitting your paper to JOSE @ConorIA. **Currently, there isn't an JOSE editor assigned** to your paper.

@ConorIA if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.08 s (463.2 files/s, 45822.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Rmd                             15            704           1014           1004
TeX                              7             50              4            375
CSS                              2             10              0            191
R                                4             12              3             75
YAML                             3              4              0             59
Dockerfile                       2              9              0             38
make                             1             14              0             35
Markdown                         2             14              0             33
Python                           1              3              0              9
-------------------------------------------------------------------------------
SUM:                            37            820           1021           1819
-------------------------------------------------------------------------------


Statistical information for the repository 'b8ef7812374909cd006f47e7' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Conor Anderson                   2            14              2          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Conor Anderson               12           85.7          0.0                0.00
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00093/jose.00093/10.21105.jose.00093.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00093/jose.00093/10.21105.jose.00093.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/JCLI-D-14-00754.1 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
Hi @ConorIA — thank you for your submission to JOSE. We've had the journal in a holding pattern since the pandemic hit, mainly because I became overwhelmed with pivoting online teaching, research, and JupyterCon (I was General Chair). Thank you for your patience. I am beginning to dig up from a long backlog, so you'll begin seeing some movement.

Could you help with some leads of people we might reach out to for a review of this work? Many thanks!

**Comment by labarba** [comment]
@whedon assign @ali-ramadhan as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @ali-ramadhan as reviewer

**Comment by whedon** [comment]
OK, @ali-ramadhan is now a reviewer

**Comment by labarba** [comment]
hi @ali-ramadhan 👋  — thank you for agreeing to review this submission for JOSE. We'll be looking for a second reviewer, and then start the REVIEW issue, where all the action happens. Have a look at an [old example review](https://github.com/openjournals/jose-reviews/issues/53): you'll get a checklist as shown there to guide you, and you'll be encouraged to open issues on the submission repository (adding a cross-link with the review). Stay tuned!

**Comment by labarba** [comment]
@whedon add @jwagemann as reviewer

**Comment by whedon** [comment]
OK, @jwagemann is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/100.

**Comment by ConorIA** [comment]
Hi @labarba, you folks are fast. So glad that you've found two reviewers. Thanks! See you on #100!
