### ISSUE TITLE
[PRE REVIEW]: Hacking Health Covid-19: An Online Data Science Course-Project

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#94]
**Submitting author:** @warint (<a href="http://orcid.org/0000-0002-5921-3428">Thierry Warin</a>)
**Repository:** <a href="https://github.com/warint/covid19_article" target ="_blank">https://github.com/warint/covid19_article</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @jhelvy, @lwjohnst86

**Author instructions**

Thanks for submitting your paper to JOSE @warint. **Currently, there isn't an JOSE editor assigned** to your paper.

@warint if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=1.03 s (127.0 files/s, 64139.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                             13           2190            596          21602
HTML                            27           4344            821          18560
JavaScript                      25           1276           2072           5630
SVG                             18              1              1           2763
Stylus                          43            602            218           2556
XML                              1              0             42           1505
TeX                              1             77              0           1023
Markdown                         2             70              0            119
Rmd                              1             37             74              1
-------------------------------------------------------------------------------
SUM:                           131           8597           3824          53759
-------------------------------------------------------------------------------


Statistical information for the repository 'ffcd793396d56a2550b57c55' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Marine Leroi                     1         28798              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marine Leroi              28798          100.0          0.0               14.86
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00094/jose.00094/10.21105.jose.00094.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00094/jose.00094/10.21105.jose.00094.pdf) :page_facing_up: :point_left:

**Comment by labarba** [comment]
Hi @warint — thank you for your submission to JOSE. We've had the journal in a holding pattern since the pandemic hit, mainly because I became overwhelmed with pivoting online my teaching, research, and JupyterCon (I was General Chair). Thank you for your patience. I am beginning to dig up from a long backlog, so you'll begin seeing some movement.

Could you help with some leads of people we might reach out to for a review of this work? Many thanks!

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon assign @jhelvy as reviewer

**Comment by whedon** [comment]
OK, @jhelvy is now a reviewer

**Comment by labarba** [comment]
hi @jhelvy  👋 — thank you for agreeing to review this submission for JOSE. We'll be looking for a second reviewer, and then start the **REVIEW issue**, where all the action happens. Have a look at an [old example review](https://github.com/openjournals/jose-reviews/issues/53): you'll get a checklist as shown there to guide you, and you'll be encouraged to open issues on the submission repository (adding a cross-link with the review issue). Stay tuned!

**Comment by labarba** [comment]
@whedon add @lwjohnst86 as reviewer

**Comment by whedon** [comment]
OK, @lwjohnst86 is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/101.

**Comment by labarba** [comment]
👋  @jhelvy, @lwjohnst86 — Thank you for agreeing to review for JOSE! This is where the action happens. You both have a review checklist to work through. Feel free to post any questions here. If you open new issues on the submission repository, please link to this issue here. Godspeed!

[Reviewer guidelines](http://jose.theoj.org/about#reviewer_guidelines)
