### ISSUE TITLE
[PRE REVIEW]: An Open-Source Active Learning Curriculum for Data Science

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#96]
**Submitting author:** @zdelrosario (<a href="http://orcid.org/0000-0003-4676-1692">Zachary del Rosario</a>)
**Repository:** <a href="https://github.com/zdelrosario/data-science-curriculum" target ="_blank">https://github.com/zdelrosario/data-science-curriculum</a>
**Version:** v0.1
**Editor:** @ttimbers
**Reviewers:** @firasm

**Author instructions**

Thanks for submitting your paper to JOSE @zdelrosario. **Currently, there isn't an JOSE editor assigned** to your paper.

@zdelrosario if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.18 s (509.8 files/s, 93593.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Rmd                              75           3374           7388           4600
Markdown                         12            244              0            770
HTML                              1              9              1            642
R                                 1             12              3             67
make                              2             14              3             60
Python                            1              5              4             22
YAML                              1              5              0             14
Bourne Again Shell                1              5              1             13
--------------------------------------------------------------------------------
SUM:                             94           3668           7400           6188
--------------------------------------------------------------------------------


Statistical information for the repository '22462d79b965109f46c1e1ca' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zach                             3            38              7          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
zdelrosario                  31          100.0          0.0               16.13
```

**Comment by whedon** [comment]
PDF failed to compile for issue #96 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
hi @zdelrosario 👋  — it looks like you missed that you need to write a paper to describe your submission. See our documentation for [what your paper should contain](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain).

**Comment by zdelrosario** [comment]
@whedon generate pdf

@labarba thanks for the heads up! I'd written the paper to my development branch but forgot to merge that in. Trying again....

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00096/jose.00096/10.21105.jose.00096.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00096/jose.00096/10.21105.jose.00096.pdf) :page_facing_up: :point_left:

**Comment by zdelrosario** [comment]
Suggested reviewers (github usernames):

- mattforshaw
- lwjohnst86
- lebebr01

**Comment by labarba** [comment]
@ttimbers 👋  — could you handle this submission as editor?

**Comment by ttimbers** [comment]
Yes @labarba - happy to do so!

**Comment by labarba** [comment]
@whedon assign @ttimbers as editor

**Comment by whedon** [comment]
OK, the editor is @ttimbers

**Comment by labarba** [comment]
At some point, @pschloss had volunteered to review, but that was a couple of months ago. I've emailed to check again.

**Comment by labarba** [comment]
@whedon assign @pschloss as reviewer

**Comment by whedon** [comment]
OK, @pschloss is now a reviewer

**Comment by labarba** [comment]
Hi @ttimbers -- we new need one more reviewer and you can start the review! 🚀

**Comment by ttimbers** [comment]
Hi all - my deepest apologies for being absent for so long from here. I have contacted a potential reviewer. Will keep you updated as soon as I can confirm who this is.

**Comment by ttimbers** [comment]
@whedon assign @firasm as reviewer

**Comment by whedon** [comment]
OK, @firasm is now a reviewer

**Comment by ttimbers** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/117.

**Comment by ttimbers** [comment]
@pschloss , @firasm : the review issue is now started at #117 . There is a detailed checklist there. Many thanks for your help with this review! Please reach out to me if you have any questions as you work on this.
