### ISSUE TITLE
[PRE REVIEW]: censo2017: 2017 Chilean Census Easy Access Database

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#97]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/censo2017" target ="_blank">https://github.com/pachamaltese/censo2017</a>
**Version:** v0.1
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @pachamaltese. **Currently, there isn't an JOSE editor assigned** to your paper.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.11 s (421.3 files/s, 73897.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            17            745            198           2386
XML                              1              0              0           2067
R                               12            160            140            905
CSS                              4             99             49            431
JSON                             1              0              0            334
JavaScript                       5             69             40            291
Markdown                         3             44              0             81
YAML                             2             17              0             58
Rmd                              1             19             49             50
SVG                              1              0              1             11
-------------------------------------------------------------------------------
SUM:                            47           1153            477           6614
-------------------------------------------------------------------------------


Statistical information for the repository '7d9ec0919c4964661652506d' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Mauricio Vargas                  3           400              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Mauricio Vargas             400          100.0          0.0               10.00
```

**Comment by whedon** [comment]
PDF failed to compile for issue #97 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment]
hi @pachamaltese 👋  — it looks like you missed that you have to write a paper to go along with your submission. Regardless, this work seems out of scope for JOSE. See our documentation on [submission types](https://openjournals.readthedocs.io/en/jose/submitting.html#the-two-submission-types):

> JOSE accepts two types of submissions: (1) computational learning modules, created as open educational resources (OER), and (2) open-source software, created as educational technology or infrastructure.

**Comment by pachamaltese** [comment]
thanks @labarba 
unintentionally, I broke something in the repo
I wonder what happened to "datos" pre-submission, that one is 100% educational

**Comment by pachamaltese** [comment]
@labarba are web subbmisions working?
for example, https://jose.theoj.org/papers/c909ff09584aa196e1ecf408a3ee8e87 was resubmitted as we didn't hear from you since june

**Comment by labarba** [comment]
I'm confused. That submission is from 11 days ago. Please be aware that we are under reduced operations since the pandemic hit, as all volunteers have increased work loads and personal obligations.

**Comment by pachamaltese** [comment]
> I'm confused. That submission is from 11 days ago. Please be aware that we are under reduced operations since the pandemic hit, as all volunteers have increased work loads and personal obligations.

I hope things are well there

**Comment by labarba** [comment]
@pachamaltese — I still don't see a paper to go along with this submission. However, from inspecting the repository, it looks like this may be out of scope for JOSE. It looks like this project is providing access to a data base (census data) that otherwise is available on physical storage medium. 

JOSE provides publication credit for substantial work developing software in support of the teaching mission (e.g., auto-graders for computational notebooks, see [nbgrader](https://jose.theoj.org/papers/10.21105/jose.00032)), or developing learning materials that use computing integrated in the curriculum. Those are the two [submission types](https://openjournals.readthedocs.io/en/jose/submitting.html#the-two-submission-types).

**Comment by pachamaltese** [comment]
Hi Lorena. Yes, you are right. It's out of the scope in that case.

**Comment by labarba** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
